### ISSUE TITLE
Adapt the package generation with the SSL option

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#100]
Hello team

  We need to take into account this change:

https://github.com/wazuh/wazuh/pull/1856

in order to generate the packages. Also, we need to remove the line: 

https://github.com/wazuh/wazuh-packages/blob/master/rpms/SPECS/3.7.1/wazuh-manager-3.7.1.spec#L132

Best regards,

**Comment by BraulioV** [comment]
Hi @alberpilot,

I'm currently working in this branch [3.7.1-add-ssl-option](https://github.com/wazuh/wazuh-packages/tree/3.7.1-add-ssl-option). The `wazuh-manager-3.7.1.spec` is ready and I'm already working in the DEB packages.

Regards.

**Comment by alberpilot** [comment]
Solved: #107.
