### ISSUE TITLE
Unknown group id ossec in solaris 11 4.3 package generation

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#1022]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.0 | Agent | Package generation | Solaris11 |

Hello team, when fixing the packages_builder_solaris pipeline in jenkins, I have encountered this error in the build process:

- https://ci.wazuh.info/job/Packages_builder_solaris/15337/

```
14:34:57      solaris11_cmake: chown: unknown group id ossec
14:34:57      solaris11_cmake: chown: unknown group id ossec
```

Specifically, the problem is in:

https://github.com/wazuh/wazuh-packages/blob/6b9b416e87a15cd16961ed1d725988a0293e25c4/solaris/solaris11/generate_wazuh_packages.sh#L175

https://github.com/wazuh/wazuh-packages/blob/6b9b416e87a15cd16961ed1d725988a0293e25c4/solaris/solaris11/generate_wazuh_packages.sh#L176

**Comment by DFolchA** [comment]
Hello,

This was a fix added in these PRs so the upgrade from versions lower than 4.2 could maintain the files in logs/ossec:

https://github.com/wazuh/wazuh-packages/pull/743
https://github.com/wazuh/wazuh-packages/pull/637

**Comment by rauldpm** [comment]
I agree, but in a 4.3 installation the error message appears and it should not, it should limit or capture the output in case it is a direct installation of 4.3.0.

Also, when installing I have detected an error message, that seems to be related to the line:

https://github.com/wazuh/wazuh-packages/blob/6b9b416e87a15cd16961ed1d725988a0293e25c4/solaris/solaris11/generate_wazuh_packages.sh#L199:

![image](https://user-images.githubusercontent.com/14913942/143609315-b5580eb9-b06f-493f-ab48-49cdebdb972d.png)

**Comment by rauldpm** [comment]
Related https://github.com/wazuh/wazuh-packages/issues/287

**Comment by rauldpm** [comment]
### Udate report

- Investigated solaris11 build process
- Identified erros:
  - ossec group in 4.3 install
  - wrong path to wazuh-control
  - publisher removal error
  - can not unmount /wazuh
  
- Fixed path to wazuh-control. The call to uninstall.sh script had no parameters, it needed to pass the installation path
- Fixed the unmount error. The `zfs destroy rpoll/wazuh` delete the /wazuh folder. For consistency, it is unmounted before deleting
- Fixed the publisher error. Investigated publishers, It is not necessary to remove the publisher as it is removed during the process by destroying `rpool/wazuh` and the `/wazuh` folder
- Fixed the ossec group error adding a conditional that checks if the group exists in the system

- The local and jenkins build does not show such errors:
  - https://devel.ci.wazuh.info/view/Packages/job/Packages_builder_solaris/4637/
  - Test_install successful https://devel.ci.wazuh.info/view/Tests/job/Test_install/20600/

Errors related to jenkins build are not generated locally:

```
sudo /var/ossec/bin/wazuh-control stop",
sudo: PAM account management error: Permission denied",
sudo rm -r /var/ossec",
sudo: PAM account management error: Permission denied",
sudo rm -f /etc/init.d/wazuh-agent",
PAM account management error: Permission denied",
sudo userdel wazuh",
PAM account management error: Permission denied",
sudo groupdel wazuh",
sudo: PAM account management error: Permission denied",
```

This is due to security policy, it does not affect the generation of the package since this only stops the service and uninstall the package. This should be corrected but is not critical, as the vagrant machine where it is spawned is destroyed. This on a local machine has not been reproduced:

![sol1](https://user-images.githubusercontent.com/14913942/143930675-b2e405fb-28d2-4ae0-b00d-e36074a2d48f.png)

#### Testing upgrade manually from 4.2.5 to 4.3.0 using a 4.3.0 manager.

- Found strange behaviors:
  - Connecting a 4.2.5 agent to a 4.3.0 centos7 manager, the agent log show multiple attempts to disconnect and connect. In all these attempts this line has been seen:

`wazuh-modulesd:agent-upgrade: INFO: (8153): Module Agent Upgrade started.`

  - These attempts end at the 3rd or 4th iteration, with the agent connected and sending alerts

- When updating following the guide, the agent is updated, but when starting I find a CRITICAL error

```
wazuh-agentd: ERROR: Unable to open agent file. errno: 13
wazuh-agentd: CRITICAL: (1103): Could not open file 'queue/rids/001' due to [(13)-(Permission denied)].
```

**Comment by rauldpm** [comment]
### Update report

- `sudo: PAM account management error: Permission denied`   error is related to solaris11_cmake vagrant box. This box is provided with the Vagrantfile in the wazuh-packages repo. An user can use it, this must be fixed.

**Comment by rauldpm** [comment]
### Update report

- Manually running the postinstall.sh script fixes the permissions problem, but this script should run automatically when installing or upgrading the package.
- The direct installation (without previous version of the 4.3.0 package) runs the postintall.sh script, on the other hand, when it is an upgrade, this file is updated but not ran, which causes a permission problem in the rids files
