### ISSUE TITLE
The `restore-permission.sh` file persists after installation on Debian

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh-packages#1044]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.0-rc1 | Manager | Install | Debian |

Hi team,

Following research in wazuh/wazuh#11093, it has been observed that after installing a package `manager 4.3.0-rc1`, a new **`restore-permission.sh`** file has been created with a size of 4.7M.

Apparently it comes from changes made to #1005.

Is it necessary that after installation, the manager continues to keep this file? 
Is there any way to avoid it?

Regards,
Marcel

**Comment by c-bordon** [comment]
It is found that the line `cp $ {SCRIPTS_DIR} /restore-permissions.sh $ {DIR} /restore-permissions.sh `was added in line 222 of the file `debs/SPECS/4.3.0/wazuh-manager/debian/postinst`
