### ISSUE TITLE
.template.db must be removed by wazuh-db

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-packages#111]
Hi team,

the .deb package removes the `.template.db` file in the post-install but this file must be removed by `wazuh-db`. 

https://github.com/wazuh/wazuh-packages/blob/9a42c4119b97f2d29f9699cd0037c823c6629297/debs/SPECS/3.7.2/wazuh-manager/debian/postinst#L108

This behavior already appears in the RPM packages.

Regards,
Braulio.

**Comment by DFolchA** [comment]
Hello team,

Today I have fixed this by removing the lines that deleted the file from the specs file for RPM and from the posinst file for  Debian.
I have tested it on centos7.
This has been committed to https://github.com/wazuh/wazuh-packages/tree/remove-.template.db.

Regards,
Daniel Folch
