### ISSUE TITLE
Wazuh-agent FreeBSD port

### ISSUE THREAD

**Issue by juliocbc** [wazuh/wazuh-packages#112]
## Feature request
FreeBSD agent port

**Compatibility**
FreeBSD

Description
--------------
Build an official port to FreeBSD ports collection, like ossec-agent has.

**Comment by alberpilot** [comment]
Hello @juliocbc 

  Thanks a lot for your request, we highly appreciate your feedback. We will include it in our roadmap, we would like to support this OS with a port. As you probably know we support a large amount of OS in our packaging process so unfortunately, we can't now estimate an ETA but we have included in our plans.

Best regards,

**Comment by edgeman16** [comment]
I would also like this.

**Comment by juliocbc** [comment]
Michael Muenz did it! Thanks Michael!

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=237900

**Comment by edgeman16** [comment]
Nice! I think it lacks an init script though :(

**Comment by DigitalFriends** [comment]
I would love this

**Comment by andredebuisne** [comment]
Would love this as well!

**Comment by b4b857f6ee** [comment]
We would love to have this <3
