### ISSUE TITLE
Unattended_installation (All in one) script not working (upgrade apache-log4j)

### ISSUE THREAD

**Issue by pamioc** [wazuh/wazuh-packages#1127]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.2.5 | Manager | Install | Debian v11.2 |

Hi Wazuh Team,
While executing unattended_installation script I have an issue on extracting package apache-log4j.
apache-log4j was upgraded to 2.17.1 yesterday.
https://dlcdn.apache.org/logging/log4j/

Thanks

**Comment by DFolchA** [comment]
Hello, 

Thank you for informing about this issue, we fixed it in this PR:
https://github.com/wazuh/wazuh-packages/pull/1128
