### ISSUE TITLE
Anyone got it running on Synology or an unifi cloud key?

### ISSUE THREAD

**Issue by cybert79** [wazuh/wazuh-packages#114]
Anyone got it running on Synology or an unifi cloud key?

**Comment by alberpilot** [comment]
Hello @cybert79 

We don't have any record about it but don't hesitate to share your requirements and we will try to help. 

Best regards, 
Alberto R.

**Comment by alberpilot** [comment]
Hello @cybert79 

  We will be glad to help you if you consider contributing. Anyway, we will add this to our roadmap. 

Best regards,
