### ISSUE TITLE
a small mistake in debian postinst script

### ISSUE THREAD

**Issue by LubinLew** [wazuh/wazuh-packages#1148]
Hi,

[`/debs/SPECS/4.4.0/wazuh-agent/debian/postinst#L200`](https://github.com/wazuh/wazuh-packages/blob/d3d82ddb4e1cb8c4ebb60465db43519bbb98e4df/debs/SPECS/4.4.0/wazuh-agent/debian/postinst#L200)

```bash
echo "postinst called with unknown argument \`$1'" >22
```

should be `>2` not `>22`.

**Comment by DFolchA** [comment]
Hello,

Thank you for reporting this, we have fixed this on these PRs:
https://github.com/wazuh/wazuh-packages/pull/1149
https://github.com/wazuh/wazuh-packages/pull/1150

Regards.
