### ISSUE TITLE
File creation in /var/ossec/etc/shared/ could cause an Agent reboot

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#116]
New files created in `/var/ossec/etc/shared` could cause Wazuh agent reboots. Those new files could be created in upgrades by the RPM package. We need to determinate the best option in order to avoid reboots due to .new files created by the RPM package. 

Best regards,

**Comment by BraulioV** [comment]
Hi @alberpilot, 

This issue was solved in https://github.com/wazuh/wazuh-packages/pull/119 for Wazuh v3.9.0 and added in d63b3b51711a3ccdf4c8b9485f8fa758d20b02fd to Wazuh v3.8.1, so I will close the issue. 

Best regards :)
