### ISSUE TITLE
Windows agent interface doesn't show with 4.3.0 package install

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#1214]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.0 | Agent | Install | Windows Server 2016 |

Hello team,

Testing the windows agent package for 4.3.0, I have seen that when installing and selecting the option to launch the agent interface at the end of the installation, it does not appear, however, for version 4.2.5, it does. 

https://user-images.githubusercontent.com/14913942/151455518-e9d89c93-d266-4b82-8fd5-8fdd6f613c18.mp4

Regards, Raúl.

**Comment by alberpilot** [comment]
This problem was solved as shown in the Windows video here: https://github.com/wazuh/wazuh-packages/issues/633#issuecomment-981872656. The PR: https://github.com/wazuh/wazuh/pull/10978
