### ISSUE TITLE
Unattended installer breaks when the OS language is other than English

### ISSUE THREAD

**Issue by RamiroRD** [wazuh/wazuh-packages#1247]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.2.5 | - | Installed using unattended installer | Linux |

There are parts of the unattended installer script which use the output of some commands, such as `free` to get system data. The problem with doing this is that our parsing relies on the output of these commands being in English. 

We had some users from the community report having trouble running the unattended installers because of this problem.

**Comment by teddytpc1** [comment]
This will be addressed [here](https://github.com/wazuh/wazuh-automation/issues/1485).
