### ISSUE TITLE
Unattended script: Remove code reference' s to Suse.

### ISSUE THREAD

**Issue by nikoslastra** [wazuh/wazuh-packages#1257]
Work on the following branch:

- https://github.com/wazuh/wazuh-packages/tree/unify-unattended

Remove parts of the unattended installer code that reference Suse.

**Comment by rauldpm** [comment]
We must remove the references to zypper from the installation assistant since the opensuse and suse systems are not referenced as recommended in the documentation and we do not apply tests on these systems

- https://documentation.wazuh.com/current/quickstart.html#operating-system
