### ISSUE TITLE
Change the Unattended installer 9700 and 9800 port references to 9200 and 9300.

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1287]
As mentioned in https://github.com/wazuh/wazuh-packages/issues/1285, the Wazuh indexer must use the same default ports as elasticsearch.
We need to change all the `unify-unattended` branch 9700 & 9800 port references, changing them accordingly to 9200 for API requests and 9300 for the transport layer.

**Comment by lastranikos** [comment]
I am working on the branch: https://github.com/wazuh/wazuh-packages/tree/1287-indexer-change-port-references
