### ISSUE TITLE
.spec files for Wazuh 3.x

### ISSUE THREAD

**Issue by valorcz** [wazuh/wazuh-packages#13]
Dear Wazuh team,

I am trying to find .spec files for the latest Wazuh versions (3.x) and no success so far. I wanted to ask whether this repo will be get in sync with Wazuh upstream, or is there any other repository I should look into?

Thank you,
Vaclav

**Comment by jlruizmlg** [comment]
Hi @valorcz , you are right, we need to update this repository with the last specs/deb files to keep sync with the latest releases.

Thanks for the feedback.

**Comment by BraulioV** [comment]
Hi @valorcz,

now you can find in the repository all the _.spec_ files for the latest Wazuh versions and also all the files needed to build .deb packages, divided into different branches depending on the Wazuh version.

Best regards,
Braulio.
