### ISSUE TITLE
New password_file.yml format needed with unattended installer

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1301]
The `password_file.yml` new format must be:
```
# Wazuh indexer admin user
  username: admin
  password: S9YKUya2s4N4WPiTB1kN6ynOcq7CB2QR

# Wazuh dashboard user for establishing the connection with Wazuh indexer
  username: kibanaserver
  password: NiwXQw82pIf0dToiwczduLBnUPEvg7T0
```
This format includes an empty line to separate sections. It removes the word User (uses username instead of name). It adds a space after the `#`. It has also rephrased the explanation of the user (please rephrase other users when needed to make it easier to understand).

**Comment by rauldpm** [comment]
### Update report

- Localized and modified files
- Testing regex to check file
- Modified extension file (yml to wazuh)
- Investigating if it is worth parsing the grep to report where the error is

**Comment by rauldpm** [comment]
### Update report

- Finished local testing. Opened PR with testing
- Testing install and unit tests
- Adapted install test, working locally
- Adapting unit tests, multiples test fails

**Comment by rauldpm** [comment]
### Update report

- Unit test are on hold due to new requirements
- Tested change with jenkins pipelines
- Created PR
- Fixed conflicts with latest unify-unattended changes (merge)
- Fixed commit unsigned
