### ISSUE TITLE
Wazuh package install duplicated service

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh-packages#132]
Hi team,

When installing Wazuh in a system with Systemd, it installs the service at both **/etc/init.d** and **/etc/systemd/system**

Best regards,
Miguel

**Comment by alguacilaguamara** [comment]
Hello team,

To change this case, I have to modify the following lines of code:

https://github.com/wazuh/wazuh-packages/blob/dfdf27c9aefe7c4c621793dbe83fa1cd89ae96c4/debs/SPECS/3.9.5/wazuh-agent/debian/postinst#L145-L151

To solve this, I am going to make the system installation of init.d independent.

Best regards,
Alejandro

**Comment by alguacilaguamara** [comment]
Hello team,

I can't put the postint changes for Wazuh version 3.9.5, but in 3.10 and 3.11. 

To force the differences, in the systems that have init.d will be called to this, while if you have systemd only one service will be created with this system.

Best regards,
Alejandro

**Comment by BraulioV** [comment]
Hi all,

For the release of Wazuh 4.x we have been researching several ways to avoid this issue, but finally, we've decided to install both services always. These are the main reasons:
- The same package will work in any of the supported OS.
- Pre/post-install scripts are easier to maintain.
- The installer will know what files are installed by it. If you install files using the post-install script, it may cause issues.

Finally, we're working in this branch: [4.0-fix-services-logic](https://github.com/wazuh/wazuh-packages/tree/4.0-fix-services-logic) to improve all the logic related to the services, improving the codebase of installation scripts, etc.

I'm closing this issue, but if you have any comments or requests, feel free to reopen it.

Regards.
