### ISSUE TITLE
Remove log config from Dashboard configuration yml

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-packages#1321]
Remove the logging.dest property from the Dashboard configuration file:

https://github.com/wazuh/wazuh-packages/blob/6abdfaac6c56d3edfe5e4b1d4ede7a3b245f887b/stack/dashboard/base/files/etc/opensearch_dashboards.yml#L14

We do this because Kibana does not rotate the logs and causes this file to grow

**Comment by c-bordon** [comment]
References to the custom log file and directory are removed.

@alberpilot  The wazuh-dashboard logs will remain in the strout only, right?

**Comment by alberpilot** [comment]
It must be as openseach default behavior.
