### ISSUE TITLE
Sca folder renaming for suse

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#133]
Hello team

 Due to changes https://github.com/wazuh/wazuh/pull/2697 we need to adapt the RPM specs. The affected folder needs to be modified. 

Best regards,

**Comment by BraulioV** [comment]
Hi @alberpilot,

I'm closing this issue because it was fixed in this PR https://github.com/wazuh/wazuh-packages/pull/134.

Regards.
