### ISSUE TITLE
Issue with the unattended cert-tools

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-packages#1340]
There is an issue in the cert-tools process for creating the admin.pem certificate, this fails if the CA does not previously exist, so the process of creating these certificates has to validate the existence of the CA and in the case that there is no call to the function: `cert_generateRootCAcertificate`

**Comment by alberpilot** [comment]
After checking the tool, the are some points that we consider necessary to fix and change:
- When using option `-a,  --admin-certificates`, the tool must ask the user a root CA. If not provided, the tool must tell the user to create all certificates from a `config.yml` file provided. 
- Same for `-wd,  --wazuh-dashboard-certificates`, `-wi,  --wazuh-indexer-certificates`, `-ws,  --wazuh-server-certificates`. 
- The script must avoid creating `cert` folder if only using the help option.
