### ISSUE TITLE
Wazuh installer assistant fails if other process is using APT

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1388]
We noticed that, if a process is using `apt` installing or upgrading other packages, the Wazuh installer assistant fails as follow:
```
24/03/2022 14:49:47 INFO: --- Wazuh server ---
24/03/2022 14:49:47 INFO: Starting the Wazuh manager installation.
24/03/2022 14:49:48 ERROR: Wazuh installation failed
24/03/2022 14:49:48 INFO: --- Removing existing Wazuh installation ---
```
More detailed: 
```
24/03/2022 14:49:47 INFO: Starting the Wazuh manager installation.
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 5654 (unattended-upgr)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
```
When you try to use `apt-get install` when another process is using it, it throws an error message (code 100). So the installation fails and cleans the system. 

This is not an issue in RPM systems. 

Solution: try to install until unlocked with a timeout.

**Comment by DFolchA** [comment]
# Update
**working branch** https://github.com/wazuh/wazuh-packages/tree/1388-apt-lock-fail

Added loop to wait for the lock and fail if it takes too long.

**Comment by c-bordon** [comment]
# Update

https://github.com/wazuh/wazuh-packages/pull/1401#discussion_r837863875
I will continue working on the validation of the apt lock error so as not to cause unnecessary delays
