### ISSUE TITLE
The Wazuh installation assistant must be able to process CRLF `config.yml` files

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1410]
The installation assistant shows an error when a `config.yml` file is used with CRLF. We should take it and transform it into LF.

**Comment by alberpilot** [comment]
@fcaffieri Please continue in this issue https://github.com/wazuh/wazuh-packages/issues/1421 and close this one.

**Comment by fcaffieri** [comment]
This issue is closed, continue on https://github.com/wazuh/wazuh-packages/issues/1421
