### ISSUE TITLE
The Wazuh installation assistance must check if indexer is listening just before `indexer-security-init.sh` run

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1411]
After several tests, we noticed that users can install their indexer nodes and, for connectivity reasons, the nodes don't go into the bootstrap stage. An `indexer-security-init.sh` without a started cluster (appointed master node) trigger a high wait stage with final errors. 

We need to determine, just before `indexer-security-init.sh` call, if the nodes are listening and cluster ready. For that, we need to check if they are listening. A connection test using the 9300 port to all nodes must be enough.

## Tasks
- [ ] Investigate what tool suits better with the 9300 TCP port check through an IP. I.e: `nc`, `nmap`, `telnet`, `curl`, etc. 
- [ ] Imprement a check, launched just before the wrapper, for determine if elasticsearch is listening using 9300 port.

**Comment by c-bordon** [comment]
Tests are carried out with different tools and I consider that nc helps us to monitor if indexer is listening on port 9300 through the status code of the command:

`nc -z localhost 9300`

I am doing some tests with a validation of the nc status code, although I still could not replicate the error, I will continue validating until I am sure that the new code corrects the error:

Centos: https://devel.ci.wazuh.info/view/Tests/job/Test_unattended/511/console
Ubuntu: https://devel.ci.wazuh.info/view/Tests/job/Test_unattended/512/console
Distributed: https://devel.ci.wazuh.info/view/Tests/job/Test_unattended_distributed/398/console
