### ISSUE TITLE
Change unhandled promises level in wazuh-dashboard and kibana node.options file

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-packages#1429]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3 | Manager| Update | - |

Recent versions of Opensearch-dashboards and ELK changed the default behavior regarding unhandled promises. Current version treat them as fatal errors, while prior version treat them as warning.

While resolving issues of unhandled promises is very important, we cannot change the default behavior yet.

Thus, we need to add the option ```-unhandled-rejections=warn``` to the ```node.options``` file we distribute. 

Also, we need to update our other artifacts and documentation to reflect this change, telling our users they need to use this option to work with our application.

Todo:
- [x] Wazuh dashboard
- [x] Elastic Stack

**Comment by rauldpm** [comment]
### Update report

- After investigating demo environment, it has been found that the parameter is `--unhandled-rejections=warn` and not  `-unhandled-rejections=warn`

**Comment by rauldpm** [comment]
### Update report

- The kibana 7.17.0 installation already contains this change, reviewing the elastic/kibana repository, it is observed that from the v7.16.0 tag, the node.options file contains this modification

https://github.com/elastic/kibana/blob/v7.17.0/config/node.options
