### ISSUE TITLE
Automatic agent deployment in MacOS

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#143]
Regarding the issue https://github.com/wazuh/wazuh-packages/issues/135 we need to replicate the behavior in MacOS packages. 

Best regards,

**Comment by ChusMoyano** [comment]
Hello team, 

In this issue, we tried to install and auto-register an agent on the OSX system. 

1. The first thing that we thought was to pass variables in-line like in Linux, follow that syntax: `VAR_0=XXX VAR_1=YYY VAR_2=ZZZ  dpkg -i (name of package)`, but OSX seems like doesn´t access to defined variables on pre-install or post-install scripts.

2. Second, we tried export variables to our environment, with ` export VAR=YYY `and try to access at the post-install script but it didn´t work either.

We still researching about this issue.

Best Regards
Jesús.

**Comment by BraulioV** [comment]
Hi @alberpilot and @ChusMoyano,

I've been doing some research about this issue on MacOS X. The problems that @ChusMoyano faced in the previous comment are the same ones that I faced in this PR https://github.com/wazuh/wazuh/pull/2605 when adding support for wazuh-manager in MacOS hosts, where exported variables can't be read by "child process".

In this case, I found a solution to this issue by exporting the env variables using `launchctl`. If you create an env variable with `launchtl setenv var_name var_value`, you can read the value of `var_name` executing this line: `launchctl getenv var_name`. Here you can see an example:

```shellsession
sh-3.2# launchctl setenv WAZUH_MANAGER "1.1.1.1" WAZUH_AUTH "1.1.1.2"
sh-3.2# launchctl getenv WAZUH_MANAGER
1.1.1.1
sh-3.2# launchctl getenv WAZUH_AUTH
1.1.1.2
```
In this commit: https://github.com/wazuh/wazuh/commit/b54ce996f5ab26dcf7b9c14fd95c56b8e1c1afbd I added the necessary changes to run the `register_configure_agent.sh` script in MacOS hosts. These changes consist on checking if the script is ran in MacOS and if that's true, read the variable names with `launchctl getenv` and export the variable in the local namespace of the script.

I will test the solution and create a PR to add this enhacement into `auto-register-and-connection` from wazuh/wazuh.

Regards.

**Comment by BraulioV** [comment]
Hi team,

I'm closing this issue because it was resolved in https://github.com/wazuh/wazuh/pull/3085.

Regards.
