### ISSUE TITLE
RPM Manager package throw duplicate id of vuln detector rule

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-packages#146]
Hi team,

We have detected that 3.9.0 manager package throws the error:
```
ossec-testrule: ERROR: Duplicate rule ID:23501
ossec-testrule: CRITICAL: (1220): Error loading the rules: 'ruleset/rules/0520-vulnerability-detector_rules.xml'.
``` 

When we upgrade from any previous version to 3.9.0-3911, It seems that on some little moment the previous 0520 rule is on same place at same time that new rule, we attach this logs
[upgrade381_382.txt](https://github.com/wazuh/wazuh-packages/files/3028891/upgrade381_382.txt)
[upgrade382_390.txt](https://github.com/wazuh/wazuh-packages/files/3028892/upgrade382_390.txt)

Regards!.

**Comment by BraulioV** [comment]
Hi @okynos,

in the commit 73c47a2 I've added a first implementation that solves this issue. First, I will explain why this problem appears, why it doesn't appear in _.deb_ packages and in _.rpm_ yes and the proposed solution:
- Cause: In this PR https://github.com/wazuh/wazuh-ruleset/pull/325 the file `rules/0520-vulnerability-detector.xml` was renamed as `rules/0520-vulnerability-detector_rules.xml` and the file `rules/0565-ms_ipsec_rules_json.xml` is also rename as `rules/0565-ms_ipsec_rules_json.xml`. This will create duplicate IDs errors while upgrading the manager.
- Why this error only appears in _.rpm_ packages: _.rpm_ and _.deb_ packages behave a bit different when a package is upgraded. .deb packages delete the files from previous version **before** running the `postinst` script. 
![image](https://user-images.githubusercontent.com/9081114/55516882-eaf7a400-566e-11e9-8ee2-df4afe6f630c.png) This is why the error doesn't appear in .deb packages, the files from previous versions are deleted before restarting the manager.
_.rpm_ packages delete the files from the previous version after finishing the execution of `postinstall` and `triggerin` scripts. This means that when the package is going to restart the manager, you can find this in `ruleset/rules`:
    ```shellsession
    [root@centos7 wazuh-ruleset]# ls -l /var/ossec/ruleset/rules/ | grep 0565
    -rw-r-----. 1 root ossec   9505 Apr  3 22:06 0565-ms_ipsec_rules_json.xml
    -rw-r--r--. 1 root root    4162 Apr  3 22:07 0565-ms_ipsec_rules.xml
    [root@centos7 wazuh-ruleset]# ls -l /var/ossec/ruleset/rules/ | grep 0520
    -rw-r--r--. 1 root root    2898 Apr  3 22:07 0520-vulnerability-detector_rules.xml
    -rw-r-----. 1 root ossec   2923 Apr  3 22:06 0520-vulnerability-detector.xml
    ```
    Duplicated rules, duplicated IDs and the error.
- Proposed solution: rename the broken files as `.old` files, restart the manager and restore those files. This will allow us to restart the manager, keep in the memory of `ossec-analysisd` the updated ruleset and allow rpm process to properly delete the files from the previous version.

Regards.

**Comment by nodesocket** [comment]
I am running into this issue:

> 2019/09/06 23:38:37 ossec-testrule: ERROR: Duplicate rule ID:23501
2019/09/06 23:38:37 ossec-testrule: CRITICAL: (1220): Error loading the rules: 'ruleset/rules/0520-vulnerability-detector_rules.xml'.

What is the fix?

**Comment by BraulioV** [comment]
Hi @nodesocket,

Sorry for the late response. Can you provide us more info about your environment?
- Manager version before upgrade.
- The current version of the manager.
- Have you manually update the ruleset using `/var/ossec/bin/update_ruleset`? If so, can you send us the command that you used?
- Are you using .deb or .rpm packages?

**Comment by nodesocket** [comment]
@BraulioV actually the issue seemed to be related to using this repo https://github.com/davinerd/wazuh_terraform which just seems to be out of date. Doing a manual install of the agent, api, and Elasticsearch + Beat + Kibana worked great. Closing this issue.
