### ISSUE TITLE
Language-Bug in unattended-installation.sh

### ISSUE THREAD

**Issue by ricokritzer** [wazuh/wazuh-packages#1501]
There is a little bug in the installation script of "unattended-installation.sh".

If system language is not English, awk in line 331 does not receive empty memory space. Resolution will be "" instead.

Wrong Code:
`$(free -g | awk '/^Mem:/{print $2}')`

In German e. g. following code works fine:
`$(free -g | awk '/^Speicher:/{print $2}')`

**Comment by jnasselle** [comment]
Me again @ricokritzer,

Providing some widely-supported fix (and test it across multiple GNU/Linux distros) for this issue might take some time, but in the meantime, the next change might solve your problem:
```diff
-        ram_gb=$(free -g | awk '/^Mem:/{print $2}')
+        ram_gb=$(free -g | awk 'FNR == 2 {print $2}')
```
Please let me know if this was helpful

**Comment by ricokritzer** [comment]
This quick-fix works fine, thanks!

**Comment by jnasselle** [comment]
You are welcome @ricokritzer! Happy to be helpful!
I will close this issue in favor of preexistent https://github.com/wazuh/wazuh-packages/issues/1247.

Regards,
Nico
