### ISSUE TITLE
OVA changes are required

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1502]
For the next OVA building we need the following changes:
- [x] OVA logo welcome message has the URL `www.wazuh.com`. Replace it with `https://wazuh.com/`. 
- [ ] The user for OVA should be `admin` instead of `wazuh-user`. The password should be `admin. The root user password should be `admin`. The WUI user and password should be `admin`. 
- [ ] The user change described before should have a documentation change request too. 
- [x] The welcome message `Use wazuh-user for username and wazuh for password to login` should be replaced by:
```
Login credentials:
User: wazuh-user
Password: wazuh
```
- [x] The automatic set ram script should be modified to take into account the unattended `jvm.options` modification. It should replace whatever has the variable Xms and Xmx.

**Comment by rauldpm** [comment]
> The automatic set ram script should be modified to take into account the unattended jvm.options modification. It should replace whatever has the variable Xms and Xmx.

Added in https://github.com/wazuh/wazuh-packages/pull/1510/

**Comment by rauldpm** [comment]
> OVA logo welcome message has the URL www.wazuh.com. Replace it with https://wazuh.com/

Added in https://github.com/wazuh/wazuh-packages/pull/1514

**Comment by teddytpc1** [comment]
We will keep the `wazuh-user`.
