### ISSUE TITLE
Unattended must change API default password by default

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1523]
Currently, the Wazuh installation assistant doesn't change the Wazuh API password by default and it must be implemented.

**Comment by miguelfdez99** [comment]
We want to be able to change the API password of certain users using the password tool, so a new functionality is going to be added to the password tool. This change will not only change the default API password when performing the unattended installation, but will allow us to change the password whenever we want.

I have added the options --api , --id-api, --admin-user and --admin-password
````
    echo -e "        -ai,  --api <currentPassword>"
    echo -e "                Change the Wazuh API password given the current password, it needs --id-api ,--user and --password."
    echo -e "                If not an administrator --admin-user and --admin-password need to be provided."
    echo -e ""
    echo -e "        -au,  --admin-user <adminUser>"
    echo -e "                Admin user for Wazuh API it is needed when the user given it is not an administrator"
    echo -e ""
    echo -e "        -ap,  --admin-password <adminPassword>"
    echo -e "                Password for Wazuh API admin user, it is needed when the user given it is not an administrator"
    echo -e ""
    echo -e "        -id,  --id-api <id>"
    echo -e "                ID for Wazuh API user to be changed"
````
To change the API password we need the current password, the id of the user we want to change, the user and the new password. For the user and the new password we have to include the --user <user> and --password <password> flags.
The admin flag is needed when the user we are going to change his password is not an administrator, so it is necessary to provide the credentials of an administrator.

Example of use:

````
[root@ip-172-31-3-174 ec2-user]# ./wazuh-passwords-tool.sh -A '1wA?djhbuwibdialjda2' -id 100  -u usuario -p '1wA+kdjhbuwibdialjda2' -au wazuh -ap 'wu1PSTkWcndjARCSa7cLlWWK9[BxTg8'
````
Result:

````
24/05/2022 09:27:39 INFO: 
The new password for user usuario is 1wA+kdjhbuwibdialjda2
````

**Comment by gdiazlo** [comment]
The issue https://github.com/wazuh/wazuh-packages/issues/1634 could be related to this effort.

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-packages/pull/1548/files
