### ISSUE TITLE
Wazuh agent RPM package generation needs to be adapted for i386 compilation

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#154]
Hello team
 
  Due to this modification: https://github.com/wazuh/wazuh/pull/3151 we need to modify the RPM Spec in order to include the new previous PR defined flag. This new flag for compilation has to be taken into account in this part of the 3.9 Spec and use it only after an i386 architecture detection.

Best regards, 
Alberto R.

**Comment by DFolchA** [comment]
Hello team,

I have been working on this issue, to solve this I made some changes to wazuh-agent-3.9.0.spec for the 3.9.0 version, using `%ifnarch x86_64` to check the architecture and then setting the flag  USE_MSGPACK_OPT to its correct value.
 https://github.com/wazuh/wazuh-packages/blob/b9aa73e4a761062fb17ed92f93c8e532b2d8d344/rpms/SPECS/3.9.0/wazuh-agent-3.9.0.spec#L53-L65

Regards,
Daniel Folch
