### ISSUE TITLE
Update filebeat module for 4.x installations

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-packages#1563]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.0 - 4.3.1 | Manager | Install/Upgrade | GNU/Linux |

Related issue: https://github.com/wazuh/wazuh/issues/13415

## Description
Currently, filebeat module delivered via https://packages.wazuh.com/4.x/filebeat/wazuh-filebeat-0.1.tar.gz is not updated with the expected content located here https://github.com/wazuh/wazuh/tree/v4.3.0/extensions/filebeat/7.x/wazuh-module.

This is causing that office365 data ingestion could not translate IP addresses to geolocations (PR [here](https://github.com/wazuh/wazuh/pull/9139))

**Comment by DFolchA** [comment]
## Update report

Build filebeat module with latest changes, and update generation script:
https://github.com/wazuh/wazuh-packages/blob/filebeat-module/filebeat/build-wazuh-module.sh

Improvements:
- Install mage
- Use git to get beats repository

Test new module.

**Comment by DFolchA** [comment]
Update
- Work in improved script for Wazuh packages using docker

**Comment by c-bordon** [comment]
## UpdateReport

### Tasks
- A new Dockerfile was created with the necessary for the construction of the Filebeat module and 2 scripts were created for this creation, the `build.sh` which is responsible for the creation of the module itself, and the `build-filebeat-module.sh` which facilitates the use of the first script for any user who wants to create it from this repository.
- We started from this script for the creation of the new ones: https://github.com/wazuh/wazuh-packages/blob/filebeat-module/filebeat/build-wazuh-module.sh

**Comment by c-bordon** [comment]
## UpdateReport

### Tasks
- Some changes were made to the scripts mentioned above to generate a file according to the version of Wazuh from where it is built, thus changing the way in which this module is delivered to production.
With this change, now for each version of Wazuh, we must have a version of this module (This is to be confirmed).
- The packages_builder and packages_builder_tier pipelines are modified to contemplate the construction of this module:
https://ci.wazuh.info/view/Packages/job/Packages_builder_tier_cbordon/6/console
https://ci.wazuh.info/job/Packages_builder_cbordon/11/console
- I am working on the necessary changes to the publish_release and the check_release
