### ISSUE TITLE
Remove unnecessary plugins from default Wazuh dashboard. 

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1564]
The Wazuh dashboard **should not have** the following plugins by default:

- Query workbench
- Anomaly detection
- Observability

In order to avoid cascade changes in several repositories, preparing the base with this change will help to get prepared the assets before being used to installers, containers, etc. 
The following commands can be run in the base preparation stage:
```
opensearch-dashboards-plugin remove queryWorkbenchDashboards
Removing queryWorkbenchDashboards...
Plugin removal complete
```
```
opensearch-dashboards-plugin remove anomalyDetectionDashboards                        
Removing anomalyDetectionDashboards...
Plugin removal complete
```
 ```
opensearch-dashboards-plugin remove observabilityDashboards    
Removing observabilityDashboards...
Plugin removal complete
```

## Tasks
- [x] Modify the Wazuh dashboard base building tool. 
- [ ] Modify the `checkfiles` for Jenkins install/upgrade tests.

**Comment by c-bordon** [comment]
The changes are made in the base and packages are assembled with the changes in the trash repository, and some tests are executed to validate the changes in the checkfiles.

RPM: https://packages-dev.wazuh.com/trash/yum/wazuh-dashboard-4.3.2-1.x86_64.rpm
DEB: https://packages-dev.wazuh.com/trash/apt/pool/main/w/wazuh-dashboard/wazuh-dashboard_4.3.2-1_amd64.deb
