### ISSUE TITLE
Missing SCA policy file in Mac OS X package

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-packages#159]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0-rc8 | Agent | Packages | Mac OS X |

Hi team,

When installing the wazuh agent package in mac OS should contain the policies [system_audit_rcl_mac.yml](https://github.com/wazuh/wazuh/blob/3.9/etc/sca/darwin/system_audit_rcl_mac.yml) and [system_audit_ssh.yml](https://github.com/wazuh/wazuh/blob/3.9/etc/sca/generic/system_audit_ssh.yml) as it is defined at the mac os template (https://github.com/wazuh/wazuh/blob/3.9/etc/templates/config/darwin/sca.files).

However, it includes the generic policies for Linux:

```
ll /Library/Ossec/ruleset/sca/
total 56
drwxr-x---  5 root  ossec   160B 26 abr 13:26 .
drwxr-x---  3 root  ossec    96B 26 abr 04:49 ..
-rw-r-----  1 root  ossec    11K 26 abr 04:49 system_audit_pw.yml
-rw-r-----  1 root  ossec   4,1K 26 abr 04:49 system_audit_rcl.yml
-rw-r-----  1 root  ossec   5,5K 26 abr 04:49 system_audit_ssh.yml
```

The configuration template is being installed correctly:

```
<sca>
    <enabled>yes</enabled>
    <scan_on_start>yes</scan_on_start>
    <interval>12h</interval>
    <skip_nfs>yes</skip_nfs>

    <policies>
      <policy>system_audit_rcl_mac.yml</policy>
      <policy>system_audit_ssh.yml</policy>
    </policies>
</sca>
```

But when running the scan, the `system_audit_rcl_mac.yml` policy is missing, and `system_audit_pw.yml` is contained in the package but is compatible with Linux agents only.

```
2019/04/26 13:55:07 sca: INFO: Starting Security Configuration Assessment scan.
2019/04/26 13:55:07 sca: WARNING: Policy file not found: '/Library/Ossec/ruleset/sca/system_audit_rcl_mac.yml'. Skipping it.
```

Regards.

**Comment by alberpilot** [comment]
Done. Thanks, @chemamartinez for reporting.
