### ISSUE TITLE
Dashboard package updates for 4.3.4

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-packages#1620]
The following updates need to be applied for Wazuh dashboard 4.3.4 package

- [x] Include the changes mentioned in this issue: https://github.com/wazuh/wazuh-packages/issues/1564
- [x] Include the changes mentioned in this issue: https://github.com/wazuh/wazuh-packages/issues/1576
- [x] Investigate possible issue in the demo environment with the favicon
![Screenshot_20220606_080226](https://user-images.githubusercontent.com/64099752/172148858-8feea79f-6c22-4714-b78d-6360833d822c.png)

**Comment by alberpilot** [comment]
The welcome screen logo should be a little bit bigger and the bottom text wide should be the same as the log.

**Comment by c-bordon** [comment]
Updates are made, but I found a problem with the new logo in firefox:

### Chrome:
![Screenshot_20220607_091502](https://user-images.githubusercontent.com/64099752/172465283-03100777-c14b-4366-912e-8c4c22a5fd5a.png)
![Screenshot_20220607_091523](https://user-images.githubusercontent.com/64099752/172465304-c57dccf8-b657-4722-8453-d66920c4c329.png)
![Screenshot_20220607_091533](https://user-images.githubusercontent.com/64099752/172465317-d65337be-cd7a-44bd-b929-92f35712c172.png)


### Firefox:
![Screenshot_20220607_102139](https://user-images.githubusercontent.com/64099752/172465369-c7ec00d7-e3cb-487e-af47-61ef5b1d31c8.png)


I've been researching but still can't find a solution:
https://stackoverflow.com/questions/38169475/svg-in-html5-when-is-xml-declaration-xml-version-1-0-encoding-utf-8
https://stackoverflow.com/questions/39330512/svg-doesnt-display-on-firefox-but-in-chrome-and-edge-works-fine
https://stackoverflow.com/questions/69711967/why-are-my-svgs-showing-properly-in-chrome-but-not-firefox
https://stackoverflow.com/questions/29467891/svg-working-in-chrome-but-not-in-firefox
https://developer.mozilla.org/en-US/docs/Web/SVG/SVG_as_an_Image
https://superuser.com/questions/324902/svg-not-displaying-completely-in-chrome-firefox

![Screenshot_20220607_162604](https://user-images.githubusercontent.com/64099752/172465634-b6d0e8fa-2065-4f7c-a635-1cfdfb894bfc.png)
![Screenshot_20220607_162622](https://user-images.githubusercontent.com/64099752/172465675-896d5884-c50a-4660-bb7b-8b67e30a2a22.png)
![Screenshot_20220607_162640](https://user-images.githubusercontent.com/64099752/172465723-a9ee1452-25cb-40c6-827f-92b789da5252.png)

**Comment by c-bordon** [comment]
thanks @Desvelao for you help.

The PR is merged
