### ISSUE TITLE
Installers should log the activity into a file

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1632]
The installers can't prevent situations with wrong OS permissions files, (like wrong permissions with `/etc/passwd`), errors with `adduser`, etc. The installer should log into a file the executed steps in order to easily identify possible problems.

**Comment by davidcr01** [comment]
# Update Report

> Related: https://github.com/wazuh/wazuh-packages/issues/2363. Useful to consider the complex commands.

Is necessary to check the commands of the following files and add the `${debug}` variable to the necessary commands:

- [ ] certFunctions.sh  
- [ ] certMain.sh  
- [ ] certVariables.sh
- [ ] common.sh 
- [ ] commonVariables.sh
- [ ] checks.sh     
- [ ] indexer.sh        
- [ ] installVariables.sh
- [ ] dashboard.sh  
- [ ] installCommon.sh  
- [ ] manager.sh
- [ ] filebeat.sh   
- [ ] installMain.sh    
- [ ] wazuh-offline-download.sh
- [ ] passwordsFunctions.sh  
- [ ] passwordsMain.sh  
- [ ] passwordsVariables.sh

**Comment by davidcr01** [comment]
# Update Report

As the main objective of this issue is to add more information to the logfile in order to easily identify possible problems, I think that adding more debug messages in the execution of the code can be a good idea. These messages can be useful as "checkpoints" of the code.

**Comment by davidcr01** [comment]
# Update Report

To ensure that there are no breaking changes, it is necessary to perform the following tests:


<details><summary>:green_circle: AIO installation</summary>

```console
```
</details>


<details><summary>:green_circle: AIO installation with verbose</summary>

```console
```
</details>


<details><summary>:green_circle: Uninstall</summary>

```console
```
</details>


<details><summary>:green_circle: Uninstall with verbose</summary>

```console
```
</details>

<details><summary>:green_circle: Step-by-step installation</summary>

```console
```
</details>

<details><summary>:green_circle: Step-by-step installation with verbose</summary>

```console
```
</details>

<details><summary>:green_circle: Offline installation</summary>

```console
```
</details>

<details><summary>:green_circle: Offline installation with verbose</summary>

```console
```
</details>
