### ISSUE TITLE
Adapt packages install to use the cert creation tool

### ISSUE THREAD

**Issue by antoniomanuelfr** [wazuh/wazuh-packages#1676]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
|4.5| Manager| Install/Upgrade/Remove | OS version |

Hello team!

In this issue https://github.com/wazuh/wazuh/issues/11295, the team is developing a new option for `wazuh-authd` to be able to generate the needed certificates using the already downloaded OpenSSL library instead of having OpenSSL as a dependency.

In order to generate the manager certificates, the following parameters must be added to the CLI:
- `-C` Specify the certificate validity in days.
- `-B` Specify the certificate key size in bits.
- `-K` Specify the path to store the certificate key.
- `-X` Specify the path to store the certificate.
- `-S` Specify the certificate subject.

```
wazuh-authd -C 265 -B 2048 -K /var/ossec/etc/sslmanager.key -X /var/ossec/etc/sslmanager.cert -S "/C=US/ST=California/CN=wazuh/"
```

**Comment by rauldpm** [comment]
This issue cannot be closed until @wazuh/qa completes their testing and the PR https://github.com/wazuh/wazuh/tree/11295-add-openssl-cert-tool is merged into the wazuh repository.

The working branch of this issue with the changes is: `1676-adapt-cert-creation-tool`

A revert of the introduced changes has been made so as not to stop the development of other issues. https://github.com/wazuh/wazuh-packages/pull/1830
