### ISSUE TITLE
Disable TLS versions lower than v1.2

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-packages#1694]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.X | - | -  | - |

### Description 

We need to consider whether it makes sense to disable old TLS versions from our default configurations. I would argue it makes sense to upgrade it to the latest version possible, while disabling all the other old options. If a browser or API client does not support the required TLS, they must upgrade.

Given the [attacks against TLS 1.2](https://raccoon-attack.com/) we should push to adopt version 1.3 asap, even if this attack is not very practical today.

References:

* [OWASP top 10](https://owasp.org/Top10/A00_2021_Introduction/)
* [Cloudflare argues TLS 1.3](https://www.cloudflare.com/learning/ssl/why-use-tls-1.3/)
* [Racoon attack](https://raccoon-attack.com/)

### Settings

Our settings could use some parameters [documented here](https://opensearch.org/docs/latest/security-plugin/configuration/tls/#advanced-enabled-ciphers-and-protocols) to disable weak ciphers and protocols, for example:

```
plugins.security.ssl.http.enabled_ciphers:
  - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
  - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
plugins.security.ssl.http.enabled_protocols:
  - "TLSv1.2"
  - "TLSv1.3"
```

This configuration can potentially affect old clients like:
- Android  4.3 and older
- Internet Explorer 10 and older
- Safari 6.0.4 and older

`opensearch-dashboards` does not support TLSv1.3 yet as per 

 - https://github.com/opensearch-project/OpenSearch-Dashboards/issues/838

We can set up TLSv1.2 on it and advise our users to expose `wazuh-dashboards` to internet using a TLSv1.3 proxy.

**Comment by miguelfdez99** [comment]
## TLSv1.2
As mentioned, we need to ensure that the TLS version is lower than 1.2.
In this [article](https://media.defense.gov/2021/Jan/05/2002560140/-1/-1/0/ELIMINATING_OBSOLETE_TLS_UOO197443-20.PDF) we can see that there are some cipher suites stronger than others. We need to be careful with the cipher suites we are using. 
This is from the article: ```Especially weak encryption algorithms in TLS 1.2 are designated as NULL, RC2, RC4, DES, IDEA, and TDES/3DES; cipher suites using these algorithms should not be used TLS 1.3 removes these cipher suites, but implementations that support both TLS 1.3 and TLS 1.2 should be checked for obsolete cipher suites```

Using ```Elliptic Curve Diffie–Hellman (ECDH)``` key exchange makes TLSv1.2 more secure
<details><summary>Image </summary>

![image](https://user-images.githubusercontent.com/61159728/180003815-f689f3ac-0f99-4dfe-884f-6ab4f44e24f0.png)
</details>

Here's an example from wazuh.com.
<details><summary>Image </summary>

![image](https://user-images.githubusercontent.com/61159728/180001812-4b221bcd-ca90-451a-bd63-817efd238c33.png)
</details>

With settings similar to the ones mentioned [here](https://github.com/wazuh/wazuh-packages/issues/1694#issue-1286275592)

````
plugins.security.ssl.http.enabled_ciphers:
  - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
  - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
  - "TLS_ECDHE_ECDSA_WITH_AES_128_ GCM_SHA256"
  - "TLS_ECDHE_ECDSA_WITH_AES_256_ GCM_SHA384"
plugins.security.ssl.http.enabled_protocols:
  - "TLSv1.2"
  - "TLSv1.3"
````
With this code, we make sure that the TLS protocol it is at least v1.2.

This is the result in the Wazuh app web.
<details><summary>Image </summary>

![image](https://user-images.githubusercontent.com/61159728/180005078-f474a7b6-dbaa-46ca-904e-869dac1920bf.png)
</details>


TLSv1.2 is supported in most browsers as it is the most used one.
<details><summary>Compatibility </summary>

![image](https://user-images.githubusercontent.com/61159728/180007312-5a77c6ec-4ab5-406c-b7d4-3da963882885.png)
</details>

<details><summary>Usage relative </summary>

![image](https://user-images.githubusercontent.com/61159728/180007544-1befedfa-2660-4dd0-b1bd-a9124c405ac6.png)

</details>

### Sources:
- [Cipher suite considerations when upgrading to TLS V1.2](https://www.ibm.com/docs/en/zos/2.4.0?topic=protocols-cipher-suite-considerations-when-upgrading-tls-v12)
- [National Security Agency ](https://media.defense.gov/2021/Jan/05/2002560140/-1/-1/0/ELIMINATING_OBSOLETE_TLS_UOO197443-20.PDF)
- [Opensearch](https://opensearch.org/docs/1.3/security-plugin/configuration/tls/#advanced-enabled-ciphers-and-protocols )
- [canisue](https://caniuse.com/tls1-2)
- [ssllabs](https://www.ssllabs.com/ssltest)

## TLSv1.3
