### ISSUE TITLE
Use the big logo in the loading page

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-packages#1730]
**Describe the solution you'd like**
Currently, while the UI is loading, the page shows the small logo: 

![image](https://user-images.githubusercontent.com/2181918/172043372-a1046659-e8f0-40eb-950c-7079396547ff.png)

We need to change it to use the big one.

![image](https://user-images.githubusercontent.com/2181918/172043453-a9bb1875-0df2-4638-9518-a306c53aa373.png)

We need to discuss the design, and the size of the logo with @wazuh/marketing team.

**Comment by alberpilot** [comment]
No, it's not complete. We need the assessments.

**Comment by FelipeKnudsen** [comment]
Here goes the assets, let me know if you need something else. Thanks!

![1](https://user-images.githubusercontent.com/80284649/178254185-9aad3e03-940a-42d5-812f-48a373d814e8.png)
![2](https://user-images.githubusercontent.com/80284649/178254189-a1379b27-96cb-4039-9f69-02106f974447.png)
