### ISSUE TITLE
Review the file "Install_wazuh_notes.rtf" in macOS package

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#177]
Hello team

  I think we need to remove the file **Install_wazuh_notes.rtf**, please review if needed and if not, please remove it. 

Best regards, 
Alberto R.

**Comment by DFolchA** [comment]
Hello team,

After investigating this issue I think there are 3 files within the macos package generation that are not being used anymore, and we should delete them:
- package_files/Install_wazuh_notes.rtf
- package_files/Introduction.txt
- package_files/README.md

Regards, 
Daniel Folch
