### ISSUE TITLE
Change the macOS warning message about package architecture in package generation

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#1782]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| - | Agent | Build | macOS |

Hi team

macOS packages are built on systems with 64-bit Intel architecture, displaying the following message in the process:

```
This installer has been built for 64-bit Intel architecture. It won't install in other platforms.
```

https://github.com/wazuh/wazuh-packages/blob/99bfbe982573efd3e64a368d31bef43991ff79af/macos/specs/wazuh-agent.pkgproj#L1025

This message is no longer entirely true, since the generated package is compatible with Apple's M1 processor, for this reason, we must change this message specifying this compatibility and thus avoid confusion for our users.

Regards, Raul.

**Comment by vikman90** [comment]
@rauldpm We're applying this request on https://github.com/wazuh/wazuh-packages/issues/2086.

Best!
