### ISSUE TITLE
Outdated URL in Wazuh installation assistant output for the offline installation

### ISSUE THREAD

**Issue by javimed** [wazuh/wazuh-packages#1795]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.6-1 | Manager | Install | CentOS 7 |

When using the Wazuh installation assistant with the offline option `-dw`, an output message inviting the user to read documentation is shown at the final steps of the execution with an outdated URL.

![image](https://user-images.githubusercontent.com/47069802/186255956-6e0f23f6-92d0-438e-9e08-9a7ba0384563.png)

The Offline installation documentation is found now in this URL:

-  https://documentation.wazuh.com/current/deployment-options/offline-installation.html

**Comment by rauldpm** [comment]
Related:

- https://github.com/wazuh/wazuh-packages/issues/1799
  - https://github.com/wazuh/wazuh-packages/pull/1835
  - https://github.com/wazuh/wazuh-packages/pull/1836

**Comment by davidcr01** [comment]
## Update report

### Research

- I have been investigating where the URL is located
- I found that the URL was typed at: `unattended_installer/install_functions/wazuh-offline-download.sh`, https://github.com/wazuh/wazuh-packages/blob/4c48c1e3c86e9a27f158fb746d0350dfcd769ea0/unattended_installer/install_functions/wazuh-offline-download.sh#L80
        
### Next steps

- Change the current URL to the new URL.
- Create package for RPM.
- Test package in CentOS6, CentOS7 and CentOS8.

**Comment by alberpilot** [comment]
This issue is fixed in 4.4 and redirections are working for 4.3 patches.
