### ISSUE TITLE
Error installing azure-cli in CentOS8

### ISSUE THREAD

**Issue by miguelfdez99** [wazuh/wazuh-packages#1821]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.6 | Manager | Install azure-cli | CentOS8 |

There is an error when installing azure-cli in CentOS8, a conflict appears when the manager is installed.

````
Error: Transaction test error:
  file /usr/lib/.build-id/64/5a8ff18b9d25378a1e76a087b57b1cbbebd4f0 from install of azure-cli-2.39.0-1.el8.x86_64 conflicts with file from package wazuh-manager-4.3.6-1.x86_64
  file /usr/lib/.build-id/6a/8e2c507488980ea470b5128233926dcb645e21 from install of azure-cli-2.39.0-1.el8.x86_64 conflicts with file from package wazuh-manager-4.3.6-1.x86_64
  file /usr/lib/.build-id/96/652dd4786fcd6016a4c0f82e3072bf8cbdfab6 from install of azure-cli-2.39.0-1.el8.x86_64 conflicts with file from package wazuh-manager-4.3.6-1.x86_64
````

It seems that RHEL8 rpm creates files in /usr/lib/.build-id to improve debugging. It generates a conflict with the embedded Wazuh python.

````
lrwxrwxrwx. 1 root root 101 Jul 15 12:18 652dd4786fcd6016a4c0f82e3072bf8cbdfab6 -> ../../../../var/ossec/framework/python/lib/python3.9/site-packages/cffi.libs/libffi-806b1a9d.so.6.0.4
[root@localhost vagrant]# ls -lh /usr/lib/.build-id/6a/8e2c507488980ea470b5128233926dcb645e21
lrwxrwxrwx. 1 root root 112 Jul 15 12:18 /usr/lib/.build-id/6a/8e2c507488980ea470b5128233926dcb645e21 -> ../../../../var/ossec/framework/python/lib/python3.9/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so
[root@localhost vagrant]# ls -lh  file /usr/lib/.build-id/64/5a8ff18b9d25378a1e76a087b57b1cbbebd4f0
ls: cannot access 'file': No such file or directory
lrwxrwxrwx. 1 root root 112 Jul 15 12:18 /usr/lib/.build-id/64/5a8ff18b9d25378a1e76a087b57b1cbbebd4f0 -> ../../../../var/ossec/framework/python/lib/python3.9/site-packages/cryptography/hazmat/bindings/_padding.abi3.so
````

As far as packages the solution could be deactivating the build-id.

````
%define _build_id_links none
````

To see if this solution works we could check this:
- Try to install azure-cli in more OS to see if this error also happens.
- Install wazuh-manager and install azure-cli .
- Install the package and check that does not have python3/python dependencies for the installation.
- Check that wazuh is not linked to the OS's python.
- Upgrade wazuh-manager after installing azure-cli.
- Check agent connection after installing azure-cli.
- Check that the manager works as expected.

One possible temporary solution could be installing azure-cli through pip. In order to achieve this these steps needs to be followed:
- Install Python 3.9

````
yum install python3.9
````
- Set Python as the main Python of the system

````
update-alternatives --config python3
````
- Install azure-cli

````
pip3 install azure-cli
````

**Comment by alberpilot** [comment]
Duplicated: https://github.com/wazuh/wazuh-packages/issues/1796
