### ISSUE TITLE
Wazuh indexer package should preserve config files upon upgrade

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-packages#1850]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.x | Wazuh indexer | Install/Upgrade | Any |

When you upgrade the Wazuh indexer package, files stored under `/usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig` are overwritten.

This potentially happens in other similar folders.

Even though this configuration, when loaded, is stored in a Wazuh indexer index, and even if generating a backup of the index before upgrading is preferable, the Wazuh indexer package should preserve these files.

I have tested this behavior in older Open Distro and OpenSearch RPM versions and they do indeed preserve these files.

Regards,

Javier.

**Comment by davidcr01** [comment]
## Update Report

I noticed that in RPM packaging there is a macro, `%config(noreplace)`, which makes a file not to be replaced on an upgrade if it has been edited on disk. This could avoid the `securityconfig` files to be overwritten by an upgrade of the package.
Here is an example:
https://github.com/wazuh/wazuh-packages/blob/f09df4929222c6d42611e4026be2424dccb29d04/stack/indexer/rpm/wazuh-indexer.spec#L439-L440

**Comment by alberpilot** [comment]
This issue goes to On Hold due to: https://github.com/wazuh/wazuh-packages/issues/1954

**Comment by davidcr01** [comment]
## Update Report

Regarding Debian, it seems that the Debian package manager keeps every file stored in the `/etc` folder. To check this, I will create a Debian package with the wazuh-packages generator with the `--future` option and upgrade to it.

:warning: In the process of the package creation, I found a problem in the generation of the docker image. It seems that some GPG keys were expired so the docker image could not be created. Debian repositories were changing and caused the error

**Comment by davidcr01** [comment]
## Update Report

### Debian

:white_check_mark: After creating the two packages of wazuh-indexer, both created from the branch of this issue, the `opensearch-security` files are not overwritten in the upgrade. This test shows an installation of wazuh-indexer (4.5.0) with two files modified and an upgrade to a `--future` version (99.99).

<details><summary>Show log</summary>

```
root@vagrant:/home/vagrant# apt-get install wazuh-indexer_4.5.0-1_amd64.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package wazuh-indexer_4.5.0-1_amd64.deb
E: Couldn't find any package by glob 'wazuh-indexer_4.5.0-1_amd64.deb'
E: Couldn't find any package by regex 'wazuh-indexer_4.5.0-1_amd64.deb'
root@vagrant:/home/vagrant# apt-get install ./wazuh-indexer_4.5.0-1_amd64.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'wazuh-indexer' instead of './wazuh-indexer_4.5.0-1_amd64.deb'
The following NEW packages will be installed:
  wazuh-indexer
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/402 MB of archives.
After this operation, 669 MB of additional disk space will be used.
Get:1 /home/vagrant/wazuh-indexer_4.5.0-1_amd64.deb wazuh-indexer amd64 4.5.0-1 [402 MB]
Selecting previously unselected package wazuh-indexer.
(Reading database ... 42512 files and directories currently installed.)
Preparing to unpack .../wazuh-indexer_4.5.0-1_amd64.deb ...
Creating wazuh-indexer group... OK
Creating wazuh-indexer user... OK
Unpacking wazuh-indexer (4.5.0-1) ...
Processing triggers for ureadahead (0.100.0-21) ...
Processing triggers for systemd (237-3ubuntu10.25) ...
Setting up wazuh-indexer (4.5.0-1) ...
Created opensearch keystore in /etc/wazuh-indexer/opensearch.keystore
Processing triggers for systemd (237-3ubuntu10.25) ...
Processing triggers for ureadahead (0.100.0-21) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
root@vagrant:/home/vagrant# vim /etc/wazuh-indexer/opensearch-security/config.yml 
root@vagrant:/home/vagrant# vim /etc/wazuh-indexer/opensearch-security/internal_users.yml 
root@vagrant:/home/vagrant# ls -l /etc/wazuh-indexer/opensearch-security/
total 68
-rw-r----- 1 wazuh-indexer wazuh-indexer    50 Dec 13 15:15 action_groups.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  1973 Dec 13 15:15 allowlist.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  2541 Dec 13 15:15 audit.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  9957 Dec 13 15:44 config.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  1321 Dec 13 15:44 internal_users.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer   154 Dec 13 15:15 nodes_dn.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer 12381 Dec 13 15:15 opensearch.yml.example
-rw-r----- 1 wazuh-indexer wazuh-indexer  1511 Nov 21 07:19 roles_mapping.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  4642 Nov 21 07:19 roles.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer   170 Dec 13 15:15 tenants.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  1973 Dec 13 15:15 whitelist.yml
root@vagrant:/home/vagrant# apt-get install ./wazuh-indexer_99.99.0-1_amd64.deb Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'wazuh-indexer' instead of './wazuh-indexer_99.99.0-1_amd64.deb'
The following packages will be upgraded:
  wazuh-indexer
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/402 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 /home/vagrant/wazuh-indexer_99.99.0-1_amd64.deb wazuh-indexer amd64 99.99.0-1 [402 MB]
(Reading database ... 43575 files and directories currently installed.)
Preparing to unpack .../wazuh-indexer_99.99.0-1_amd64.deb ...
Unpacking wazuh-indexer (99.99.0-1) over (4.5.0-1) ...
Processing triggers for ureadahead (0.100.0-21) ...
Processing triggers for systemd (237-3ubuntu10.25) ...
Setting up wazuh-indexer (99.99.0-1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
root@vagrant:/home/vagrant# ls -l /etc/wazuh-indexer/opensearch-security/
total 68
-rw-r----- 1 wazuh-indexer wazuh-indexer    50 Dec 13 15:15 action_groups.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  1973 Dec 13 15:15 allowlist.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  2541 Dec 13 15:15 audit.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  9957 Dec 13 15:44 config.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  1321 Dec 13 15:44 internal_users.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer   154 Dec 13 15:15 nodes_dn.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer 12381 Dec 13 15:15 opensearch.yml.example
-rw-r----- 1 wazuh-indexer wazuh-indexer  1511 Nov 21 07:19 roles_mapping.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  4642 Nov 21 07:19 roles.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer   170 Dec 13 15:15 tenants.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  1973 Dec 13 15:15 whitelist.yml
root@vagrant:/home/vagrant# vim /etc/wazuh-indexer/opensearch-security/internal_users.yml 
root@vagrant:/home/vagrant# apt-cache policy wazuh-indexer
wazuh-indexer:
  Installed: 99.99.0-1
  Candidate: 99.99.0-1
  Version table:
 *** 99.99.0-1 100
        100 /var/lib/dpkg/status
root@vagrant:/home/vagrant# 
```

</details>


:white_check_mark: Another test similar to the previous one, but this time upgrading from 4.4 to 99.99 version (created from 4.5.0).

<details><summary>Show log</summary>

```
root@vagrant:/home/vagrant# apt-get install ./wazuh-indexer_4.4.0-1_amd64.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'wazuh-indexer' instead of './wazuh-indexer_4.4.0-1_amd64.deb'
The following NEW packages will be installed:
  wazuh-indexer
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/402 MB of archives.
After this operation, 669 MB of additional disk space will be used.
Get:1 /home/vagrant/wazuh-indexer_4.4.0-1_amd64.deb wazuh-indexer amd64 4.4.0-1 [402 MB]
Selecting previously unselected package wazuh-indexer.
(Reading database ... 42512 files and directories currently installed.)
Preparing to unpack .../wazuh-indexer_4.4.0-1_amd64.deb ...
Creating wazuh-indexer group... OK
Creating wazuh-indexer user... OK
Unpacking wazuh-indexer (4.4.0-1) ...
Processing triggers for ureadahead (0.100.0-21) ...
Processing triggers for systemd (237-3ubuntu10.25) ...
Setting up wazuh-indexer (4.4.0-1) ...
Created opensearch keystore in /etc/wazuh-indexer/opensearch.keystore
Processing triggers for systemd (237-3ubuntu10.25) ...
Processing triggers for ureadahead (0.100.0-21) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
root@vagrant:/home/vagrant# vim /etc/wazuh-indexer/opensearch-security/config.yml 
root@vagrant:/home/vagrant# vim /etc/wazuh-indexer/opensearch-security/internal_users.yml 
root@vagrant:/home/vagrant# ls -l /etc/wazuh-indexer/opensearch-security/
total 68
-rw-r----- 1 wazuh-indexer wazuh-indexer    50 Dec 13 15:55 action_groups.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  1973 Dec 13 15:55 allowlist.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  2541 Dec 13 15:55 audit.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  9957 Dec 13 16:11 config.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  1321 Dec 13 16:11 internal_users.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer   154 Dec 13 15:55 nodes_dn.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer 12381 Dec 13 15:55 opensearch.yml.example
-rw-r----- 1 wazuh-indexer wazuh-indexer  1511 Nov 21 07:19 roles_mapping.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  4642 Nov 21 07:19 roles.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer   170 Dec 13 15:55 tenants.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  1973 Dec 13 15:55 whitelist.yml
root@vagrant:/home/vagrant# apt-get install ./wazuh-indexer_99.99.0-1_amd64.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'wazuh-indexer' instead of './wazuh-indexer_99.99.0-1_amd64.deb'
The following packages will be upgraded:
  wazuh-indexer
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/402 MB of archives.
After this operation, 1,024 B of additional disk space will be used.
Get:1 /home/vagrant/wazuh-indexer_99.99.0-1_amd64.deb wazuh-indexer amd64 99.99.0-1 [402 MB]
(Reading database ... 43575 files and directories currently installed.)
Preparing to unpack .../wazuh-indexer_99.99.0-1_amd64.deb ...
Unpacking wazuh-indexer (99.99.0-1) over (4.4.0-1) ...
Processing triggers for ureadahead (0.100.0-21) ...
Processing triggers for systemd (237-3ubuntu10.25) ...
Setting up wazuh-indexer (99.99.0-1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
root@vagrant:/home/vagrant# ls -l /etc/wazuh-indexer/opensearch-security/
total 68
-rw-r----- 1 wazuh-indexer wazuh-indexer    50 Dec 13 15:55 action_groups.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  1973 Dec 13 15:55 allowlist.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  2541 Dec 13 15:55 audit.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  9957 Dec 13 16:11 config.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  1321 Dec 13 16:11 internal_users.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer   154 Dec 13 15:55 nodes_dn.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer 12381 Dec 13 15:55 opensearch.yml.example
-rw-r----- 1 wazuh-indexer wazuh-indexer  1511 Nov 21 07:19 roles_mapping.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  4642 Nov 21 07:19 roles.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer   170 Dec 13 15:55 tenants.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  1973 Dec 13 15:55 whitelist.yml
root@vagrant:/home/vagrant# apt-cache policy wazuh-indexer
wazuh-indexer:
  Installed: 99.99.0-1
  Candidate: 99.99.0-1
  Version table:
 *** 99.99.0-1 100
        100 /var/lib/dpkg/status
root@vagrant:/home/vagrant# 
```
</details>

**Comment by davidcr01** [comment]
## Update Report

To solve the 4.3 problems, I added to the `postinstall` stage the following lines to move the files of `securityconfig` folder to the `opensearch-security` folder of 4.4 and 4.5 versions in case of an upgrade.

**RPM**
https://github.com/wazuh/wazuh-packages/blob/80a4f838516d597c13fce95cf238d3a846bb4081/stack/indexer/rpm/wazuh-indexer.spec#L173-L183

**Debian**
https://github.com/wazuh/wazuh-packages/blob/e41d9d60fdd4c1545257f95dd11112b0b5fe9bdd/stack/indexer/deb/debian/postinst#L107-L113

**Comment by davidcr01** [comment]
## Update Report

### Debian

The previous Debian change did not work, so I change the way to do it by saving the `securityconfig` files in a backup folder and restoring them after the upgrade.

:x: Following the diagram below, I tried to save those files in the `postrm` and restore them in the `postinst`. But this alternative did not work. This try is in the https://github.com/wazuh/wazuh-packages/commit/356309cd2e4c37a1bc63f3a0ef7711eee7d37d0d commit.

<details><summary>Display diagram</summary>

![image](https://user-images.githubusercontent.com/72193239/207948085-173fb232-f661-4045-8582-e51af44eb870.png)
</details>

:bulb: After some research, I found that the process of the upgrade was different. To summarize, the process is old `prerm`, new `preinst`, old `postrm`, new `postinst`) as these sources explain:
- https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html
- https://unix.stackexchange.com/questions/218571/what-exactly-happens-when-i-exec-apt-get-upgrade

So, the `postrm` was not executing in the tests. Now, with this information, the backup must be done in the new `preinst` and the new `postinst`.
:warning: This process can not be done only in the `postinst` stage, as the `postrm` stage deletes the `securityconfig` folder. 


### Next steps

Do the backup in the `preinst` and the `postinst` stages.

**Comment by davidcr01** [comment]
### Update Report

:green_circle: The test for the Debian upgrade from `4.3` to my branch finally passed.

<details><summary>Show log</summary>

```
root@vagrant:/home/vagrant# apt-get install ./wazuh-indexer_4.3.10-1_amd64.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'wazuh-indexer' instead of './wazuh-indexer_4.3.10-1_amd64.deb'
The following NEW packages will be installed:
  wazuh-indexer
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/356 MB of archives.
After this operation, 638 MB of additional disk space will be used.
Get:1 /home/vagrant/wazuh-indexer_4.3.10-1_amd64.deb wazuh-indexer amd64 4.3.10-1 [356 MB]
Selecting previously unselected package wazuh-indexer.
(Reading database ... 42512 files and directories currently installed.)
Preparing to unpack .../wazuh-indexer_4.3.10-1_amd64.deb ...
Creating wazuh-indexer group... OK
Creating wazuh-indexer user... OK
Unpacking wazuh-indexer (4.3.10-1) ...
Processing triggers for ureadahead (0.100.0-21) ...
Processing triggers for systemd (237-3ubuntu10.25) ...
Setting up wazuh-indexer (4.3.10-1) ...
Created opensearch keystore in /etc/wazuh-indexer/opensearch.keystore
Processing triggers for systemd (237-3ubuntu10.25) ...
Processing triggers for ureadahead (0.100.0-21) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
root@vagrant:/home/vagrant# vim /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/config.yml 
root@vagrant:/home/vagrant# vim /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/internal_users.yml 
root@vagrant:/home/vagrant# ls -l /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/
total 64
-rw-r----- 1 wazuh-indexer wazuh-indexer    49 Jan 14  2022 action_groups.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  2541 Jan 14  2022 audit.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  9957 Dec 16 17:44 config.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  1322 Dec 16 17:44 internal_users.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer   154 Jan 14  2022 nodes_dn.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer 12615 Jan 14  2022 opensearch.yml.example
-rw-r----- 1 wazuh-indexer wazuh-indexer  1511 Nov 21 07:19 roles_mapping.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  4642 Nov 21 07:19 roles.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer   170 Jan 14  2022 tenants.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  1973 Jan 14  2022 whitelist.yml
root@vagrant:/home/vagrant# apt-get install ./wazuh-indexer_4.5.0-1_amd64.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'wazuh-indexer' instead of './wazuh-indexer_4.5.0-1_amd64.deb'
The following packages will be upgraded:
  wazuh-indexer
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/402 MB of archives.
After this operation, 30.7 MB of additional disk space will be used.
Get:1 /home/vagrant/wazuh-indexer_4.5.0-1_amd64.deb wazuh-indexer amd64 4.5.0-1 [402 MB]
(Reading database ... 43457 files and directories currently installed.)
Preparing to unpack .../wazuh-indexer_4.5.0-1_amd64.deb ...
Making backup of securityconfig files...Unpacking wazuh-indexer (4.5.0-1) over (4.3.10-1) ...
Processing triggers for ureadahead (0.100.0-21) ...
Processing triggers for systemd (237-3ubuntu10.25) ...
Setting up wazuh-indexer (4.5.0-1) ...
Installing new version of config file /etc/default/wazuh-indexer ...

Configuration file '/etc/wazuh-indexer/jvm.options'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** jvm.options (Y/I/N/O/D/Z) [default=N] ? 
Installing new version of config file /etc/wazuh-indexer/log4j2.properties ...
Installing new version of config file /etc/wazuh-indexer/opensearch.yml ...
Copying securityconfig files from backup...Processing triggers for libc-bin (2.27-3ubuntu1) ...
root@vagrant:/home/vagrant# ls -l /etc/wazuh-indexer/opensearch-security/
total 68
-rw-r----- 1 wazuh-indexer wazuh-indexer    49 Dec 16 17:45 action_groups.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  1973 Dec 16 17:09 allowlist.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  2541 Dec 16 17:45 audit.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  9957 Dec 16 17:45 config.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  1322 Dec 16 17:45 internal_users.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer   154 Dec 16 17:45 nodes_dn.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer 12615 Dec 16 17:45 opensearch.yml.example
-rw-r----- 1 wazuh-indexer wazuh-indexer  1511 Dec 16 17:45 roles_mapping.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  4642 Dec 16 17:45 roles.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer   170 Dec 16 17:45 tenants.yml
-rw-r----- 1 wazuh-indexer wazuh-indexer  1973 Dec 16 17:45 whitelist.yml
root@vagrant:/home/vagrant# 
```
</details>

The changes I have done were described in the previous comment. To summarize:
- In `preinst`:
https://github.com/wazuh/wazuh-packages/blob/83c422d3270b4c53824cc5843589d86b6b518b63/stack/indexer/deb/debian/preinst#L63-L70

- In `postinst`:
https://github.com/wazuh/wazuh-packages/blob/83c422d3270b4c53824cc5843589d86b6b518b63/stack/indexer/deb/debian/postinst#L86-L92

**Comment by alberpilot** [comment]
GitHub Actions tests were required. This issue goes to On Hold.

**Comment by davidcr01** [comment]
## Update Report

Currently working on the GitHub Action workflow. 

https://github.com/wazuh/wazuh-packages/blob/1850-wazuh-indexer-preserve-config-files-upon-upgrade-master/.github/workflows/test-indexer.yml

https://github.com/wazuh/wazuh-packages/blob/1850-wazuh-indexer-preserve-config-files-upon-upgrade-master/.github/actions/upgrade-indexer/test-debian.sh

**Comment by davidcr01** [comment]
## Update Report

The `test-upgrade-debian.sh` script has been changed, making it more parametrized.
- Install the most recent wazuh indexer package version (release).
- Get the name of the generated package and avoid to hardcode it.

I got many problems performing the second point, because I tried to store it and use it in the same stage of the workflow until I noticed. 
https://stackoverflow.com/questions/57968497/how-do-i-set-an-env-var-with-a-bash-expression-in-github-actions

> [...]the environment variable does not have access to the new value, but all subsequent actions in a job will have access


Some unexpected behavior has been detected in the script. Currently fixing them.

**Comment by davidcr01** [comment]
## Update Report

Finally, I finished the workflow and action for the wazuh-indexer upgrade package in Debian. 

Currently, this workflow does not use the environmental variable mentioned in the previous report due to it is not supported after some failed checks.
- Use of `env` parameter in the workflow file -> deprecated https://stackoverflow.com/a/57969570
- Sintaxis for `{{ env.VARIABLE }}` does not work inside the script. https://stackoverflow.com/a/74488946
- Not working using `#!/usr/bin/env bash` instead of `#!/bin/bash`
- Finally, the encountered solution is to pass this environmental variable as a parameter of the script, as it can not access directly the environmental variables defined in the workflow. 
Link to a StackOverflow conversation with the same problem: https://stackoverflow.com/a/61235800

**Comment by davidcr01** [comment]
## Update Report

I am currently working on the workflow to test in RPM.

Encountered problems:
- In RPM, a docker container must be used to run the action script. Because of this, the workflow can not download the release package, this step must be moved to the action script `upgrade-indexer-rpm.sh`. New function added: `preinstall_indexer_release`
```
function preinstall_indexer_release() {
    rpm --import https://packages.wazuh.com/key/GPG-KEY-WAZUH
    echo -e '[wazuh]\ngpgcheck=1\ngpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH\nenabled=1\nname=EL-$releasever - Wazuh\nbaseurl=https://packages.wazuh.com/4.x/yum/\nprotect=1' | tee /etc/yum.repos.d/wazuh.repo
}
```
- The command `local -n variable[=value]` used in the Debian action, `upgrade-indexer-debian.sh` can not be used in the RPM test as CentOS7 does not support bash 4.3. Currently searching for an alternative...

**Comment by davidcr01** [comment]
## Update Report

The proposed alternative is not to use local references to the arrays and not to depend on the bash version in `CentOS` tests. Using this alternative, arrays are not passed as parameters when invoking the functions of the script. Instead, some flags are passed to control the function flow. For instance:

https://github.com/wazuh/wazuh-packages/blob/9a3cd604c1960496124a01814d7f6efd151b14de/.github/actions/upgrade-indexer/upgrade-indexer-rpm.sh#L46-L51

https://github.com/wazuh/wazuh-packages/blob/9a3cd604c1960496124a01814d7f6efd151b14de/.github/actions/upgrade-indexer/upgrade-indexer-rpm.sh#L80

With this, tests passed as expected. These tests download the fix package instead of generating it (provisionally) to take less time.
- :green_circle: Passed test, expected to pass: https://github.com/wazuh/wazuh-packages/actions/runs/3828157138/jobs/6513435770
- :red_circle:  Unpassed test, expected not to pass as it uses another package: https://github.com/wazuh/wazuh-packages/actions/runs/3828204920/jobs/6513533723. The test fails when comparing the first file with a different checksum, which is the expected behavior.

:green_circle: Test passed generating the package instead of downloading it: https://github.com/wazuh/wazuh-packages/actions/runs/3828236708/jobs/6513599480

**Comment by davidcr01** [comment]
## Update Report

- :green_circle: Second improvement achieved. The file `common.sh` includes all the variables and functions used in the action. The action itself is now called `upgrade-indexer.sh` which invokes the necessary functions of `common.sh` and execute them depending on the detected system. 
https://github.com/wazuh/wazuh-packages/actions/runs/3837179008
https://github.com/wazuh/wazuh-packages/actions/runs/3837178995
