### ISSUE TITLE
`authd.pass` is not created in the agent when the password is empty

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-packages#1863]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 4.4.0-0.commitce045ec | Manager and Agent | Packages | Any, tested in Ubuntu 22 and Windows Server 2022 |

# Description

When we set up the `/var/ossec/etc/authd.pass` as empty(manager side), we are not able to register an agent. The `authd.pass` file is not created(agent side) and the log that appears is not that good for this behavior:

```
2022/09/21 11:54:48 wazuh-authd: INFO: New connection from 172.31.5.20
2022/09/21 11:54:48 wazuh-authd: ERROR: Invalid password provided by 172.31.5.20. Closing connection.
```
>This behavior occurs when we set the password as an empty string, or just spaces.

We may have a few approaches to improve this:

1. If the user don't want to use a password, do not allow the user to set the password as an empty value: improve the logging, and notify the user via `ERROR` that it is not allowed. We should be more precise than just a log like this one `2022/09/21 11:54:48 wazuh-authd: ERROR: Invalid password provided by 172.31.5.20. Closing connection.`

2. Set a default password and the authd.pass is created

3. Add to the documentation this exception

This bug has been tested both `4.3.7` and `4.4.0` with fix changes. More info about it [here](https://github.com/wazuh/wazuh-qa/issues/3317).

<details><summary>Steps to reproduce this bug</summary>

1. Configure the manager to use password authentication

    ```
    echo "" > /var/ossec/etc/authd.pass
    chmod 640 /var/ossec/etc/authd.pass
    chown root:wazuh /var/ossec/etc/authd.pass
    ```

2. Set the pass auth method using the `ossec.conf`
    ```
    <use_password>yes</use_password>
    ```

3. Restart the manager

    ```
    systemctl restart wazuh-manager
    ```

4. Install an agent using `WAZUH_REGISTRATION_PASSWORD`

    ```
    WAZUH_MANAGER="172.31.7.232" WAZUH_REGISTRATION_PASSWORD="" apt install ./wazuh-agent_4.4.0-0.commitce045ec_amd64.deb 
    ```

5. Check the enrollment logs

    ```
    2022/09/21 11:54:48 wazuh-authd: INFO: New connection from 172.31.5.20
    2022/09/21 11:54:48 wazuh-authd: ERROR: Invalid password provided by 172.31.5.20. Closing connection.
    ```

6. The `auth.pass` is not created

    ```
    root@ip-172-31-5-20:/home/qa# ll /var/ossec/etc/authd.pass
    ls: cannot access '/var/ossec/etc/authd.pass': No such file or directory
    ```

</details>

**Comment by vikman90** [comment]
Superseded by:

- https://github.com/wazuh/wazuh/issues/22677
