### ISSUE TITLE
Remove the `vagrant` `OVA` user `PAM` configuration

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#1866]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.7 | OVA | - | CentOS 7 |

A user has reported the inability to access the `root` user from the `wazuh-user` user account in the `v4.3.7 OVA` using the `su root` command.

```
[wazuh-user@wazuh-server ~]$ su root
Password: 
su: Authentication failure
```

Reviewing the user permissions, it has been found that in the `PAM` (Pluggable Authentication Modules) configuration, the `vagrant` user, which does not exist in the system due to its elimination during the construction of the package, is `hard-coded` in the `/etc/pam.d/su` file.

```
**account         [success=1 default=ignore] \
                                pam_succeed_if.so user = vagrant use_uid quiet
account         required        pam_succeed_if.so user notin root:vagrant **
```

We need to change the `vagrant` user to `wazuh-user` or allow any user on the system to use the `su` command.

```
sudo sed -i "s/vagrant/wazuh-user/g" /etc/pam.d/su
```

```
account         [success=1 default=ignore] \
                                pam_succeed_if.so user = wazuh-user use_uid quiet
account         required        pam_succeed_if.so user notin root:wazuh-user
```

After making this change, it is possible to switch users using the `su root` command.

```
[wazuh-user@wazuh-server ~]$ su root
Password: 
[root@wazuh-server wazuh-user]#
```

**Comment by teddytpc1** [comment]
The new OVA (`v4.5.1`) allows the `wazuh-user` to run the `su root` command:
 
![ovaroot](https://github.com/wazuh/wazuh-packages/assets/33964202/36d4e10f-7bb8-4419-a776-4c1d1e49f93d)

the `vagrant` user does not exist as the base OS is a custom box that does not include it.
