### ISSUE TITLE
macOS installer install two packages of Wazuh 

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-packages#187]
Hi team,

The macOS installer seems to install two packages instead of one. You can list them using `pkgutil --pkgs` as follows:
```shellsession
$ pkgutil --pkgs | grep -i wazuh
com.wazuh.pkg.wazuh-agent
com.wazuh.pkg.wazuh-agent-etc
```

Probably, the `com.wazuh.pkg.wazuh-agent-etc` package is used to mark the configuration files and don't overwrite them while upgrading the packages. We must review this and improve it.

Regards.

**Comment by DFolchA** [comment]
Hello team, 

I have been investigating this issue and the file second package `com.wazuh.pkg.wazuh-agent-etc` as @BraulioV said contains configuration files, but it also contains some files that don't correspond to the OS so we should try to just include files related to macos.

Regards, 
Daniel Folch

**Comment by DFolchA** [comment]
Hello team,

I have been investigating how the .pkgproj works and if it is possible to combine both packages into one by modifying it.

Regards,
Daniel Folch

**Comment by DFolchA** [comment]
Hello team,

I have removed the package `com.wazuh.pkg.wazuh-agent-etc` from the installation, now I am working on how to avoid the overwriting of the configuration files after an upgrade.

Regards,
Daniel Folch

**Comment by DFolchA** [comment]
Hello team,

I have been investigating about  how to save the configuration files and it seems the packages application that we use for building the packages runs pkgbuild on the background, and the specs of the packages are given to pkgbuild.
So I am now looking for documentation about this function to see if we can make the upgrade process not to overwrite the configuration files, without using the pre-post install scripts.

Regards,
Daniel Folch

**Comment by DFolchA** [comment]
Hello team, 

Regretfully I couldn't find a way to preserve the configuration files that were preserved by `wazuh-agent-etc` only using the pkgproj file to configure the package.

So, I will do this relying on the pre/post install scripts to make a copy of the files.

Regards,
Daniel Folch

**Comment by DFolchA** [comment]
Hello team,

I have modified the pre/post-install scripts so we can preserve the configuration files:

https://github.com/wazuh/wazuh-packages/blob/ffc6ae95d6dcbdb7741098291b854f61e9e70b77/macos/package_files/3.9.3/preinstall.sh#L20-L23

https://github.com/wazuh/wazuh-packages/blob/ffc6ae95d6dcbdb7741098291b854f61e9e70b77/macos/package_files/3.9.3/postinstall.sh#L17-L21

I have also added a check for the version, so when we are upgrading from an old version the had the -etc package we uninstall that package first.

https://github.com/wazuh/wazuh-packages/blob/ffc6ae95d6dcbdb7741098291b854f61e9e70b77/macos/package_files/3.9.3/preinstall.sh#L25-L32

Lastly, I have made connection tests to make sure the package was able to connect with a manager, in this case, the manager in a centos 7 with a 3.9.2 version of the manager.

Regards,
Daniel Folch.

**Comment by DFolchA** [comment]
Hello team,
I have changed the way  we check the version:
https://github.com/wazuh/wazuh-packages/blob/d5f0b4f92d7b5022e7f6371c7cede8d88049beed/macos/package_files/3.9.3/preinstall.sh#L25-L39
And tested if the -etc package was uninstalled after an upgrade:
![image](https://user-images.githubusercontent.com/19505384/60163952-f9340700-97fc-11e9-99b0-46be49bb9ee4.png)

After this, I have run several tests to check connectivity with the manager after the upgrade from different versions, the manager I used was a 3.9.2 manager in a Centos 7 machine:
- [x] 3.7.0 => 3.9.3
- [x] 3.8.2 => 3.9.3
- [x] 3.9.0 => 3.9.3
- [x] 3.9.2 => 3.9.3
- [x] 3.9.3 => 3.9.3
- [x] 3.9.0 => 3.10.0

And lastly, I built a package using Jenkins:
 https://jenkins-staging.wazuh.info/job/Build_OSX_packages/435/

Regards,
Daniel Folch
