### ISSUE TITLE
Upgrade and then downgrade doesn't work with 3.9

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-packages#189]
Hi team,

We have detected that upgrading a Wazuh manager RPM and probably Debian also from `3.8.2` to `3.9.1` and then downgrade to `3.8.2` produce errors on log:
* The first error is related with the rules that couldn't be loaded and manager stops.
* The other one is related to Manager database that isn't at right version.

Regards.

**Comment by BraulioV** [comment]
Hi @okynos,

I'm closing this issue because the downgrade between 4.x works and downgrading from 4.x to 3.x requires manual interaction due to the removal of the wazuh-api package in 4.x.

Feel free to reopen it if you have any doubts.
