### ISSUE TITLE
`generate_wazuh_packages.sh` is removing `package_files/*.sh` on macOS after execution

### ISSUE THREAD

**Issue by tsarquis88** [wazuh/wazuh-packages#1902]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| Any | Manager & Agent | PKG generation | Any macOS distro |

### Description
On macOS, the package generation script is removing definitely the scripts under `package_files` folder, being impossible to run the script succesfully again.

### Steps to reproduce
- [Generate a package](https://documentation.wazuh.com/current/development/packaging/generate-osx-package.html) on any macOS distribution
- Run `ls package_files/` - No `.sh` should be present.

### Possible cause
Scripts are first [backuped](https://github.com/wazuh/wazuh-packages/blob/b9caf1f53e14c72d8a7d6b1a528077549313027e/macos/generate_wazuh_packages.sh#L40) and then the backups are tried to be [removed](https://github.com/wazuh/wazuh-packages/blob/b9caf1f53e14c72d8a7d6b1a528077549313027e/macos/generate_wazuh_packages.sh#L145). Problem seems to be in the first step:
```
143 - packages_script_path="package_files"
144 -
145 - cp ${packages_script_path}/*.sh ${CURRENT_PATH}/package_files/
```
In which source and destination paths are the same, so no backup is really created, and the removed files are the original ones.

**Comment by verdx** [comment]
The removing of the scripts has been solved in issue #1965 but the unnecessary backup is not.
