### ISSUE TITLE
Static Key Ciphers and TLSv1.1

### ISSUE THREAD

**Issue by BPJOHN1990** [wazuh/wazuh-packages#1927]
Hi,

I am using Wazuh 4.3.4. I performed a vulnerability scan on my own Wazuh and found out that TLSv1.1 and static key ciphers were supported in Port 443, Port 1515 and Port 55000.

I have configured the port 443 ciphers in the opensearch.yml file in /etc/wazuh-indexer/ to appear stated in this following website: https://opensearch.org/docs/latest/security-plugin/configuration/tls/#advanced-enabled-ciphers-and-protocols I have also restarted the wazuh-dashboard services but static key ciphers and TLS v1.1 were still detected. For Port 1515 and Port 55000 I would greatly appreciate it if anyone can point me to the right direction to configure the ciphers/TLS version to disable the insecure ciphers and TLS version

My current configured opensearch.yml file:
-----------------------------------
...
plugins.security.ssl.http.enabled_ciphers:
- "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
- "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
- "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
- "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"

plugins.security.ssl.http.enabled_protocols:
- "TLSv1.2"
...

**Comment by vikman90** [comment]
@BPJOHN1990 Please refer:
- [The auth configuration reference](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/auth.html).
- [OpenSSL 1.1.1 ciphers](https://www.openssl.org/docs/man1.1.1/man1/ciphers.html).

Just set `<cipher>` _in ossec.conf_ to this:
```xml
<ciphers"TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384</ciphers>
```

On the other hand, _wazuh-authd_ (and agents) always try to use TLS v1.2. They will even always use it except if you use OSSEC or Wazuh older than v3.5. If you want to enforce TLS v1.2+, just make sure that `<ssl_auto_negotiate>` is missing or set to "no":
```xml
<ssl_auto_negotiate>no</ssl_auto_negotiate>
```
I mean, the default value is not to allow SSL or TLS older than 1.2.

Hope this helps.
Best regards.

**Comment by BPJOHN1990** [comment]
Hi @vikman90,

I tried setting the ciphers accordingly but now Wazuh-Manager cannot be started.

● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/usr/lib/systemd/system/wazuh-manager.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2023-07-03 08:43:03 UTC; 1min 23s ago
  Process: 7682 ExecStop=/usr/bin/env /var/ossec/bin/wazuh-control stop (code=exited, status=0/SUCCESS)
  Process: 8296 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=1/FAILURE)
   CGroup: /system.slice/wazuh-manager.service
           ├─7911 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─7961 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           └─7964 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py

Jul 03 08:42:51 wazuh-server env[8296]: Starting Wazuh v4.4.3...
Jul 03 08:42:52 wazuh-server env[8296]: wazuh-apid already running...
Jul 03 08:42:52 wazuh-server env[8296]: Started wazuh-csyslogd...
Jul 03 08:42:52 wazuh-server env[8296]: Started wazuh-dbd...
Jul 03 08:42:52 wazuh-server env[8296]: 2023/07/03 08:42:52 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Jul 03 08:42:52 wazuh-server env[8296]: Started wazuh-integratord...
Jul 03 08:42:52 wazuh-server env[8296]: Started wazuh-agentlessd...
Jul 03 08:43:03 wazuh-server env[8296]: wazuh-authd did not start correctly.

**Comment by vikman90** [comment]
@BPJOHN1990 You're right. I'm digging into this, and it seems like if OpenSSL did not include these ciphers despite the documentation.

Try out this command: `openssl -v <CIPHERS>`. 

`<CIPHERS>` is the list of ciphers, as indicated in the `<ciphers>` option.

For instance:

```shell
openssl ciphers -v 'TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384'
```
```
Error in cipher list
800BE301737F0000:error:0A0000B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:../ssl/ssl_lib.c:2745:
```

I recommend you get the list of all ciphers:

```shell
openssl ciphers -v 'ALL`
```

Or just the TLSv1.2 ciphers:
```
openssl ciphers -v 'TLSv1.2'
```

And then either remove the ciphers you don't want to use, for instance:
```shell
openssl ciphers -v 'TLSv1.2:!CAMELLIA256-SHA256:!CAMELLIA128-SHA256'
```

Or explicitly list which ciphers you want. In fact, I think these are the correct cipher names:
```shell
 openssl ciphers -v 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384'
```

Then, set up the Authd configuration accordingly:

```xml
<auth>
  <ciphers>ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384</ciphers>
</auth>
```

I've tested the configuration with that setting, and I confirm it works on Wazuh 4.4.4.

Best.

**Comment by BPJOHN1990** [comment]
Hi Vikman,

Thanks for the help on Port 1515, now its secure. Do you have any clue on how to set the same secure ciphers for port 443 as well?

My current configuration in /etc/wazuh-dashboard/opensearch_dashboards.yml is: 
server.ssl.supportedProtocols:
 - "TLSv1.2"
server.ssl.cipherSuites:
 - "!TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA"
 - "!TLS_RSA_WITH_AES_128_CBC_SHA"
 - "!AES128-SHA"
 - "!ECDHE-RSA-AES128-SHA"
 - "TLS_AES_256_GCM_SHA384"
 - "TLS_CHACHA20_POLY1305_SHA256"
 - "TLS_AES_128_GCM_SHA256"
 - "ECDHE-RSA-AES128-GCM-SHA256"
 - "ECDHE-ECDSA-AES128-GCM-SHA256"
 - "ECDHE-RSA-AES256-GCM-SHA384"
 - "ECDHE-ECDSA-AES256-GCM-SHA384"
 - "DHE-RSA-AES128-GCM-SHA256"
 - "ECDHE-RSA-AES128-SHA256"
 - "DHE-RSA-AES128-SHA256"
 - "ECDHE-RSA-AES256-SHA384"
 - "DHE-RSA-AES256-SHA384"
 - "ECDHE-RSA-AES256-SHA256"
 - "DHE-RSA-AES256-SHA256"
 - "HIGH"

**Comment by vikman90** [comment]
@BPJOHN1990 Maybe this previous answer helps you: [Remove AES128 & AES256 Encryption](https://groups.google.com/g/wazuh/c/pCUJPlmhiaE).

Best.
