### ISSUE TITLE
When an app uses PID 443 the Wazuh installation fails.

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-packages#1936]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.9 | Manager| Install | Ubuntu 20.04|

# Description

The Quickstart installation method shows unexpected behavior, when an app uses PID 443, and it is not the 443 port, the Wazuh installation fails.

## Steps to Reproduce

1. Download and run the Wazuh installation assistant. 
    > curl -sO https://packages.wazuh.com/4.3/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
    
    ![imagen](https://user-images.githubusercontent.com/3978434/202738653-fb4288fe-404d-40e1-86c2-ecbe71c68b98.png)
        
 2. Execute **_`netstat -tulpn`_** to check if there are any port 
    ![imagen](https://user-images.githubusercontent.com/3978434/202740295-3c659ac2-f788-4c88-997d-b3176014f29a.png)

    > **Note**: No used port but there is a 443 PID.

### Current result

1. Shows an ERROR with 443 port, but the problem is that you have a PID with the same port number. 

    ![imagen](https://user-images.githubusercontent.com/3978434/202738653-fb4288fe-404d-40e1-86c2-ecbe71c68b98.png)

   
### Expected result

1. Installation successful without any error.

--- 
# Workaround

1. Force the shutdown of the process with 443 PID. 
2. Execute the install command again. 
3. Finish the installation successfully. 
    
    ![imagen](https://user-images.githubusercontent.com/3978434/202756047-be87d73d-9d63-46cf-a1bf-e0c606139b16.png)

## Considerations 

1. We check ports used executing: 
    > - netstat -aon | findstr '443'
    > - netstat -aon | grep "443"
    > - netstat -tulpn | grep :443
    > - ss -lntup | grep -q 443
    > - lsof -i:443
2. Verified with Carlos Bordon.

**Comment by alberpilot** [comment]
Duplicated: https://github.com/wazuh/wazuh-packages/issues/1857
