### ISSUE TITLE
Error in Build legacy Linux packages

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh-packages#1944]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.4.0 | Agent | Install | centos5 |

During the checks for [Wazuh PR #15466](https://github.com/wazuh/wazuh/pull/15466/checks), the `Build legacy Linux x86_64 agent package` and the `Build legacy Linux i386 agent package` failed with the following outputs:

<details><summary>Build legacy Linux x86_64 agent package output</summary>

    ...
    + [[ no == \y\e\s ]]
    + cp /downloaded_tmp_specs/wazuh-agent.spec /build_wazuh/rpmbuild/SPECS/wazuh-agent-4.4.0.spec
    + cd /build_wazuh
    + tar czf /build_wazuh/rpmbuild/SOURCES/wazuh-agent-4.4.0.tar.gz wazuh-agent-4.4.0
    + '[' x86_64 = i386 ']'
    + '[' x86_64 = armv7hl ']'
    + '[' yes = no ']'
    + rpmbuild --define '_sysconfdir /etc' --define '_topdir /build_wazuh/rpmbuild' --define '_threads 4' --define '_release 0.commit16915ed.el5' --define '_localstatedir /var/ossec' --define '_debugenabl
    ed no' --target x86_64 -ba /build_wazuh/rpmbuild/SPECS/wazuh-agent-4.4.0.spec
    error: %changelog not in descending chronological order
    Building target platforms: x86_64
    Building for target x86_64
</details>

<details><summary>Build legacy Linux i386 agent package output</summary>

    ...
    + [[ no == \y\e\s ]]
    + cp /d_specs/wazuh-agent.spec /build_wazuh/rpmbuild/SPECS/wazuh-agent-4.4.0.spec
    + cd /build_wazuh
    + tar czf /build_wazuh/rpmbuild/SOURCES/wazuh-agent-4.4.0.tar.gz wazuh-agent-4.4.0
    + '[' i386 = i386 ']'
    + linux=linux32
    + '[' yes = no ']'
    + linux32 rpmbuild --define '_sysconfdir /etc' --define '_topdir /build_wazuh/rpmbuild' --define '_threads 4' --define '_release 0.commit16915ed.el5' --define '_localstatedir /var/ossec' --define '_de
    bugenabled no' --target i386 -ba /build_wazuh/rpmbuild/SPECS/wazuh-agent-4.4.0.spec
    error: %changelog not in descending chronological order
    Building target platforms: i386
    Building for target i386
</details>

After the last error of `changelog not in descending chronological order` the execution ends giving a failed check as the final result.

**Comment by rauldpm** [comment]
Duplicated from: https://github.com/wazuh/wazuh-packages/issues/1943
