### ISSUE TITLE
Update WPK package guide to create a custom package for Windows

### ISSUE THREAD

**Issue by DaveVG1** [wazuh/wazuh-packages#196]
Hi team,

We should improve our guide on how to create custom WPK packages and include the creation of WPK packages in Windows as it's a substantial different process compared to Linux.

Our current guide only includes the creation of Linux WPK packages: https://documentation.wazuh.com/current/user-manual/agents/remote-upgrading/create-custom-wpk.html

Regards.

David.

**Comment by alberpilot** [comment]
Hello team

  I transferred this issue in order to track it from @wazuh/cicd. @DFolchA, I assigned you this issue, we need to modify the documentation and include the new WPK creation tool. 

Thanks. BR, 
Alberto R

**Comment by DFolchA** [comment]
Hello team,

I have created a new page in the documentation with a guide of how to use the tools within wazuh-packages to create a  wpk automatically, I have also updated the actual page to include how to create a windows WPK manually.

Regards,
Daniel Folch.

**Comment by alberpilot** [comment]
PR done and merged.
