### ISSUE TITLE
The deploy variables names needs refactoring

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#197]
Hello team

  The variable names used in the deploy script are not accurate (https://github.com/wazuh/wazuh/blob/master/src/init/register_configure_agent.sh). We need to reach a new name convention for all of them, implement it, leaving support for the old ones and documenting it. 

We will put here the new proposal. This change affects the Windows MSI variables too. 

Best regards, 
Alberto R

**Comment by BraulioV** [comment]
Hi @alberpilot,

I've been working on this issue in this branch: [wazuh/refactor-deploy-variables](https://github.com/wazuh/wazuh/tree/refactor-deploy-variables). This commit https://github.com/wazuh/wazuh/commit/b64a5fbc80c00618628d175b1c00cb8885f030d0 includes the refactor of the variables, adding the new variables and a function that allows using the old and the new ones.

In addition, the function allows the usage of the old and new variables, but the new variables will have more preference if the user set both variables at the same time.

Here you can check some examples showing how you can deploy the agent automatically:
- Using the new variables:
```shellsession
# WAZUH_MANAGER="172.17.0.2" yum install wazuh-agent-3.9.3-1.x86_64.rpm -y
```
- Using the old variables:
```shellsession
# WAZUH_MANAGER_IP="172.17.0.2" WAZUH_AUTHD_PORT="22"  WAZUH_REGISTRATION_PORT="1566" yum install wazuh-agent-3.9.3-1.x86_64.rpm -y
```
- Using new and old variables:
```
# WAZUH_MANAGER="172.17.0.2" WAZUH_AUTHD_SERVER="172.17.0.116"  WAZUH_REGISTRATION_PORT="1566" yum install /packages/wazuh-agent-3.9.3-1.x86_64.rpm -y
```

Regards.

**Comment by BraulioV** [comment]
Hi team,

This is the result of the refactor. On the left, you can find the old variables, and on the right side the new one. In addition, you can also find the unchanged variables:
```
WAZUH_MANAGER_IP     ==> WAZUH_MANAGER
WAZUH_MANAGER_PORT   ==> not changed
WAZUH_PROTOCOL       ==> not changed
WAZUH_AUTHD_SERVER   ==> WAZUH_REGISTRATION_SERVER
WAZUH_AUTHD_PORT     ==> WAZUH_REGISTRATION_PORT
WAZUH_PASSWORD       ==> WAZUH_REGISTRATION_PASSWORD
WAZUH_NOTIFY_TIME    ==> WAZUH_KEEP_ALIVE_INTERVAL
WAZUH_TIME_RECONNECT ==> not changed
WAZUH_CERTIFICATE    ==> WAZUH_REGISTRATION_CA
WAZUH_PEM            ==> WAZUH_REGISTRATION_CERTIFICATE
WAZUH_KEY            ==> WAZUH_REGISTRATION_KEY
WAZUH_AGENT_NAME     ==> not changed
WAZUH_GROUP          ==> WAZUH_AGENT_GROUP
```
Regards.

**Comment by BraulioV** [comment]
Hi again team,

The rework of the Unix variables has been approved, so now, it's time to apply the same rework in the Windows package in order to unify all the variables.

Regards.

**Comment by DFolchA** [comment]
Hello team,

I have updated the documentation of the deployment variables with the new ones, the changes are in this branch:
https://github.com/wazuh/wazuh-documentation/tree/issue-wp-197-refactor-deploy-variables
Currently, I am investigating how to include the new variables into the MSI package while maintaining the old ones.
I am consulting the official WIX Toolset documentation as a reference:
https://wixtoolset.org/documentation/manual/v3/

Regards, 
Daniel Folch

**Comment by BraulioV** [comment]
Hi team, 

I've been working on the refactor of the Windows variables used to auto-deploy the agent. 

Here you can see what is the new name for each variable on Windows:
```
ADDRESS        => WAZUH_MANAGER
GROUP          => WAZUH_MANAGER_PORT
SERVER_PORT    => WAZUH_PROTOCOL
NOTIFY_TIME    => WAZUH_REGISTRATION_SERVER
TIME_RECONNECT => WAZUH_REGISTRATION_PORT" Secure
AUTHD_SERVER   => WAZUH_REGISTRATION_PASSWORD
AUTHD_PORT     => WAZUH_KEEP_ALIVE_INTERVAL
PROTOCOL       => WAZUH_TIME_RECONNECT
PASSWORD       => WAZUH_REGISTRATION_CA
CERTIFICATE    => WAZUH_REGISTRATION_CERTIFICATE
PEM            => WAZUH_REGISTRARTION_KEY
KEY            => WAZUH_AGENT_NAME
AGENT_NAME     => WAZUH_AGENT_GROUP
```
For now, installing and register the agent works fine but it needs further testing. You can see the changes in these two commits:
- https://github.com/wazuh/wazuh/pull/3708/commits/2c3b3e439c82268e7acc0a80ba2c65632524a31d
- https://github.com/wazuh/wazuh/pull/3708/commits/02f620905cc3789bc403cb2ad212555931bfa23d

Regards.

**Comment by BraulioV** [comment]
Hi again team,

Today I've been testing the introduced changes in the MSI installer. Here you can find the applied fixes:
- https://github.com/wazuh/wazuh/commit/daeab82a2a8b3e15fd0c573d05ac2752c5c739e4. Removed the old variables from the `customActions` with the new variables.
- https://github.com/wazuh/wazuh/commit/4ca6680a830a94c8ee5023750349d8ee4dcebe7b. This commit allows the package to edit the `ossec.conf` file using the old and the new variables.

Regards.

**Comment by BraulioV** [comment]
Closed by https://github.com/wazuh/wazuh-documentation/pull/1588 and https://github.com/wazuh/wazuh/pull/3708.
