### ISSUE TITLE
Enable debug packages

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-packages#201]
Hi team,

In this PR https://github.com/wazuh/wazuh-packages/pull/139, we added a new parameter to build packages using the flag `DEBUG=1` from the Makefile of the wazuh/wazuh repository. This allows us to build packages with debug symbols for testing purpose. 

But, all of this isn't enough. For RPM packages we must create `debuginfo` packages and install them alongside the wazuh-xxxxx rpm package. The `debuginfo` packages contain the debugging symbols of the binaries, so to debug the binaries with `gdb` for example, we must install these packages too.

Debian case is a bit different. In Debian, we are using this "flag": https://github.com/wazuh/wazuh-packages/blob/cd45a4c4472202459605d0f0208c1de36845fc4c/debs/SPECS/3.9.3/wazuh-manager/debian/rules#L115-L116
that disables/removes the debugging symbols from the binaries included in the package.

To add the debugging symbols of the binaries, we have two options:
1. Tag the package as a debug package using `override_dh_strip`:
    ```Makefile
    override_dh_strip:
        dh_strip --dbg-package=wazuh-agent
    ```
2. Remove these lines from the `rules` file:
    ```Makefile
    override_dh_strip:
        dh_strip --no-automatic-dbgsym
    ```
    And let the Makefile decide if the package must contain debugging symbols or not.

Regards,
Braulio.

**Comment by BraulioV** [comment]
Hi team, 

I've added the changes to build packages with debugging symbols for .deb packages. Here you can see the changes: https://github.com/wazuh/wazuh-packages/commit/b50b54d90e7579eca2ef4cae9a9483e129ee135b. 
This will remove the line https://github.com/wazuh/wazuh-packages/blob/b50b54d90e7579eca2ef4cae9a9483e129ee135b/debs/SPECS/3.9.3/wazuh-manager/debian/rules#L116 to allow us to keep the debugging symbols of the binaries from the package after building with the flag `DEBUG=yes`.

Regards.

**Comment by BraulioV** [comment]
Hi team,

Building RPM packages that contain the installation files and their debugging symbols isn't possible since `rpm 4.2`. So, to add the debug symbols from each binary, it is necessary to create and install a `debuginfo` package. More info at: https://docs.fedoraproject.org/en-US/packaging-guidelines/Debuginfo/. So, if you want to debug a binary using `gdb` you must install the packages `wazuh-xxxxx` and `wazuh-xxxxx-debuginfo`.

To generate these packages, I have to create a new `%build` section in the RPM specs and move the `make` lines to this section. This will tell to rpm how the binaries are built. Also, I added at the end of the `%install` section a new line to execute the `find-debuginfo.sh` script in order to correctly generate the `debuginfo` package.

Also, I've introduced some changes to the Dockerfile's entrypoint to generate these packages only and only if you execute the script using `-d` parameter.

Regards.

**Comment by tellison** [comment]
Just as a heads-up, many descriptions of the strip problem also report possibility of overriding [`dh_shlibdeps`](https://man7.org/linux/man-pages/man1/dh_shlibdeps.1.html) if private libraries are removed during packaging. I don't think we have that problem, but mentioning it here in case it comes up later.
