### ISSUE TITLE
`securityadmin.sh` tool will be deprecated in Opensearch v3

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#2029]
Based on https://github.com/opensearch-project/security/issues/1755, we need to plan the `securityadmin.sh` tool deprecation within our custom tools and documentation. 

## Tasks
- Analyze the impact (to expand).

**Comment by sultanovich** [comment]
One point to keep in mind if the tools are used to generate results is that they now have a banner included.

* In Opensearch 2.4.1
```
[root@wazuh-indexer-0 wazuh-indexer]# bash ./plugins/opensearch-security/tools/hash.sh -p Password
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
$2y$12$6s./ByazGHc.Mb7u3d1mReei7A7hDYyHdIy5t96JfA/7z0m67JFoG
[root@wazuh-indexer-0 wazuh-indexer]#
```

* Before Opensearch 2.4.1
```
[root@wazuh-indexer-0 wazuh-indexer]# bash ./plugins/opensearch-security/tools/hash.sh -p Password
$2y$12$6s./ByazGHc.Mb7u3d1mReei7A7hDYyHdIy5t96JfA/7z0m67JFoG
[root@wazuh-indexer-0 wazuh-indexer]#
```

**Comment by gdiazlo** [comment]
We will evaluate this when the next major version of OpenSearch gets a release date in their release plan. I'll close this as there will be more stuff to review, and we will open an issue to review all the breaking changes.
