### ISSUE TITLE
Installation Assistant Builder doesn't give error when curl fails

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh-packages#2031]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.4.0 | Installation Assistant | Building | Every OS |

The `curl` command used in the script `builder.sh` to recover function `dist-detect` from https://github.com/wazuh/wazuh may fail because of a self-signed certificate in raw.githubusercontent.com, for example. When it does, function `dist_detect()` at `wazuh-install.sh` is empty, but no error is shown. When the Installation Assistant is used, an error appears.

Code to recover the function from github:
```
## dist-detect.sh
    echo "function dist_detect() {" >> "${output_script_path}"
    curl -s "https://raw.githubusercontent.com/wazuh/wazuh/${source_branch}/src/init/dist-detect.sh" | sed '/^#/d' >> "${output_script_path}"
    echo "}" >> "${output_script_path}"
```

Curl error(for example):
```
[verdx@pop-os unattended_installer]$ curl "https://raw.githubusercontent.com/wazuh/wazuh/4.4/src/init/dist-detect.sh"
curl: (60) SSL certificate problem: self-signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Error in `wazuh-install.sh`:
```
[verdx@pop-os unattended_installer]$ bash wazuh-install.sh 
wazuh-install.sh: line 2708: syntax error near unexpected token `}'
wazuh-install.sh: line 2708: `}'
```

### Expected behaviour
Every `curl` to an outside web should be checked and give an error or at least warning if it reports an error.

**Comment by davidcr01** [comment]
# Update Report

## Research

This problem seems a cert issue. I could not reproduce the reported issue, but I can test the behavior with a curl to the Wazuh dashboard app, which returns the same error.

```
root@vagrant:/home/vagrant# curl https://localhost
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
root@vagrant:/home/vagrant#
```

:red_circle: Some failed solutions have been tested without success:
- Update the certificates with `sudo update-ca-certificates`
- Installing `ssl-certs` package.
- Installing `ca-certificates` package. 

## Next steps

After adding a check to that `curl` command, I should discuss with the team whether to add the `--insecure` option to ignore the certificate check. This could be done as the URL is to our GitHub repository, so we could assume it is a safe URL.

**Comment by davidcr01** [comment]
# Update Report 

## Meetings

After discussing the issue mentioned in the previous report, the team and I decided not to add the `--insecure` (or `-k`) option to the curl. It is true that the `curl` command fetches a resource from our repository, but it is unsafe not to check the certificates of the site. 
This modification could give rise to "Man in the Middle" attacks.

With this, the development would be to add a new function or check that tested the URL of the `dist-detect.sh` script before fetching it.

## Development

A new function, `checkDistDetectURL` is added in the `builder.sh` file, this function:
- Fetches de URL silently.
- Retries the `curl` command if a transient error is fetched.
- Retries the `curl` command if a "connection refused" error is fetched
- If an error is produced, the script exits with an error message.

## Validation

Some checks have been done to test the function:

:green_circle: Success case: the URL is correct and no error is fetched
```
+ checkDistDetectURL
+ retries=0
+ eval 'curl -s -o /dev/null '\''https://raw.githubusercontent.com/wazuh/wazuh/4.4/src/init/dist-detect.sh'\'' --retry 5 --retry-delay 5 --max-time 300 --fail'
++ curl -s -o /dev/null https://raw.githubusercontent.com/wazuh/wazuh/4.4/src/init/dist-detect.sh --retry 5 --retry-delay 5 --max-time 300 --fail
+ e_code=0
+ '[' 0 -eq 7 ']'
+ [[ 0 -eq 12 ]]
+ '[' 0 -ne 0 ']'
+ echo Continue...
Continue...
```
:red_circle: Failure case: the URL is incorrect or an error is generated (the URL is not correct)

```
+ checkDistDetectURL
+ retries=0
+ eval 'curl -s -o /dev/null '\''https://raw.githubusercontent.com/wazuh/wazu/4.4/src/init/dist-detect.sh'\'' --retry 5 --retry-delay 5 --max-time 300 --fail'
++ curl -s -o /dev/null https://raw.githubusercontent.com/wazuh/wazu/4.4/src/init/dist-detect.sh --retry 5 --retry-delay 5 --max-time 300 --fail
+ e_code=22
+ '[' 22 -eq 7 ']'
+ [[ 0 -eq 12 ]]
+ '[' 22 -ne 0 ']'
+ echo -e 'Error: Could not get the dist-detect.sh file. '
Error: Could not get the dist-detect.sh file. 
+ exit 1
```
