### ISSUE TITLE
The variables `adminpem`and `adminkey` are not being correctly set on `wazuh-passwords-tool.sh`

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#2033]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.4.0 | `wazuh-passwords-tool.sh`| Change passwords | OS version |

***Note: this issue is already present in 4.3.x***

We found that the `wazuh-passwords-tool.sh` script fails when using a different path for the admin certificate and key, other than `/etc/wazuh-indexer/certs/admin.pem` and `/etc/wazuh-indexer/certs/admin.key`.

If we use a different path but the files `/etc/wazuh-indexer/certs/admin.pem` and `/etc/wazuh-indexer/certs/admin.key` exist, the script uses those files:

```
[root@amazon2 vagrant]# ./wazuh-passwords-tool.sh -c /home/vagrant/admin.pem -a
11/01/2023 11:57:19 INFO: Wazuh API admin credentials not provided, Wazuh API passwords not changed.
11/01/2023 11:57:27 INFO: The password for user admin is trX*Q0P341Ibx+DeA?oT1OB3C*gfojDt
11/01/2023 11:57:27 INFO: The password for user kibanaserver is cNd363fhE0mrlTow1?qtxJz6PJzsm5X1
11/01/2023 11:57:27 INFO: The password for user kibanaro is SnYoQXrJk*hJSOlR?9LAw0VLR4*SRle.
11/01/2023 11:57:27 INFO: The password for user logstash is GTHmQlUJJj0fNiR*6??iggby3ndxZlch
11/01/2023 11:57:27 INFO: The password for user readall is ?JGsg3lK*AuilGc2w2QCgfH1bP8E+thw
11/01/2023 11:57:27 INFO: The password for user snapshotrestore is qnfjRw?5eI+j9TZsu222RJ2mjmzVw0Lb
11/01/2023 11:57:27 WARNING: Wazuh indexer passwords changed. Remember to update the password in the Wazuh dashboard and Filebeat nodes if necessary, and restart the services.
```

If we use a different path and those files do not exist, then the script fails indicating that we need to specify the path:

```
[root@amazon2 vagrant]# mv /etc/wazuh-indexer/certs/admin.pem /home/vagrant/admin.pem
[root@amazon2 vagrant]# ./wazuh-passwords-tool.sh -c /home/vagrant/admin.pem -a
11/01/2023 11:57:58 INFO: Wazuh API admin credentials not provided, Wazuh API passwords not changed.
11/01/2023 11:58:04 ERROR: No admin certificate indicated. Please run the script with the option -c <path-to-certificate>.
```

This error comes from the following lines:
https://github.com/wazuh/wazuh-packages/blob/79815b296658de20bb2f7f7bc773b7bb132a9cd8/unattended_installer/passwords_tool/passwordsFunctions.sh#L361-L375

We need to define the default path as a variable and change that variable if the corresponding flag is used and then change the conditional in those lines:

```
    if [[ ! -f  "${adminpem} ]]; then
        common_logger -e "No admin certificate indicated. Please run the script with the option -c <path-to-certificate>."
        exit 1;
    fi

    if [[ ! -f  "${adminkey} ]]; then
        common_logger -e "No admin certificate key indicated. Please run the script with the option -k <path-to-key-certificate>."
        exit 1;
    fi

```

**Comment by davidcr01** [comment]
## Update Report

### Research

The research of @DFolchA was very complete. Besides, I noticed that the `admin.key` file is no longer used. In the latest documentation is not mentioned https://documentation.wazuh.com/4.2/user-manual/certificates.html and in the cert-tool the created key is `admin-key.pem `and not `admin.key`.
https://github.com/wazuh/wazuh-packages/blob/79815b296658de20bb2f7f7bc773b7bb132a9cd8/unattended_installer/cert_tool/certFunctions.sh#L58-L65

Because of this, the check of the `admin.key` will be removed.

### Development

To aboard this problem, the steps to follow are:
- Initialize the `adminkey` and `adminpem` to the default values. This action will be performed in the `passwordVariables.sh`.
- If the user indicates another path for these files, the variables will change their values. This is already implemented in the code.
- In the `passwords_readAdmincerts` function, the checks of the files will be over the variables and not over the hardcoded path.

**Comment by davidcr01** [comment]
# Update Report

## Research

After doing the above development, I noticed the Installation Assistant uses the `adminpem` and `adminkey` variables, which are now defined in the `passwordsVariables.sh`. This change makes the Installation Assistant not know the value of these variables.

## Development

To solve this issue, I created a new file inside the `common_functions` folder, called `commonVariables.sh`, which should contain all the common variables used in the different tools.

For now, this file contains the following lines:
```
adminpem="/etc/wazuh-indexer/certs/admin.pem"
adminkey="/etc/wazuh-indexer/certs/admin-key.pem"
```

**Comment by davidcr01** [comment]
# Update Report

Here are some manual tests with the latest changes:

:green_circle: Install the Wazuh indexer
<details><summary>Show log</summary>
```
root@ubuntu-focal:/home/vagrant# bash wazuh-install.sh -u
14/02/2023 09:20:09 INFO: Starting Wazuh installation assistant. Wazuh version: 4.5.0
14/02/2023 09:20:09 INFO: Verbose logging redirected to /var/log/wazuh-install.log
14/02/2023 09:20:11 INFO: Wazuh dashboard not found in the system so it was not uninstalled.
14/02/2023 09:20:11 INFO: Removing Wazuh manager.
14/02/2023 09:20:23 INFO: Wazuh manager removed.
14/02/2023 09:20:23 INFO: Removing Wazuh indexer.
14/02/2023 09:20:28 INFO: Wazuh indexer removed.
14/02/2023 09:20:28 INFO: Removing Filebeat.
14/02/2023 09:20:32 INFO: Filebeat removed.
root@ubuntu-focal:/home/vagrant# bash wazuh-install.sh -wi node-1 -i
14/02/2023 09:21:09 INFO: Starting Wazuh installation assistant. Wazuh version: 4.5.0
14/02/2023 09:21:09 INFO: Verbose logging redirected to /var/log/wazuh-install.log
14/02/2023 09:21:11 WARNING: Hardware and system checks ignored.
14/02/2023 09:21:22 INFO: Wazuh development repository added.
14/02/2023 09:21:22 INFO: --- Wazuh indexer ---
14/02/2023 09:21:22 INFO: Starting Wazuh indexer installation.
14/02/2023 09:22:15 INFO: Wazuh indexer installation finished.
14/02/2023 09:22:15 INFO: Wazuh indexer post-install configuration finished.
14/02/2023 09:22:15 INFO: Starting service wazuh-indexer.
14/02/2023 09:22:44 INFO: wazuh-indexer service started.
14/02/2023 09:22:44 INFO: Initializing Wazuh indexer cluster security settings.
14/02/2023 09:22:47 INFO: Wazuh indexer cluster initialized.
14/02/2023 09:22:47 INFO: Installation finished.
root@ubuntu-focal:/home/vagrant# 
```
</details>

:green_circle: 
<details><summary>Show log</summary>
```

```
</details>

:green_circle: 
<details><summary>Show log</summary>
```

```
</details>

:green_circle: 
<details><summary>Show log</summary>
```

```
</details>

:green_circle: 
<details><summary>Show log</summary>
```

```
</details>

:green_circle: 
<details><summary>Show log</summary>
```

```
</details>


:green_circle: 
<details><summary>Show log</summary>
```

```
</details>
