### ISSUE TITLE
OpenJDK Version Update

### ISSUE THREAD

**Issue by giga1699** [wazuh/wazuh-packages#2044]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.10-4311 | Manager/API | Install | Ubuntu 22.04 |

When installing on a single server with the install.sh script (Jan 1, 2023 install date), the wazuh-indexer includes a bundled version of OpenJDK 15.0.1. It is installed at /usr/share/wazuh-indexer/jdk/.

There are multiple security advisories for OpenJDK 15.0.1. Looking at the associated CVEs, there are many that do not list version 15 even though scans and advisories say that 15.0.1 is affected.

Attempting to upgrade to OpenJDK 17.0.5+8 package from Adoptium caused the server to no longer function properly. There were numerous Java errors related to what I believe was security manager. It seems this may be patched in 4.4 based on #1844.

Downloading OpenJDK 11.0.17+8 package from Adoptium was successful with the following process:

> cd /tmp
> wget https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.17%2B8/OpenJDK11U-jdk_x64_linux_hotspot_11.0.17_8.tar.gz
> tar xvzf OpenJDK11U-jdk_x64_linux_hotspot_11.0.17_8.tar.gz
> cd /usr/share/wazuh-indexer/
> cp -r /tmp/jdk-11.0.17+8 ./jdk-new
> chown -R wazuh-indexer:wazuh-indexer jdk-new/
> chmod -R o-r jdk-new
> chmod -R o-x jdk-new
> service wazuh-indexer stop
> mv jdk jdk-old
> mv jdk-new jdk
> service wazuh-indexer start`

Once 'jdk-old' was removed, scans no longer show a vulnerable version of Java installed on the system.

It appears as though OpenSearch is having a conversation about using LTS versions of Java based on this issue:  https://github.com/opensearch-project/opensearch-build/issues/74

I haven't been able to find if wazuh is pulling from elastic.co, or OpenSearch github for the indexer packages, but having a fully patched Java version (preferably a LTS release) would be beneficial in newer releases.

While the embedded JDK isn't terribly hard to overwrite, I don't have a good set of tests to ensure that the system is operating the same under 11 as it was under 15.

**Comment by DFolchA** [comment]
Hello,

Thank you for reporting this, this vulnerability will be solved in the next release for wazuh-indexer 4.4.0 which is based in opensearch 2.4.1. This version uses OpenJDK 17.0.5.

```
[root@amazon2 vagrant]# cat /usr/share/wazuh-indexer/VERSION 
4.4.0
[root@amazon2 vagrant]# cat /usr/share/wazuh-indexer/jdk/release
IMPLEMENTOR="Eclipse Adoptium"
IMPLEMENTOR_VERSION="Temurin-17.0.5+8"
JAVA_VERSION="17.0.5"
JAVA_VERSION_DATE="2022-10-18"
LIBC="gnu"
...
```
You can see the version correspondence here:
https://github.com/wazuh/wazuh-packages/tree/4.4#distribution-version-matrix
