### ISSUE TITLE
Installation Assistant gives error `curl:command not found` during dependency installation

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh-packages#2048]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.4.0 | installation Assistant | Install | DEB OS |

When doing an installation using the Installation Assistant on a DEB system, if `curl` is not installed, it gives an error:

![image](https://user-images.githubusercontent.com/61122643/212963116-84054b74-bab2-41c4-abb8-6c3137134c8f.png)

It seems the installation of dependencies has started correctly but has called `curl` before having gotten to installing it, or it is not installing it correctly.

**Comment by DFolchA** [comment]
Solved in https://github.com/wazuh/wazuh-packages/pull/2063
