### ISSUE TITLE
`Could not resolve to a ProjectV2 with the number 3.`

### ISSUE THREAD

**Issue by jsoref** [wazuh/wazuh-packages#2108]
https://github.com/wazuh/wazuh-packages/actions/runs/4248103241/jobs/7386884256

```
Run actions/add-to-project@v0.4.0
Error: Request failed due to following response errors:
 - Could not resolve to a ProjectV2 with the number 3.
```

**Comment by rauldpm** [comment]
Hello @jsoref, thanks for the notice, we will fix this [GitHub Action workflow](https://github.com/wazuh/wazuh-packages/blob/master/.github/workflows/add-issues-to-projects.yml) as soon as possible.
