### ISSUE TITLE
Create new version of Filebeat module

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#2113]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| X.Y.Z-rev | Manager/API/Agent | Install/Upgrade/Remove | OS version |

There are some changes in the Filebeat module that are not included in the current 0.2 version:
https://github.com/wazuh/wazuh/commit/88c7df0c01d7207a12c6418516d00210e943f368
https://github.com/wazuh/wazuh/commit/d44fee5f16f02fc4ec2181c7448698a688067f58

We need to generate, test, and upload a new version of the module for future versions.

**Comment by davidjiglesias** [comment]
Already done in 0.3 version
