### ISSUE TITLE
Memory of RHEL 9 is not correctly detected by the Installation Assistant

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh-packages#2119]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3, 4.4, 4.5 | Installation Assistant | Red Hat Enterprise Linux 9 |

When running an All-in-one installation in a vagrant VM of RHEL 9 with `4096` of RAM and 2 cores, the installation stops with an error saying that the system does not meet the recommended minimum hardware requirements:

```
[vagrant@redhat9 ~]$ sudo bash wazuh-install.sh -a
08/03/2023 10:08:57 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.10
08/03/2023 10:08:57 INFO: Verbose logging redirected to /var/log/wazuh-install.log
08/03/2023 10:09:00 ERROR: Your system does not meet the recommended minimum hardware requirements of 4Gb of RAM and 2 CPU cores. If you want to proceed with the installation use the -i option to ignore these requirements.
```

This happens because the command used to check the available memory returns `3655` and the expected minimum value is `3700`:
```
[vagrant@redhat9 ~]$ free -m | awk '/^Mem:/{print $2}'
3655
```
https://github.com/wazuh/wazuh-packages/blob/daeeaa51b6d7f1c60d30ccbd69e413e414fca7b0/unattended_installer/install_functions/checks.sh#L301-L306

https://github.com/wazuh/wazuh-packages/blob/daeeaa51b6d7f1c60d30ccbd69e413e414fca7b0/unattended_installer/install_functions/checks.sh#L223-L228

This has only been tested on a vagrant VM, but if it comes from changes in RHEL 9 as an OS and its base use of memory, it would maybe be needed to reduce the checking number for memory to `3600`.

- [ ] Check if it happens on a real RHEL 9
- [ ] Investigate implications of reducing the necessary memory to `3600`

**Comment by davidcr01** [comment]
This issue goes to "On Hold" until we discuss modifying the minimum RAM requirement with the Core team.

**Comment by davidcr01** [comment]
After discussing this topic, we believe that lowering the RAM requirements to 3600MiB may be risky.
Taking into account that the `node.options` options specify half of the total RAM of the system, the Wazuh indexer will be set with approximately 1Gb of RAM, and this can provoke a malfunctioning of the Wazuh indexer.
