### ISSUE TITLE
Unable to build rpm using generate_rpm_package.sh to set custom path outside /var for CIS security requirements.

### ISSUE THREAD

**Issue by hayesb-emmanuel** [wazuh/wazuh-packages#2126]
|4.3.10|agent|build rpm|CentOS 8 and RedHat Enterprise 8.7|

Description
---------------
I am trying to deploy Wazuh Agent on a RedHat Enterprise 8.7 server with CIS Security - Server Level 1 configured. This excludes the ability to execute from /var, so I am attempting to use the instructions to rebuild the rpm with a custom path. I am using this documentation to do the steps ...
https://documentation.wazuh.com/current/development/packaging/generate-rpm-package.html

Environment
---------------
I have attempted to do this on a clean install of RedHat Enterprise 8.7 fully patched with Developer Tools and docker installed, and re-tried on CentOS 8 clean install with Developer Tools and docker installed.

Output (Error Specific)
--------------------------
make[2]: Leaving directory `/root/rpmbuild/BUILD/libarchive-3.1.2'
make[1]: Leaving directory `/root/rpmbuild/BUILD/libarchive-3.1.2'
make[2]: *** [check-TESTS] Error 1
make[1]: *** [check-am] Error 2
make: *** [check] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.OnJUpu (%check)
    InstallSourcePackage at: psm.c:244: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root

RPM build errors:
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    user mockbuild does not exist - using root
    group mockbuild does not exist - using root
    Bad exit status from /var/tmp/rpm-tmp.OnJUpu (%check)
Error: building at STEP "RUN curl -O https://packages.wazuh.com/utils/libarchive/libarchive-3.1.2-12.el7.src.rpm &&     rpmbuild --rebuild libarchive-3.1.2-12.el7.src.rpm && rpm -Uvh /root/rpmbuild/RPMS/x86_64/* --nodeps && rm -rf libarchive-*": while running runtime: exit status 1

Full Output Attached
---------------------------
[full-output.txt](https://github.com/wazuh/wazuh-packages/files/10944533/full-output.txt)

**Comment by hayesb-emmanuel** [comment]
I have also tried pulling v4.3.6 and v4.3.8 with the same results

**Comment by hayesb-emmanuel** [comment]
Thank you for looking into this, appreciate your help!

**Comment by jnasselle** [comment]
Hi @hayesb-emmanuel,

After a deeper analysis, it was found that the current situation is related to Centos8/RHEL8 running `podman` as `docker` (installing `docker` installs `podman-docker`)
Please check if you are effectively under this condition. This can be easily verified by checking `docker --version` output. For example, on Centos 8

```
[root@centos8 vagrant]# docker --version
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
podman version 3.3.1
```

On the other hand, you can overcome this issue by generating RPM packages on other popular GNU/Linux OS like Ubuntu, Docker, or Amazon Linux, where the default `docker` package is a truly `docker` CLI.

**Comment by hayesb-emmanuel** [comment]
Confirmed, my CentOS and RedHat builds 100% installed podman-docker instead of docker when I told it to install the package. Thank you for researching this, I had no idea that it didn't install standard docker. 

I'll grab a copy of Ubuntu and try to build the RPM and follow up today that it's good or not.

**Comment by hayesb-emmanuel** [comment]
Pulled and built on Ubuntu 22.04 Server LTS and worked perfect. Thank you again for taking the time to isolate the issue, it was really helpful. 

To reiterate for others that check this thread, the issue was that CentOS 8 and Red Hat Enterprise 8.7 install podman-docker when you tell it to install docker. The incorrect docker distribution was leading to my errors.
