### ISSUE TITLE
Add SPECs for macOS Ventura

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-packages#2137]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.4.2 | Agent | Install | macOS Ventura|

Hello team, we need SPECS for this new SCA file:
PR - https://github.com/wazuh/wazuh/pull/16027
Branch - https://github.com/wazuh/wazuh/tree/macOS-Ventura-SCA

**Comment by DFolchA** [comment]
Closed with https://github.com/wazuh/wazuh-packages/pull/2148
