### ISSUE TITLE
deluser/delgroup should be called from purge, not remove

### ISSUE THREAD

**Issue by jsoref** [wazuh/wazuh-packages#214]
Currently 

`del*` is called for lots of conditions:
https://github.com/wazuh/wazuh-packages/blob/3615935c9c0ad10e4aebb91487a051c4b26a4ff7/debs/SPECS/3.1.0/wazuh-agent/debian/postrm#L7-L14

This is dead wrong and results in broken systems when one uninstalls and then reinstalls `wazuh-agent`.

`del*` should only be called for `purge` in debian systems.

**Comment by DFolchA** [comment]
Hello team,

I have been investigating this issue and how to solve it for future versions. I have implemented the requested changes an tested the new packages generated in:

Agent:
- upgrade a futures

- reinstall
- install + remove + install
- install + purge + install
- install + remove
- [ ] Ubuntu 18.04
- [ ] Ubuntu 16.04
- [ ] Ubuntu 14.04
- [ ] Debian 7
- [ ] Debian 8
- [ ] Debian 9 

Manager:
- [ ] Ubuntu 18.04
- [ ] Ubuntu 16.04
- [ ] Ubuntu 14.04
- [ ] Debian 7
- [ ] Debian 8
- [ ] Debian 9

**Comment by DFolchA** [comment]
Hello team,
I have been investigating this issue and how to implement this improvement for future versions of wazuh, I have moved the userdel and groupdel orders to the purge section of postrm.

I have conducted the following tests:
Agent

| Future upgrade    | Reinstall           | Install + Remove + Install        | Install + Purge + Install | Install + Remove|
|:--------------------|---------------------:|:-------------------:|:-------------------:|:-------------------:|
| <ul><li>- [ ] Ubuntu 18.04</li>|  <ul><li>- [ ] Ubuntu 18.04</li>| <ul><li>- [ ] Ubuntu 18.04</li>| <ul><li>- [ ] Ubuntu 18.04</li>| <ul><li>- [ ] Ubuntu 18.04</li>|
| <ul><li>- [ ] Ubuntu 16.04</li>|  <ul><li>- [ ] Ubuntu 16.04</li>| <ul><li>- [ ] Ubuntu 16.04</li>|<ul><li>- [ ] Ubuntu 16.04</li>| <ul><li>- [ ] Ubuntu 16.04</li>|
| <ul><li>- [ ] Ubuntu 14.04</li>|  <ul><li>- [ ] Ubuntu 14.04</li>| <ul><li>- [ ] Ubuntu 14.04</li>| <ul><li>- [x] Ubuntu 14.04</li>| <ul><li>- [x] Ubuntu 14.04</li>|
| <ul><li>- [ ] Debian 7</li>|  <ul><li>- [ ] Debian 7</li>| <ul><li>- [ ] Debian 7</li>| <ul><li>- [ ] Debian 7</li>| <ul><li>- [ ] Debian 7</li>|
| <ul><li>- [ ] Debian 8</li>|  <ul><li>- [ ] Debian 8</li>| <ul><li>- [ ] Debian 8</li>| <ul><li>- [ ] Debian 8</li>| <ul><li>- [ ] Debian 8</li>|
| <ul><li>- [ ] Debian 9</li>|  <ul><li>- [ ] Debian 9</li>| <ul><li>- [ ] Debian 9</li>| <ul><li>- [ ] Debian 9</li>| <ul><li>- [ ] Debian 9</li>|

Manager:

| Future upgrade    | Reinstall           | Install + Remove + Install        | Install + Purge + Install | Install + Remove|
|:--------------------|---------------------:|:-------------------:|:-------------------:|:-------------------:|
| <ul><li>- [ ] Ubuntu 18.04</li>|  <ul><li>- [ ] Ubuntu 18.04</li>| <ul><li>- [ ] Ubuntu 18.04</li>| <ul><li>- [ ] Ubuntu 18.04</li>| <ul><li>- [ ] Ubuntu 18.04</li>|
| <ul><li>- [ ] Ubuntu 16.04</li>|  <ul><li>- [ ] Ubuntu 16.04</li>| <ul><li>- [ ] Ubuntu 16.04</li>|<ul><li>- [ ] Ubuntu 16.04</li>| <ul><li>- [ ] Ubuntu 16.04</li>|
| <ul><li>- [ ] Ubuntu 14.04</li>|  <ul><li>- [ ] Ubuntu 14.04</li>| <ul><li>- [ ] Ubuntu 14.04</li>| <ul><li>- [ ] Ubuntu 14.04</li>| <ul><li>- [x] Ubuntu 14.04</li>|
| <ul><li>- [ ] Debian 7</li>|  <ul><li>- [ ] Debian 7</li>| <ul><li>- [ ] Debian 7</li>| <ul><li>- [ ] Debian 7</li>| <ul><li>- [ ] Debian 7</li>|
| <ul><li>- [ ] Debian 8</li>|  <ul><li>- [ ] Debian 8</li>| <ul><li>- [ ] Debian 8</li>| <ul><li>- [ ] Debian 8</li>| <ul><li>- [ ] Debian 8</li>|
| <ul><li>- [ ] Debian 9</li>|  <ul><li>- [ ] Debian 9</li>| <ul><li>- [ ] Debian 9</li>| <ul><li>- [ ] Debian 9</li>| <ul><li>- [ ] Debian 9</li>| 

Regards,
Daniel Folch
