### ISSUE TITLE
Improve error handling in case of not finding the base in the build_packages.sh script of Wazuh indexer and Wazuh dashboard

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-packages#2145]
## Description
The build_packages.sh script contemplates the possibility of building or not the necessary base for building the Wazuh indexer and Wazuh dashboard packages.

Currently, if the option of not building a new base is chosen, the process continues and then it gives an error when trying to build the package.

```console
cp /tmp/wazuh-dashboard-base-4.6.0-1-linux-x64.tar.xz ./
cp: cannot stat '/tmp/wazuh-dashboard-base-4.6.0-1-linux-x64.tar.xz': No such file or directory
```

This error can be confusing for any user who wants to build any of the packages

## Tasks

- [x] Add a validation so that if you choose not to build the base, the script will validate the existence of a base file in the `outdir` directory

## Validation

- [x] test so that the error in case the base does not exist is clear to the users

**Comment by vikman90** [comment]
Due to the nature of the issue, it seems that it corresponds to @wazuh/frontend.

**Comment by AlexRuiz7** [comment]
As for now, this is @wazuh/cicd responsibility.
