### ISSUE TITLE
Enhance deb packages to accurately display information in the Software Updater

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh-packages#2156]
Currently, when viewing the "Software Updater" in the Debian-based operating systems, the displayed information for some packages is inaccurate or incomplete. For example, as shown in the attached screenshots, the title for the "Wazuh agent" package is too long, and the technical description incorrectly states that the changelog is not supported. Additionally, there is no description provided in the "Description" tab.

To improve the user experience and ensure accurate information is displayed, we propose enhancing the deb packages for affected packages to properly display the title and description in the "Software Updater".

![image](https://user-images.githubusercontent.com/1523318/231708105-b6979d32-35ad-4fcf-be22-d71d1a004d12.png)

![image](https://user-images.githubusercontent.com/1523318/231708445-e333bb8a-12bd-48f5-9be3-ae08f857c595.png)

**Comment by lchico** [comment]
# Update
I researched a fix for the deb package description display issue in Software Updater, created a [branch](enhancement/2156-improve-how-deb-packages-display-information-in-the-software-updater) with the fix, and now I have pending testing.
