### ISSUE TITLE
Add lsof as a dependency of the unattended installer - Backport 4.4

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#2165]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
|4.4.2| Manager/API/Agent | Install/Upgrade/Remove | OS version |

We intend to bring the changes in this https://github.com/wazuh/wazuh-packages/pull/1951 to 4.4.

For this purpose, we have created the following PR:
https://github.com/wazuh/wazuh-packages/pull/2023

**Comment by teddytpc1** [comment]
Tests will be executed to validate changes.
