### ISSUE TITLE
Rename macOS `login item`

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#2199]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.4.3 | Agent | Install/Upgrade | macOS |

Related to: https://github.com/wazuh/wazuh-packages/issues/1917

Currently, the `login item` in macOS appears as `launcher.sh` we need to rename this so the users can more easily identify it.

![image](https://github.com/wazuh/wazuh-packages/assets/19505384/358dd778-bc62-4edc-bb91-c72fe816c081)

**Comment by verdx** [comment]
#### All updates on this issue are on the different PRs:
- https://github.com/wazuh/wazuh-packages/pull/2207
- https://github.com/wazuh/wazuh-documentation/pull/6122
- https://github.com/wazuh/wazuh/pull/17190
