### ISSUE TITLE
Improve generation process for DEB package

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh-packages#22]
The current script to build the Debian packages is too complex. 

Tasks to do:

- [x] Simplify the build script.
   - [x] Clean up the script.
   - [x] Improve the parameter handler.
   - [x] Remove all the unnecessary stuff to create a package. This means unnecessary dependencies and unnecessary code.
- [x] Build the packages using `debuild`.
- [x] Use Docker containers to build the packages.
- [x] Make a script/tool to build and prepare the environment.
- [x] Create the Dockerfiles to build i386 and x86_64 Debian packages.
- [x] Add compatibility for previous Wazuh versions. This means that the new tool to build the deb packages must be able to build all the Wazuh 3.x versions.
- [x] Testing.

**Comment by BraulioV** [comment]
Hi team,

I just add the new script to build the packages, the Dockerfiles to build amd64 and i386 packages, the new "specs" for the deb packages, including the 3.4.0 ones.

Everything is implemented in this branch [dev-improve-deb-generation](https://github.com/wazuh/wazuh-packages/tree/dev-improve-deb-generation).

Regards,
Braulio.

**Comment by BraulioV** [comment]
This issue is solved in #27.

Regards,
Braulio.
