### ISSUE TITLE
Test the agent installation on macOS 14

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-packages#2200]
- Parent issue: [#17148](https://github.com/wazuh/wazuh/issues/17148)

We need to check the agent package on macOS 14 when it's available.

The beta is expected to arrive on June 5th.

**Comment by lsayanes** [comment]
I downloaded the pkg file from the wazuh page:
https://packages.wazuh.com/4.x/macos/wazuh-agent-4.5.2-1.arm64.pkg 

<img width="662" alt="Captura de pantalla 2023-10-06 a la(s) 15 37 21" src="https://github.com/wazuh/wazuh-packages/assets/68856625/f5964cfa-ea57-4867-bb8c-801146f7fde7">

It was installed and worked correctly:
<img width="602" alt="Captura de pantalla 2023-10-06 a la(s) 15 39 18" src="https://github.com/wazuh/wazuh-packages/assets/68856625/a3e86531-fd99-434a-8a91-3f30d7c73955">

## log
**Agent**
```
2023/10/06 15:52:50 wazuh-syscheckd: INFO: Agent is now online. Process unlocked, continuing...
2023/10/06 15:52:50 rootcheck: INFO: Starting rootcheck scan.
2023/10/06 15:52:51 sca: INFO: Security Configuration Assessment scan finished. Duration: 70 seconds.
2023/10/06 15:52:51 wazuh-modulesd: INFO: Agent is now online. Process unlocked, continuing...
2023/10/06 15:52:52 wazuh-syscheckd: INFO: (6009): File integrity monitoring scan ended.
2023/10/06 15:52:52 wazuh-syscheckd: INFO: FIM sync module started.
```
**Manager**
![Captura de pantalla 2023-10-06 a la(s) 15 54 17](https://github.com/wazuh/wazuh-packages/assets/68856625/e7e009d7-f5ef-407c-a991-e0f7ab2b4d14)
