### ISSUE TITLE
Maintain production and numbered branches - `wazuh-packages`

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#2214]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| X.Y.Z-rev | Manager/API/Agent | Install/Upgrade/Remove | OS version |

The goals are:

- [x] Merge 4.4 into 4.5: https://github.com/wazuh/wazuh-packages/pull/2215
- [ ] Merge 4.5 into master: https://github.com/wazuh/wazuh-packages/pull/2219

**Comment by teddytpc1** [comment]
This issue will be continued in #2221.
