### ISSUE TITLE
Pkg info is not correctly updated in Solaris package generation

### ISSUE THREAD

**Issue by grg121** [wazuh/wazuh-packages#222]
Hello team,

We've detected some failures in the pkg info of Solaris packages that we should fix:

- https://github.com/wazuh/wazuh-packages/blob/master/solaris/solaris10/pkginfo#L7 the email should be changed to `info@wazuh.com`

- The `ARCH` parameter should change to SPARC when building for SPARC.

Currently, our packages for Solaris SPARC claim to be i386 and that should not happen.  

```
pkgadd -d wazuh-agent_v3.9.2-sol10-sparc.pkg

The following packages are available:

 1  wazuh-agent     Wazuh - Improved OSSEC agent for Intrusion Detection, File Integrity Monitoring, Policy Monitoring and Rootkits Detection.

                    (i386) 3.9.2

Is it correct that is i386 the package for Solaris Spark 10?
```

That should be checked during package generation.

**Comment by DFolchA** [comment]
Hello team, 

I have changed the pkginfo file so it includes the new email `info@wazuh.com`  and added a sed that changes the architecture before creating the package:

https://github.com/wazuh/wazuh-packages/blob/7e78d1e481fde9fc76a0bf5e7b8b71a11dc5cddc/solaris/solaris10/generate_wazuh_packages.sh#L166

Regards,
Daniel Folch
