### ISSUE TITLE
Maintain production and numbered branches - wazuh-packages

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#2221]
Main issue: https://github.com/wazuh/wazuh/issues/17285

The goals are:

- [x] [Merge 4.4.3 into 4.4](https://github.com/wazuh/wazuh-packages/pull/2222)
- [x] Update the latest released versions' date in 4.4
- [x] Merge 4.4 into 4.4.4
- [x] Merge 4.4 into 4.5.
- [x] Merge 4.5 into master.

**Comment by teddytpc1** [comment]
This issue is blocked by #17285. Core's PRs should be ready.
