### ISSUE TITLE
The RPM package is unable to install on Oracle Linux 9

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-packages#2223]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.4.3 | Manager | Install | Oracle Linux 9 |

## Platform setup

```shell
vagrant init oraclelinux/9 https://oracle.github.io/vagrant-projects/boxes/oraclelinux/9.json
vagrant up
vagrant ssh
```

## Installation command

```shell
sudo rpm --import https://packages.wazuh.com/key/GPG-KEY-WAZUH
wget https://packages.wazuh.com/4.x/yum/wazuh-manager-4.4.3-1.x86_64.rpm
sudo rpm -i wazuh-manager-4.4.3-1.x86_64.rpm
```

## Output

```
error: Failed dependencies:
        /sbin/service is needed by wazuh-manager-4.4.3-1.x86_64
```

**Comment by jnasselle** [comment]
Closed by #2257

**Comment by VinceBezzina** [comment]
So how do you install Wazuh agent on Oracle Linux 9 ?

**Comment by jnasselle** [comment]
Hi @VinceBezzina ,

This issue was solved in v4.4.5. You can install Wazuh Agent on Oracle Linux following the next documentation https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html

**Comment by VinceBezzina** [comment]
Thanks for the help. But mind that I am trying to install on Oracle Linux 9.
We tried this version https://packages.wazuh.com/4.x/yum/wazuh-agent-4.5.3-1.x86_64.rpm
I saw mention of a 4.6.0 version but could not find the rpm.

So the agent will install and will run, but the enable fails with this message
sudo systemctl enable wazuh-agent

Executing: /usr/lib/systemd/systemd-sysv-install enable wazuh-agent
Failed to execute /usr/lib/systemd/systemd-sysv-install: No such file or directory

Apparently in Oracle Linix 9
this program does not exist in the /usr/lib/systemd/ directory, but in the /usr/libexec/initscripts/ directory 
(https://github.com/wazuh/wazuh-packages/issues/1626)

But I could not follow the discussion through to find a solution, if there was one

**Comment by jnasselle** [comment]
Hi @VinceBezzina ,

You are right. In fact, there's an issue that points to the solution https://github.com/wazuh/wazuh/issues/18778. Basically, there's a dependency on chkconfig for enabling the service.

I'm going to triage the issue with the team to fix it.

Regards,
Nico

**Comment by VinceBezzina** [comment]
Awesome thanks

**Comment by VinceBezzina** [comment]
Wondering if there was an update. Have two systems waiting for this deployment.
