### ISSUE TITLE
Expiring Certs of Wazuh agent files at 14/06/2023

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-packages#2227]
##  Related issues / PRs
|Scope| Issue | PR |
|---|---|---|
|Packages|https://github.com/wazuh/wazuh-packages/issues/2227 | https://github.com/wazuh/wazuh-packages/pull/2228 |
|CICD|https://github.com/wazuh/wazuh-jenkins/issues/5260 |https://github.com/wazuh/wazuh-jenkins/pull/5262|
|Core| - | https://github.com/wazuh/wazuh/pull/17506| 
|Documentation| - | https://github.com/wazuh/wazuh-documentation/pull/6149 |

## Description
We have seen that different users are reporting that agent files have certificates that will expire on 14/06.

This shows an example of: C:\Program Files (x86)\ossec-agent\libgcc_s_dw2-1.dll

https://github.com/wazuh/wazuh/issues/17365

This one shows an example of C:\Program Files (x86)\ossec-agent\dbsync.dll

https://github.com/wazuh/wazuh/discussions/17294

Different behaviors are reported in each case, such as that Syscollector fails and no vulnerabilities are reported, as well as that the agent won't auto start at boot.

Could you please check it? Thank you in advance!

# Information 

- Wazuh version: 4.4.2
- Platform: Windows

**Comment by fcaffieri** [comment]
Test Finish :green_circle: 
https://github.com/wazuh/wazuh/pull/17506/checks 
https://ci.wazuh.info/view/Pull_requests/job/PR_wazuh/17615/
