### ISSUE TITLE
Investigate impact of expired sign certificates

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#2229]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.4.3-rev | Agent | Install/Upgrade/Remove | Windows |

As indicated in this [issue](https://github.com/wazuh/wazuh-packages/issues/2227) the certificates currently used to sign the MSI packages are about to expire, this issue is intended to investigate the impact of this on the packages that already use that signature.

**Comment by DFolchA** [comment]
## Update

After testing old Wazuh agent 3.0.0 packages that were signed with an expired certificate, we have determined that Windows still trusts the packages and does not show any SmartScreen popup or indicate that the developer is unknown.

This same behavior was reproduced when changing the date of the machine and using 4.4.3 Wazuh agent MSI packages.

This behavior is expected because the files were `timestamped` when they were signed and this way the system trusts them even if the certificate has expired due to being signed while the certificate was still valid.

Here there are some resources about this topic:
https://www.globalsign.com/en/blog/what-is-timestamping-how-does-it-work
https://www.digicert.com/blog/best-practices-timestamping
https://codesigningstore.com/what-happens-when-code-signing-certificate-expires
https://knowledge.digicert.com/generalinformation/INFO1119.html

**Comment by verdx** [comment]
# Review

The same test as @DFolchA has been done on Windows Server 2016. Wazuh version 3.0.0 has been used, which uses an expired certificate. When installing the package, no problem has been encountered and no message says the developer is unidentified or the certificate expired. The links @DFolchA has added have been reviewed and they make sense as to why no error is shown. 

Installation of the package: 

[Screencast from 06-12-2023 11:28:06 AM.webm](https://github.com/wazuh/wazuh-packages/assets/61122643/09889b7b-47a7-43d2-afbf-60709a29b012)
