### ISSUE TITLE
Adapt the Linux specs due to SCA refactor

### ISSUE THREAD

**Issue by Skeptor** [wazuh/wazuh-packages#224]
Due to the changes made in the refactoring of SCA https://github.com/wazuh/wazuh/pull/3286 the templates for SCA have been changed.

The commit https://github.com/wazuh/wazuh/pull/3286/commits/3728926ee9433d3b96a4ee3084ce5cbe43d84f3d contains the changes in the files `*.file` and `*.template`.

The commits https://github.com/wazuh/wazuh-ruleset/pull/406/commits/9843be07e5d3be6eb4952ab3239e9c4e07d35c47 and https://github.com/wazuh/wazuh-ruleset/pull/406/commits/8d7741eab22260ac7b79e82cd142ef29f126f74d contains the removed files and the refactor of debian policies. Now the policy `cis_debianlinux_7-8` has been divided in policies: `cis_debian7`, `cis_debian8` and `cis_debian9`

Regards.

**Comment by Skeptor** [comment]
Due to the changes made here https://github.com/wazuh/wazuh/issues/3249#issuecomment-513180012 the method to install the SCA policies must be different in the manager.

The policies that can be scanned in the manager are installed in the same way. But the rest of the policies must be installed as `.disabled` to prevent the manager from scanning them.

Also, the folder `ruleset/sca` must be replaced in the updates to remove the old policies.

Regards.

**Comment by BraulioV** [comment]
Hi team,

I'm currently working in this branch: [224-rework-sca-files](https://github.com/wazuh/wazuh-packages/tree/224-rework-sca-files). I made the following changes on the RPM specs:
- Added the new SCA files: (application, Amazon Linux, macOS, etc.)
- Apply the changes on how the SCA files are installed, disabling all the unnecessary files on the Wazuh Manager.
- Remove the old and incompatible SCA files from previous versions when upgrading.
- Remove the SCA files after uninstalling the package.

For now, I tested the fresh install, upgrade from previous versions, reinstall and remove, and everything worked fine. Now I have to replicate the changes on .deb packages.

Regards.

**Comment by BraulioV** [comment]
Hi team,

I've already added the changes to the Debian, RPM and macOS packages, including manager and agent packages. Here you can find the more relevant commits:
- 069345a9def07f5769ed26471d5f59fba5b2795f: Refactor the SCA logic in the wazuh-agent macOS package.
- 2f0c6309c780e259d8a3e7813916246764af0dcd: Refactor the SCA logic in the wazuh-agent deb package.
- c195d3c9f69f651aa5cc76bce4a24cce9d1a43ba: Refactor the SCA logic in the wazuh-agent RPM package.
- 0524656748837393cef53add39560d4ecef6fd64: Port the changes to v3.11.0.

Regards.
