### ISSUE TITLE
Update packages builder for wazuh app (plugins)

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-packages#2247]
## Description

From 4.6.0, we have adopted a new folder structure in the `wazuh-kibana-app` repo. The source code of the plugin is now inside the `plugins/main `folder, `package.json` file included.

These changes have collateral effects [packages builder scripts](https://github.com/wazuh/wazuh-packages/tree/4.6.0/wazuhapp), so they need to be updated.

Related issue: https://github.com/wazuh/wazuh-kibana-app/issues/5566

**Comment by Rebits** [comment]
### 03/07/2023
- Open: https://github.com/wazuh/wazuh-packages/pull/2249
- Pending upgrade ECR

**Comment by Rebits** [comment]
### 04/07/2023
- Built Kibana Container locally
- Blocked: Lack of permissions to perform ECR upgrade

**Comment by Rebits** [comment]
### 05/07/2023

- Detected error during packages creation: https://github.com/wazuh/wazuh-packages/issues/2251
- Mark issue as blocked

**Comment by Rebits** [comment]
### 06/07/2023
- New changes in https://github.com/wazuh/wazuh-packages/pull/2249 to update plugin path that produces reported error https://github.com/wazuh/wazuh-packages/issues/2252
- Mark as blocked until https://github.com/wazuh/internal-devel-requests/issues/75

**Comment by Rebits** [comment]
Successfully created kibana and dashboardapp. Moving issue to pending review

- DashboardApp: https://ci.wazuh.info/job/Packages_builder/154027/
- KibanaApp: https://ci.wazuh.info/job/Packages_builder/153961/

**Comment by davidjiglesias** [comment]
LGTM!
