### ISSUE TITLE
Lack of SCA files on RHEL8 with Wazuh-agent

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-packages#226]
Hello team,

We have detected that Wazuh agent package doesn't install SCA files on Red Hat 8 systems, all Wazuh versions with SCA are affected, below are the files:
```
Missing:
/var/ossec/ruleset/sca/system_audit_pw.yml
/var/ossec/ruleset/sca/system_audit_rcl.yml
/var/ossec/ruleset/sca/system_audit_ssh.yml
```

Regards.

**Comment by BraulioV** [comment]
Fixed in #230
