### ISSUE TITLE
SPECS for new SCA Debian Linux 12

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-packages#2280]
Create SPECS as needed for a new OS SCA

PR - https://github.com/wazuh/wazuh/pull/17565 Is ready to merge
Branch - https://github.com/wazuh/wazuh/tree/create-sca-policy-for-debian-linux-12

PLEASE confirm with @wazuh/threat-intel before merging.

**Comment by vikman90** [comment]
This is a subtask of https://github.com/wazuh/wazuh/issues/17325.

**Comment by vikman90** [comment]
PR https://github.com/wazuh/wazuh-packages/pull/2303 ready, blocked by https://github.com/wazuh/wazuh/pull/17565.

**Comment by mjcr99** [comment]
## Issue updates
**(15/12/2023)** - Opened PR with the requested changes to add Debian 12 SCA files. The PR has been tested, the resulting packages contain the new files as expected:

<details><summary>Manager</summary>

**Manager package build:** https://ci.wazuh.info/job/Packages_builder/176215

**Package installation:**
```
root@debian-12:/home/vagrant# dpkg -i wazuh-manager_4.7.2-1_amd64.deb 
Selecting previously unselected package wazuh-manager.
(Reading database ... 30470 files and directories currently installed.)
Preparing to unpack wazuh-manager_4.7.2-1_amd64.deb ...
Unpacking wazuh-manager (4.7.2-1) ...
Setting up wazuh-manager (4.7.2-1) ...
```

**SCA file found:**
```
root@debian-12:/home/vagrant# cat /var/ossec/ruleset/sca/cis_debian
cis_debian10.yml.disabled  cis_debian7.yml.disabled
cis_debian11.yml.disabled  cis_debian8.yml.disabled
cis_debian12.yml           cis_debian9.yml.disabled
```
</details>

<details><summary>Agent</summary>

**Agent package build:** https://ci.wazuh.info/job/Packages_builder/176216

**Package installation:**
```
root@debian-12:/home/vagrant# dpkg -i wazuh-agent_4.7.2-1_amd64.deb 
Selecting previously unselected package wazuh-agent.
(Reading database ... 30470 files and directories currently installed.)
Preparing to unpack wazuh-agent_4.7.2-1_amd64.deb ...
Unpacking wazuh-agent (4.7.2-1) ...
Setting up wazuh-agent (4.7.2-1) ...
```

**SCA file found:**
```
root@debian-12:/home/vagrant# ls /var/ossec/ruleset/sca
cis_debian12.yml
```
</details>
