### ISSUE TITLE
SPECS for new SCA Rocky Linux 8

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-packages#2281]
Create SPECS as needed for a new OS SCA

PR - https://github.com/wazuh/wazuh/pull/17784 Is ready to merge
Branch - https://github.com/wazuh/wazuh/tree/create-sca-policy-for-rocky-linux-8

PLEASE confirm with @wazuh/threat-intel before merging.

**Comment by vikman90** [comment]
This is a subtask of https://github.com/wazuh/wazuh/issues/13406.

**Comment by vikman90** [comment]
PR ready, blocked by https://github.com/wazuh/wazuh/pull/17784.
