### ISSUE TITLE
SPECS for new SCA Amazon Linux 2023

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-packages#2285]
Create SPECS as needed for a new OS SCA

PR - https://github.com/wazuh/wazuh/pull/17780 Is ready to merge
Branch - https://github.com/wazuh/wazuh/tree/create-sca-policy-for-amazon-linux-2023

PLEASE confirm with @wazuh/threat-intel before merging.

**Comment by vikman90** [comment]
This is a subtask of https://github.com/wazuh/wazuh/issues/15462.

**Comment by vikman90** [comment]
PR https://github.com/wazuh/wazuh-packages/pull/2303 ready, blocked by https://github.com/wazuh/wazuh/pull/17780.
