### ISSUE TITLE
Solaris 11 smf Manifest points to deleted script

### ISSUE THREAD

**Issue by ghdangang** [wazuh/wazuh-packages#2313]
|Wazuh 4.4.5|Install Agent |Action Rewrite smf manifest|Sparc|
|---|---|---|---|
| "v4.4.5"-"40413"| WAZUH_TYPE="agent" Install/ | Solaris 11.4.53.132.2 |

For whatever reasons the installer removes this directory
 
/var/ossec/installation_scripts

root@sol11:~# cd /var/ossec/
root@sol11:/var/ossec# ls installation_scripts/postinstall.sh
installation_scripts/postinstall.sh: No such file or directory
root@sol11:/var/ossec# ls installation_scripts/
installation_scripts/: No such file or directory

This results in the smf not restarting wazuh after reboot or smf restarts

Also the var/ossec/installation_scripts/postinstall.sh does not start or stop the wazuh agent

I have written a new manifest that worked for me 

cat wazuh-install.xml
<?xml version="1.0" ?>
<!DOCTYPE service_bundle
  SYSTEM '/usr/share/lib/xml/dtd/service_bundle.dtd.1'>
<service_bundle type="manifest" name="site/wazuh-install">
    <service version="1" type="service" name="site/wazuh-install">
        <dependency restart_on="none" type="service"
            name="multi_user_dependency" grouping="require_all">
            <service_fmri value="svc:/milestone/multi-user"/>
        </dependency>
        <dependent restart_on="none"
            name="wazuh-install_multi-user-server" grouping="optional_all">
            <service_fmri value="svc:/milestone/multi-user-server" />
        </dependent>
        <exec_method timeout_seconds="60" type="method" name="refresh"
                     exec="var/ossec/bin/wazuh-control restart"/>
        <exec_method timeout_seconds="60" type="method" name="start"
                     exec="var/ossec/bin/wazuh-control start"/>
        <exec_method timeout_seconds="60" type="method" name="stop"
                     exec="var/ossec/bin/wazuh-control stop"/>
         <property_group type="framework" name="startd">
                     <propval type="astring" name="duration" value="transient"/>
        </property_group>
        <instance enabled="true" name="default"> </instance>
    </service>
</service_bundle>

**Comment by jnasselle** [comment]
Hi @ghdangang ,

Thanks for reporting this bug. This behavior was currently reported in https://github.com/wazuh/wazuh-packages/issues/2238 and treated there.

Closing this issue as a duplicate.
Regards,
Nico
