### ISSUE TITLE
Wazuh dashboard show errors related to SSL in 4.4.5

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-packages#2326]
## Description

The following log messages have been found in the [v4.4.5 AMI](https://github.com/wazuh/wazuh/issues/18115#issuecomment-1658992386) testing:

```
jul 31 17:58:01 wazuh-server opensearch-dashboards[2478]: {"type":"error","@timestamp":"2023-07-31T17:58:01Z","tags":["connection","client","error"],"pid":2478,"level":"error","error":{"message":"140249625483136:error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 48\n","name":"Error","stack":"Error: 140249625483136:error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 48\n","code":"ERR_SSL_TLSV1_ALERT_UNKNOWN_CA"},"message":"140249625483136:error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 48\n"}

```

This message is similar to others obtained previously but with a different format, probably due to an OpenSearch change. It is necessary to investigate these messages and establish the actions to be taken.
Similar  error than reported https://github.com/wazuh/wazuh-packages/issues/2106

## Tasks

- [ ] Analyze each message obtained (OVA/AMI)
- [ ] Open an issue for each error and apply the necessary fix if necessary

## Validation

- [ ] The OVA/AMI are built without these error messages or it is validated that they can show them

**Comment by rauldpm** [comment]
Related:
  - https://github.com/wazuh/wazuh-packages/issues/2445
  - https://github.com/wazuh/wazuh-packages/issues/2106

This error will be tracked in those issues
