### ISSUE TITLE
Bump Wazuh dashboard app to OpenSearch 2.8.0

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2393]
## Description

The generation of the Wazuh dashboard app package fails in the 4.6.0 branch due to outdated dependencies with respect to OpenSearch 2.8.0, it is necessary to adapt the repository.

- https://ci.wazuh.info/view/Packages/job/Packages_builder/163478/console

```
19:09:11  + mkdir -p plugin_platform_source/plugins
19:09:11  + mv plugin_platform_source /tmp/source
19:09:11  + install_dependencies
19:09:11  + cd /tmp/source
19:09:11  + change_node_version '>=14.20.1' '<19'
19:09:11  ++ node -v
19:09:11  + installed_node_version=v10.24.1
19:09:11  + node_version='>=14.20.1'
19:09:11  + n '>=14.20.1'
19:09:11    Error: invalid version '>=14.20.1'
```

## Tasks

- [x] Adapt Wazuh dashboard app to 2.8.0

**Comment by davidjiglesias** [comment]
LGTM!
