### ISSUE TITLE
Remove all the scripts from /usr/share/wazuh-*

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh-packages#24]
Hi team, 

Packages add some scripts to the directory `/usr/share/wazuh-manager` and `/usr/share/wazuh-agent`, to add some information to the `ossec.conf`, etc.

This must be created in a new directory inside of the _installation dir_. For example, in `/var/ossec/tmp`.

**Comment by BraulioV** [comment]
Related issue: #16

**Comment by BraulioV** [comment]
Hi, 

this has been already done for the RPM packages.

**Comment by BraulioV** [comment]
Hi again, 

this has been already done for the .deb packages in these commits 6ddad697cedb476e80f0fc5755cc5bb3900a996e and f5d051f003b1c11fb5ec5b81365e022a47abacd0. There's a deeper explanation of the changes in #23.

Regards,
Braulio
