### ISSUE TITLE
The Wazuh installation assistant shows the Node version when installing the components

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2413]
## Description

Apparently, with OpenSearch bump 2.8.0, when using the binary the Node version used is displayed on the screen, this has been detected when using the Wazuh installation assistant, which shows the following:

```
01/09/2023 17:30:46 INFO: wazuh-dashboard service started.
v16.20.0
01/09/2023 17:31:55 INFO: Initializing Wazuh dashboard web application.
```

When using the binary in an OpenSearch 2.8.0 install, it is possible to see it in the command output:

```
[root@centos7 a]# /usr/share/wazuh-dashboard/bin/opensearch-dashboards -h
v16.20.0
node:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
```

This has been confirmed by @Tostti when looking at journalctl output

```
[root@localhost vagrant]# journalctl -u opensearch-dashboards
-- Logs begin at Fri 2023-09-01 18:29:29 UTC, end at Fri 2023-09-01 18:37:15 UTC. --
Sep 01 18:36:29 localhost.localdomain systemd[1]: Started "OpenSearch Dashboards".
Sep 01 18:36:29 localhost.localdomain opensearch-dashboards[3267]: v16.20.0
```

It is necessary to silence this output during the installation of the components using the Wazuh installation assistant

## Tasks

- [x] Silence the Node version when using the Wazuh installation assistant

## Validation

- [x] When using the Wazuh installation assistant, the Node version used is not shown

## Related:

- https://github.com/wazuh/internal-devel-requests/issues/194
- https://github.com/wazuh/wazuh-packages/issues/2391
- https://github.com/wazuh/wazuh-packages/issues/2392

**Comment by davidcr01** [comment]
# Update Report

## Workaround

The workaround is to perform an step-by-step installation using the Wazuh Installation Assistant until reaching the Wazuh dashboard installation and debug the related code. Probably, the command that is needed to be silenced must be the following line:
https://github.com/wazuh/wazuh-packages/blob/a2d519396bf323b28d652d24b58c754e768b6e8c/unattended_installer/install_functions/installMain.sh#L327

**Comment by davidcr01** [comment]
# Update Report

A new change has been added to silence an output of the `grep` command while fetching the Dashboard name. 
The command was: `if [ -n "${dashname}" ] && ! echo "${dashboard_node_names[@]}" | grep -w -q "${dashname}";
`
The output was:

```console
04/09/2023 15:29:52 INFO: Starting Wazuh installation assistant. Wazuh version: 4.6.0
04/09/2023 15:29:52 INFO: Verbose logging redirected to /var/log/wazuh-install.log
04/09/2023 15:29:58 INFO: Wazuh web interface port will be 443.
04/09/2023 15:30:03 INFO: Wazuh development repository added.
dashboard
04/09/2023 15:30:03 INFO: --- Wazuh dashboard ----
04/09/2023 15:30:04 INFO: Starting Wazuh dashboard installation.
```

Now, the word `dashboard` is not displayed anymore.
