### ISSUE TITLE
Ugrading wazuh-indexer from 4.5 to 4.6 modifies config.yml file

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#2429]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.6.0| Indexer | Upgrade | RPM/DEB |

We found during to GitHub action tests that the `config.yml` file is modified when upgrading `wazuh-indexer` to 4.6.0:
```
Comparing opensearch.yml.example file checksum...
Old: ab1ad1f166434f3abac7a751c1e57fba
New: ab1ad1f166434f3abac7a751c1e57fba
opensearch.yml.example - Same checksum.
Comparing action_groups.yml file checksum...
Old: 49915bd12633877031bbbb8755475c57
New: 49915bd12633877031bbbb8755475c57
action_groups.yml - Same checksum.
Comparing audit.yml file checksum...
Old: 708fac768f8535fec7cc8f861ea2f51e
New: 708fac768f8535fec7cc8f861ea2f51e
audit.yml - Same checksum.
Comparing config.yml file checksum...
Old: b9eb7a16aa1969ee394370d3369a9d6b
New: 25c499973687a8fd3eb8b9ceb3da7a68
config.yml - Different checksum.
```
https://github.com/wazuh/wazuh-packages/actions/runs/6107919844/job/16575883511?pr=2426

Related PR: https://github.com/wazuh/wazuh-packages/pull/2426

**Comment by davidjiglesias** [comment]
We have to check why the installer modifies the config file during the upgrade.

**Comment by rauldpm** [comment]
## Update report

- The checksum difference is expected as the config.yml file has changed, and the IP values are not surrounded by double commas

![image](https://github.com/wazuh/wazuh-packages/assets/14913942/e7444034-8d48-49a8-a951-8deba29ac43a)

- This change was introduced in the commit: https://github.com/wazuh/wazuh-packages/commit/41857f494253ae7db8ed88d233aa49ca7f91dcb0 at https://github.com/wazuh/wazuh-packages/pull/1992 pull request

**Comment by mauromalara** [comment]
LGTM!

> Maybe in the future we can those expected SHAs to a "whitelist" file in order to avoid modifying the scripts.

**Comment by rauldpm** [comment]
Opened issue https://github.com/wazuh/wazuh-packages/issues/2459

**Comment by rauldpm** [comment]
## Update report

- Due to confusion, the file analyzed was not the correct one, the file that must be analyzed is the one located in `/etc/wazuh-indexer/opensearch-security/config.yml` and not in `/usr/share/wazuh-indexer/plugins/opensearch-security/tools/config.ym`
- Due to the fact that more changes have been detected in other files, this issue will be worked on at https://github.com/wazuh/wazuh-packages/issues/2460
