### ISSUE TITLE
Assistant reports AL2023 as not recommended system as an error

### ISSUE THREAD

**Issue by javimed** [wazuh/wazuh-packages#2434]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
|4.6.0-alpha1 | Instalation assistant | Install | Amazon Linux 2023 |

When generating certificates the installation assistant finds the operating system is not one of the recommend systems. It breaks the installation reporting this as an error.

```
bash-5.2# bash wazuh-install.sh --generate-config-files
07/09/2023 15:38:19 INFO: Starting Wazuh installation assistant. Wazuh version: 4.6.0
07/09/2023 15:38:19 INFO: Verbose logging redirected to /var/log/wazuh-install.log
07/09/2023 15:38:21 INFO: --- Dependencies ---
07/09/2023 15:38:21 INFO: Installing openssl.
07/09/2023 15:38:23 ERROR: The recommended systems are: Red Hat Enterprise Linux 7, 8, 9; CentOS 7, 8; Amazon Linux 2; Ubuntu 16.04, 18.04, 20.04, 22.04. The current system does not match this list. Use -i|--ignore-check to skip this check.
bash-5.2# 

```

The expected output message could rather be a warning instead.

**Comment by davidcr01** [comment]
This issue is related to: https://github.com/wazuh/wazuh-documentation/issues/6456
