### ISSUE TITLE
 Windows agent library not signed on Footprint tests

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh-packages#2440]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-alpha1 | wazuh-agent | Agent | Packages | Windows |

When analyzing the Footprint tests for Alpha 1 for 4.6.0, a new warning has been encountered, saying dynamic library `libfimdb.dll` is not signed in the package.

It has appeared on the following footprint tests for now:
- https://github.com/wazuh/wazuh/issues/18930
- https://github.com/wazuh/wazuh/issues/18919

The complete warning is the following:
```
wazuh-agent WARNING: The file 'C:\\Program Files (x86)\\ossec-agent\\libfimdb.dll' is not signed or its signature is invalid.
```

**Comment by teddytpc1** [comment]
Duplicated.
