### ISSUE TITLE
`grep` warning using the Installation Assistant in AL2023

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-packages#2473]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.5.3-rc1| Installation Assistant | Install | AL2023 |

A new warning message has been found in the following test of the 4.5.3-RC1 Wazuh version: https://github.com/wazuh/wazuh/issues/19103.

```shellsession
22/09/2023 08:14:09 INFO: Starting service filebeat.
grep: warning: stray \ before white space
grep: warning: stray \ before white space
```
It means that you are trying to use a backslash "\\" to escape whitespace in your regular expression, but this is not necessary. Whitespace is not a special character in POSIX regular expressions, so it is not necessary to escape it.

This `grep` warning could be generated in the following line:
https://github.com/wazuh/wazuh-packages/blob/22d7888a2240f5c65628c0aa5a902ffdd3ba3123/unattended_installer/install_functions/installCommon.sh#L571

This issue may seem solved in later versions, for example, in `4.6.0-alpha1` version:
https://github.com/wazuh/wazuh-packages/blob/82f90313f5c4748de170820d1a3402ff4df13817/unattended_installer/install_functions/installCommon.sh#L640

**Comment by CarlosALgit** [comment]
The installation assistant has been launched in AL2023 with the 4.8.0 release. As result, we can see that the warning from grep does not appear anymore.
Evidence:
```
16/04/2024 08:17:53 INFO: Starting service filebeat.
Synchronizing state of filebeat.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable filebeat
Created symlink /etc/systemd/system/multi-user.target.wants/filebeat.service → /usr/lib/systemd/system/filebeat.service.
16/04/2024 08:17:53 INFO: filebeat service started.
```

**Comment by davidcr01** [comment]
LGTM
