### ISSUE TITLE
Change wilcards in installation scripts

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#248]
Hello team,

I have found that using wildcards in the installation scripts can cause the installation to fail in some systems, we should try to reduce the usage of wildcards  as much as we can, for example instead of using:
```
chmod 660 ${DIR}/etc/rules/*
```
We should use:
```
find ${DIR}/etc/rules -maxdepth 1 -exec chmod 660 {} \;
``` 

Regards,
Daniel Folch

**Comment by DFolchA** [comment]
Hello team,

I have made these changes to the installation scripts of Debian packages. I have generated a package with the new scripts and tested it:

Install:
- [x] Ubuntu 16
- [x] Ubuntu 18

Upgrade:
- [x] Ubuntu 16
- [x] Ubuntu 18

Remove:
- [x] Ubuntu 16
- [x] Ubuntu 18

Purge:
- [x] Ubuntu 16
- [x] Ubuntu 18

Regards, 
Daniel Folch

**Comment by BraulioV** [comment]
Hi @DFolchA,

I noticed that this error only appears if the installation scripts contain this line: `set -exf`. The parameter `-f` disables the filename expansion. That's why all the lines containing a wildcard to expand the name fail.

For now, I will close this issue.

Regards.
