### ISSUE TITLE
`requestHeadersWhitelist` setting needs to be replaced by `requestHeadersAllowlist`

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-packages#2489]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| v4.6.0-beta1 | Dashboard - AMI/OVA | Install | Any |

Related to https://github.com/wazuh/wazuh-packages/issues/1969
During https://github.com/wazuh/wazuh/issues/19212#issuecomment-1739911788 it was found the next error
```
 Sep 28 15:23:06 wazuh-server opensearch-dashboards[2037]: {"type":"log","@timestamp":"2023-09-28T15:23:06Z","tags":["warning","config","deprecation"],"pid":2037,"message":"\"opensearch.requestHeadersWhitelist\" is deprecated and has been replaced by \"opensearch.requestHeadersAllowlist\""}
```

**Comment by davidjiglesias** [comment]
LGTM!
