### ISSUE TITLE
Authorization error message in the Wazuh dashboard logs

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2491]
## Description

One of the most common errors that we encounter when analyzing the Wazuh dashboard logs is the following error message:

```
Oct 02 11:49:02 wazuh-server opensearch-dashboards[4234]: 
{"type":"log","@timestamp":"2023-10-02T11:49:02Z",
"tags":["error","plugins","securityDashboards"],"pid":4234,
"message":"Failed authentication: Error: Authentication Exception"}
```

We do not have any justification for this error, so the objective of this issue is only to report the error message and provide a justification for it.

This message occurs when entering the wrong password when accessing the WUI, to reproduce it, follow the following steps

- Install an All In One deployment
- Access the WUI
- Identify yourself with the correct credentials
- Check the Wazuh dashboard logs (journalctl)
- Log out
- Identify yourself with incorrect credentials (password)
- Check the appearance of the error in the log

**Comment by juliamagan** [comment]
LGTM

**Comment by davidjiglesias** [comment]
LGTM!
