### ISSUE TITLE
The MSI package does not provide an `E-mail` in the `Digital Signature Details`

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2532]
## Description

In the certificates check https://github.com/wazuh/wazuh-jenkins/issues/5723 it has been found that the MSI package does not establish an E-mail in the `Signer information` section (`Not available`), it would be necessary to establish one as `info@wazuh.com` or similar, or justify not providing an email.

![image](https://github.com/wazuh/wazuh-packages/assets/14913942/df86cbfb-772c-47cd-bc68-b27741ad30b1)

**Comment by havidarou** [comment]
Not critical right now.
