### ISSUE TITLE
Wazuh certs-tool log file not defined

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-packages#2536]
## Description

As of this [commit](https://github.com/wazuh/wazuh-packages/commit/a2f62188f2262be21c993388dcf245eac09021be), the file /var/log/wazuh-cert-tool.log was deleted since it was necessary for the script to be executed without root permissions. This causes the outputs of the verbose mode to not be recorded in any file.

We must define if we are going to register the outputs of this script in some log file, and if it is valid to register this file in the same directory where the script itself is located

https://github.com/wazuh/wazuh-packages/blob/5cfb6e5966dfa00c5ad3c267d9be4f043f0d88a8/unattended_installer/cert_tool/certMain.sh#L175-L177

https://github.com/wazuh/wazuh-packages/blob/5cfb6e5966dfa00c5ad3c267d9be4f043f0d88a8/unattended_installer/cert_tool/certVariables.sh#L12

**Comment by CarlosALgit** [comment]
# Update
## Original issue
The original issue objective was to add a logfile on a path in which you dont need root permissions to write. We did that by setting the path to the folder in which the `wazuh-certs-tool.sh` is executed. This was done changing the file `wazuh-packages/unattended_installer/cert_tool/certVariables.sh` by adding this variable: `readonly logfile="${base_path}/wazuh-certificates-tool.log"`

## New issues

As this change was done, tests were executed and I noticed that the tool worked fine and created the `wazuh-certificates-tool.log` but didn't write nothing in it. We investigated this issue and find that the common_logger function -which is the one in charge of writing the logs- located in `unattended_installer/common_functions/common.sh`  needed `$EUID -eq 0` permissions (root) to write on files.

We decided that the best solution was add a new condition so if the call was from the wazuh-certs-tool.sh script it could write on a file. For a better implementation, we decided to set the name to look for on a variable and only find a substring that matches.
It was done adding a new variable on the `certsVariables.sh` like this: `readonly cert_tool_script_name=".*certs.*\.sh"`

To continue, it was needed to add the new conditional to the common_logger function.  I did that as seen here: 
```
if { [ "$EUID" -eq 0 ] && [ -z "${nolog}" ]; } || [[ "$(basename "$0")" =~ $cert_tool_script_name ]]; then
    printf "%s\n" "${now} ${mtype} ${message}" | tee -a ${logfile}
else
    printf "%b\n" "${now} ${mtype} ${message}"
fi
```
Solutions and evidence are on the PR related to this issue.
