### ISSUE TITLE
Create a wiki to document build and testing process of wazuh-packages

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-packages#256]
Hello team, 

Right now, the wazuh-packages repository does not have a wiki or documentation about how to perform the building and package testing process for each operating system.

I would create sections for all OS indicating how they are built, how packages are created in debug mode, the process followed to create packages, etc.

I think that this information could be useful to facilitate and speed up the task for the rest of the team.

**Comment by alberpilot** [comment]
Hello @jmv74211 

  We will do this but not in the Wiki section. We need to create it in the documentation. 

Best regards, 
Alberto R

**Comment by DFolchA** [comment]
Hello team,

I have written de documentation for RPM packages, the code has been committed to this [branch](https://github.com/wazuh/wazuh-documentation/tree/issue-wp-256-wazuh-packages-documentation-rpm), and there is a [PR](https://github.com/wazuh/wazuh-documentation/pull/1589) opened to merge it into the main packages documentation branch.

Regards,
Daniel Folch

**Comment by DFolchA** [comment]
Hello team,

I have written de documentation for DEB packages, the code has been committed to this [branch](https://github.com/wazuh/wazuh-documentation/tree/issue-wp-256-wazuh-packages-documentation-debs), and there is a [PR](https://github.com/wazuh/wazuh-documentation/pull/1592) opened to merge it into the main packages documentation branch.

Regards,
Daniel Folch

**Comment by DFolchA** [comment]
Hello team,

I have written de documentation for Solaris packages, the code has been committed to this [branch](https://github.com/wazuh/wazuh-documentation/tree/issue-wp-256-wazuh-packages-documentation-solaris), and there is a [PR](https://github.com/wazuh/wazuh-documentation/pull/1593) opened to merge it into the main packages documentation branch.

Regards,
Daniel Folch

**Comment by DFolchA** [comment]
Hello team,

I have written de documentation for Solaris packages, the code has been committed to this [branch](https://github.com/wazuh/wazuh-documentation/tree/issue-wp-256-wazuh-packages-documentation-aix), and there is a [PR](https://github.com/wazuh/wazuh-documentation/pull/1594) opened to merge it into the main packages documentation branch.

Regards,
Daniel Folch

**Comment by DFolchA** [comment]
Hello team,

I have written de documentation for Solaris packages, the code has been committed to this [branch](https://github.com/wazuh/wazuh-documentation/tree/issue-wp-256-wazuh-packages-documentation-HPUX), and there is a [PR](https://github.com/wazuh/wazuh-documentation/pull/1608) opened to merge it into the main packages documentation branch.

Regards,
Daniel Folch

**Comment by DFolchA** [comment]
Hello team,

This is an update of this issue state:

| Task                 | Status              
|:--------------------|---------------------:|
|DEB documentation        |  <ul><li>- [x] </li>|
|RPM documentation         | <ul><li>- [ ] </li>|
|AIX documentation    | <ul><li>- [x] </li> |
|HPUX documentation  |  <ul><li>- [x] </li> |
|OSX documentation| <ul><li>- [x] </li>| 
|Solaris documentation  | <ul><li>- [ ] </li> | 
|OVA documentation | <ul><li>- [ ] </li> | 
|KibanaApp documentation  | <ul><li>- [ ] </li> | 
|SplunkApp documentation   | <ul><li>- [ ] </li> | 
|WPK documentation   | <ul><li>- [x] </li> | 
|Merge branches into main [branch](https://github.com/wazuh/wazuh-documentation/tree/issue-wp-256-wazuh-packages-documentation)   | <ul><li>- [ ] </li> | 
|Create index and front page | <ul><li>- [ ] </li> | 

Regards, 
Daniel Folch

**Comment by DFolchA** [comment]
Hello team,

This is an update of this issue state:

| Task                 | Status              
|:--------------------|---------------------:|
|DEB documentation        |  <ul><li>- [x] </li>|
|RPM documentation         | <ul><li>- [x] </li>|
|AIX documentation    | <ul><li>- [x] </li> |
|HPUX documentation  |  <ul><li>- [x] </li> |
|OSX documentation| <ul><li>- [x] </li>| 
|Solaris documentation  | <ul><li>- [x] </li> | 
|OVA documentation | <ul><li>- [x] </li> | 
|KibanaApp documentation  | <ul><li>- [x] </li> | 
|SplunkApp documentation   | <ul><li>- [x] </li> | 
|WPK documentation   | <ul><li>- [x] </li> | 
|Merge branches into main [branch](https://github.com/wazuh/wazuh-documentation/tree/issue-wp-256-wazuh-packages-documentation)   | <ul><li>- [ ] </li> | 
|Create index and front page | <ul><li>- [ ] </li> | 

I have written the pages for the Apps, the OVA, RPM, And added the notarization process to OSX.
 
Regards, 
Daniel Folch

**Comment by DFolchA** [comment]
Hello team,

This is an update of this issue state:

| Task                 | Status              
|:--------------------|---------------------:|
|DEB documentation        |  <ul><li>- [x] </li>|
|RPM documentation         | <ul><li>- [x] </li>|
|AIX documentation    | <ul><li>- [x] </li> |
|HPUX documentation  |  <ul><li>- [x] </li> |
|OSX documentation| <ul><li>- [x] </li>| 
|Solaris documentation  | <ul><li>- [x] </li> | 
|OVA documentation | <ul><li>- [x] </li> | 
|KibanaApp documentation  | <ul><li>- [x] </li> | 
|SplunkApp documentation   | <ul><li>- [x] </li> | 
|WPK documentation   | <ul><li>- [x] </li> | 
|Merge branches into main [branch](https://github.com/wazuh/wazuh-documentation/tree/issue-wp-256-wazuh-packages-documentation)   | <ul><li>- x] </li> | 
|Create index and front page | <ul><li>- [x] </li> | 

I have merged all the branches into the main one and written the indexes, a have also refactored the wpk generation documentation.

Regards, 
Daniel Folch

**Comment by alberpilot** [comment]
Merged and closed.
