### ISSUE TITLE
Add support for Amazon Linux 1, and Amazon Linux 2023 in install script

### ISSUE THREAD

**Issue by JorgeMarinoDev** [wazuh/wazuh-packages#2612]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| TBD | install | install | Unattended | Amazon Linux 2023 |

This is a complementary issue to [Add support for Amazon Linux 1, and Amazon Linux 2023 in dist-detect.sh](https://github.com/wazuh/wazuh/issues/18905)

Just in order to provide a PR to be later on merged as long as complementary issue.

**Comment by JorgeMarinoDev** [comment]
Since this must be a coordinated merge process, a new issue in CICD was created https://github.com/wazuh/internal-devel-requests/issues/489.
Branch contains the necessary changes.

**Comment by nmkoremblum** [comment]
This issue is set "on hold" in favor of https://github.com/wazuh/wazuh/issues/21385 which has a higher priority
