### ISSUE TITLE
Debian package replicate the old .save files in every remove

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#262]
Hello team

  As indicated @snaow, if you install, uninstall, and install again, some `.save` files can be saved more than one time by the package manager: 
![image](https://user-images.githubusercontent.com/3830293/63037393-570cd300-bebf-11e9-92fe-dc66334adcac.png)

Please check if this is solved in 3.9.5 or needs to be reviewed. 

Best regards, 
Alberto R

**Comment by DFolchA** [comment]
Hello team,
It seems the problem in this issue is still happening in version 3.9.5, I'm currently investigating how to solve it.
Regards,
Daniel Folch
