### ISSUE TITLE
Non-available combination of wazuh-elastic version (OVA) on the README example

### ISSUE THREAD

**Issue by jojelupipa** [wazuh/wazuh-packages#264]
Current example:

```
To build an OVA with version 3.9.0 using elastic 6.6.2 and the stable repositories you can use:

# ./generate_ova.sh -b -v 3.9.0 -e 6.6.2 -r stable
```

These versions do not have a corresponding tag, so it won't generate the ova.

This could be changed to a pair of compatible versions, e.g. latest ones, v3.9.5-7.3.0

**Comment by DFolchA** [comment]
Hello team,

This issue has been solved in this PR #265.
Thanks to @jojelupipa  for his contribution.

Best regards,
Daniel Folch
