### ISSUE TITLE
The macOS ARM agent starts automatically at the end of the installation

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-packages#2655]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.7.1-40706 | Agent | Install/Upgrade/Remove |macOS Sonoma |

## Description

During the tests performed in https://github.com/wazuh/wazuh/issues/20471, it has been seen that when installing the agent with deployment variables, the agent starts automatically:

```shell
sh-3.2# /Library/Ossec/bin/wazuh-control start
Starting Wazuh v4.7.1...
wazuh-execd already running...
wazuh-agentd already running...
wazuh-syscheckd already running...
wazuh-logcollector already running...
wazuh-modulesd already running...
Completed.
```

Although, in the [documentation](https://documentation-dev.wazuh.com/v4.7.1-rc1/installation-guide/wazuh-agent/wazuh-agent-package-macos.html), it is indicated that you have to start the agent to complete the installation.

This did not seem to happen in [4.7.0 Alpha 1](https://github.com/wazuh/wazuh/issues/19690#issuecomment-1770643479), however, it has been tested in all the packages currently available for ARM in pre-release and the behavior is reproduced in all versions.

Also, this behavior is not the same for intel packages, on those OS's you do have to start the agent.

**Comment by nmkoremblum** [comment]
Hi @juliamagan,

I have some questions regarding this:

- How is Jenkins related to this?
- How did you collect this output? Is there any link I can refer to to analyze its context?
- How was Wazuh installed? Was this installation manually performed?
- Are there any specific logs or messages displayed during the installation that might indicate the automatic startup of the agent?
- Could this behavior be reproduced?

I will be waiting for your reply

**Comment by juliamagan** [comment]
Jenkins is not related to this, these tests were done manually during the testing of 4.7.1 RC1, in the issue linked in the main comment. The output was achieved by simply installing Wazuh according to the [documentation](https://documentation-dev.wazuh.com/v4.7.1-rc1/installation-guide/wazuh-agent/wazuh-agent-package-macos.html), but you can also see the steps followed in the [comment](https://github.com/wazuh/wazuh/issues/20471#issuecomment-1832231826) with the testing.

During the tests, when we `... is already running`, to make sure, we reproduced this behavior several times and with different versions, also with `watch -n0 "ps aux| grep wazuh"` we could see how Wazuh started automatically.

**Comment by nmkoremblum** [comment]
What do you mean by saying "with different versions"? Is this not constrained to 4.7.1?

**Comment by juliamagan** [comment]
The instances were provided by the @wazuh/cicd team via https://github.com/wazuh/internal-devel-requests/issues/534 and they were clean when we installed 4.7.1. Then, when we reproduced the case with other versions, we had to uninstall Wazuh following the [documentation](https://documentation-dev.wazuh.com/v4.7.1-rc1/installation-guide/wazuh-agent/wazuh-agent-package-macos.html#uninstall-a-wazuh-agent).

**Comment by nmkoremblum** [comment]
As of now, the issue couldn't be replicated on a clean VM, even after removing all Wazuh traces and attempting reinstallation across various versions. On this new VM, the automatic startup issue did not occur. However, on @juliamagan's original VM, despite the removal of all Wazuh traces and performing a clean installation, the issue persisted.

This discrepancy suggests that the automatic startup problem seems specific to @juliamagan's VM environment, as it persisted even after repeated reinstallation and cleanup procedures were performed. Ongoing investigations aim to identify the root cause of this behavior.

Despite this, the issue doesn't appear to be a stopper, as similar behavior was observed in previous versions as well.

**Comment by davidjiglesias** [comment]
This happened again in https://github.com/wazuh/wazuh/issues/21389, I am reopening it.

**Comment by nmkoremblum** [comment]
Hi @Deblintrake09 do we still have access to this VM? How did you remove the agent between installing it with the ENV variables and without it?

**Comment by Deblintrake09** [comment]
Hi.

The VM has been already destroyed. 

The Agent was uninstalled using all commands from the [documentation](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-macos.html#uninstall-a-wazuh-agent)

```console
# /Library/Ossec/bin/wazuh-control stop
# /bin/rm -r /Library/Ossec
# /bin/launchctl unload /Library/LaunchDaemons/com.wazuh.agent.plist
# /bin/rm -f /Library/LaunchDaemons/com.wazuh.agent.plist
# /bin/rm -rf /Library/StartupItems/WAZUH
# /usr/bin/dscl . -delete "/Users/wazuh"
# /usr/bin/dscl . -delete "/Groups/wazuh"
# /usr/sbin/pkgutil --forget com.wazuh.pkg.wazuh-agent
```

**Comment by nmkoremblum** [comment]
I was able to replicate the error. The issue is probably related to the following code block:
https://github.com/wazuh/wazuh-packages/blob/e5be5560407579f374fb41400127e7d187ca1588/macos/package_files/postinstall.sh#L153-L155

**Comment by nmkoremblum** [comment]
We are waiting for the package to be built so that we can test it. The pipeline link is: https://ci.wazuh.info/job/Packages_builder_tier/3373/

**Comment by nmkoremblum** [comment]
> I was able to replicate the error. The issue is probably related to the following code block:
> 
> https://github.com/wazuh/wazuh-packages/blob/e5be5560407579f374fb41400127e7d187ca1588/macos/package_files/postinstall.sh#L153-L155

Update:

After doing some tests, we conclude that the issue is not related to these code lines

**Comment by nmkoremblum** [comment]
After digging into the issue I've narrowed my focus to the following code block:

https://github.com/wazuh/wazuh/blob/647158b124fa78e330ba0e9423c0b2d5bbe65842/src/init/darwin-init.sh#L23-L40

According to what I've found so far, when `RunAtLoad` is set, this instructs the system to automatically start the service both at boot and when the configuration file is manually loaded using `launchctl load`. Immediately after setting such a configuration, the service is loaded, with the `launchctl load` command, potentially starting the service.

**Comment by nmkoremblum** [comment]
> After digging into the issue I've narrowed my focus to the following code block:
> ### [darwin-init.sh](https://github.com/wazuh/wazuh/blob/647158b124fa78e330ba0e9423c0b2d5bbe65842/src/init/darwin-init.sh#L23-L40)
> 
> > ```shell
> > echo '<?xml version="1.0" encoding="UTF-8"?>
> >  <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> >  <plist version="1.0">
> >      <dict>
> >          <key>Label</key>
> >          <string>com.wazuh.agent</string>
> >          <key>ProgramArguments</key>
> >          <array>
> >              <string>'$LAUNCHER_SCRIPT'</string>
> >          </array>
> >          <key>RunAtLoad</key>
> >          <true/>
> >      </dict>
> >  </plist>' > $SERVICE
> > 
> > chown root:wheel $SERVICE
> > chmod u=rw-,go=r-- $SERVICE
> > launchctl load $SERVICE
> > ```
> 
> According to what I've found so far, when `RunAtLoad` is set, this instructs the system to automatically start the service both at boot and when the configuration file is manually loaded using `launchctl load`. Immediately after setting such a configuration, the service is loaded, with the `launchctl load` command, potentially starting the service.

After doing a deeper analysis and testing, I can confirm that the problem is located in these lines indeed. Such a script is 5 years old, which means that this has always been like this for a while, so it shouldn't be a stopper.

**Comment by vikman90** [comment]
@nmkoremblum Your comment suggests that `launchctl load` on macOS and `systemctl start` on Linux are comparable. Thus, I believe we should remove `launchctl` if doing so won't stop the service from beginning when the system boots.

Regards!

**Comment by cborla** [comment]
Related issue https://github.com/wazuh/wazuh/issues/21636
