### ISSUE TITLE
Unable to remove wazuh-dashboard 4.7.0-1 from ubuntu 22.04.3

### ISSUE THREAD

**Issue by maxferrario-msf** [wazuh/wazuh-packages#2662]
| Wazuh version | Install type| Action performed | Platform |
|---|---|---|---|
| 4.7.0 | Quickstart, single server  | Uninstall | Ubuntu 22.04.3 LTS |

I tried to install Wazuh 4.7.0 on a test server running ubuntu using quickstart.
The installation failed with error "Wazuh dashboard installation failed".
The automatic uninstall removed Wazuh manager, Wazuh indexer and filebeat, but failed removing Wazuh-dashboard.
This is what I see in the log file:

```
Removing wazuh-dashboard (4.7.0-1) ...
Stopping wazuh-dashboard service...Failed to stop wazuh-dashboard.service: Unit wazuh-dashboard.service not loaded.
dpkg: error processing package wazuh-dashboard (--remove):
 installed wazuh-dashboard package pre-removal script subprocess returned error exit status 5
dpkg: too many errors, stopping
Errors were encountered while processing:
 wazuh-dashboard
Processing was halted because there were too many errors.
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

While the log file says "Wazuh dashboard removed.", the package is still installed on the server:

```
$ apt list --installed "wazuh*"
Listing... Done
wazuh-dashboard/now 4.7.0-1 amd64 [installed,local]
```

And if I try to uninstall the package manually using apt I get the same error seen ini the install log (i.e. "installed wazuh-dashboard package pre-removal script subprocess returned error exit status ").

**Comment by maxferrario-msf** [comment]
[obviously] I tried various "tricks" to uninstall a .deb package, as using the "--force-remove-reinstreq", but the error is still there.

**Comment by jnasselle** [comment]
Hi @maxferrario-msf,

Sorry to hear that you are struggling with this. Let me try to reproduce it and I'll be back ASAP. 

Regards,
Nico

**Comment by jnasselle** [comment]
@maxferrario-msf ,

I was not able to replicate it using https://app.vagrantup.com/ubuntu/boxes/jammy64

```
vagrant@ubuntu-jammy:~$ curl -sO https://packages.wazuh.com/4.7/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
04/12/2023 11:37:28 INFO: Starting Wazuh installation assistant. Wazuh version: 4.7.0
04/12/2023 11:37:28 INFO: Verbose logging redirected to /var/log/wazuh-install.log
04/12/2023 11:37:45 INFO: Wazuh web interface port will be 443.
04/12/2023 11:37:49 INFO: --- Dependencies ----
04/12/2023 11:37:49 INFO: Installing apt-transport-https.
04/12/2023 11:37:58 INFO: Wazuh repository added.
04/12/2023 11:37:58 INFO: --- Configuration files ---
04/12/2023 11:37:58 INFO: Generating configuration files.
04/12/2023 11:38:00 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
04/12/2023 11:38:00 INFO: --- Wazuh indexer ---
04/12/2023 11:38:00 INFO: Starting Wazuh indexer installation.
04/12/2023 11:39:05 INFO: Wazuh indexer installation finished.
04/12/2023 11:39:05 INFO: Wazuh indexer post-install configuration finished.
04/12/2023 11:39:05 INFO: Starting service wazuh-indexer.
04/12/2023 11:39:22 INFO: wazuh-indexer service started.
04/12/2023 11:39:22 INFO: Initializing Wazuh indexer cluster security settings.
04/12/2023 11:39:33 INFO: Wazuh indexer cluster initialized.
04/12/2023 11:39:33 INFO: --- Wazuh server ---
04/12/2023 11:39:33 INFO: Starting the Wazuh manager installation.
04/12/2023 11:40:22 INFO: Wazuh manager installation finished.
04/12/2023 11:40:22 INFO: Starting service wazuh-manager.
04/12/2023 11:40:39 INFO: wazuh-manager service started.
04/12/2023 11:40:39 INFO: Starting Filebeat installation.
04/12/2023 11:40:47 INFO: Filebeat installation finished.
04/12/2023 11:40:48 INFO: Filebeat post-install configuration finished.
04/12/2023 11:40:48 INFO: Starting service filebeat.
04/12/2023 11:40:49 INFO: filebeat service started.
04/12/2023 11:40:49 INFO: --- Wazuh dashboard ---
04/12/2023 11:40:49 INFO: Starting Wazuh dashboard installation.
04/12/2023 11:41:23 INFO: Wazuh dashboard installation finished.
04/12/2023 11:41:24 INFO: Wazuh dashboard post-install configuration finished.
04/12/2023 11:41:24 INFO: Starting service wazuh-dashboard.
04/12/2023 11:41:24 INFO: wazuh-dashboard service started.
04/12/2023 11:41:43 INFO: Initializing Wazuh dashboard web application.
04/12/2023 11:41:45 INFO: Wazuh dashboard web application initialized.
04/12/2023 11:41:45 INFO: --- Summary ---
04/12/2023 11:41:45 INFO: You can access the web interface https://<wazuh-dashboard-ip>:443
    User: admin
    Password: xxxxxxxxxxxxxxxxxxxxxxxxxxx
04/12/2023 11:41:45 INFO: Installation finished.
```

Let me now focus on solving your uninstall issue

**Comment by jnasselle** [comment]
Yes @maxferrario-msf , the upgrade scenario could be the cause of your issue. To reproduce it, would you happen to remember if it was an install and uninstall of 4.x version and afterward 4.7 installation? or was it an upgrade?

**Comment by maxferrario-msf** [comment]
> Yes @maxferrario-msf , the upgrade scenario could be the cause of your issue. To reproduce it, would you happen to remember if it was an install and uninstall of 4.x version and afterward 4.7 installation? or was it an upgrade?

It was an install + uninstall of an old 4.x version: I installed it on Oct 2022, it probably was 4.3.9.
When I tried to upgrade it to 4.4.0 something went wrong and, it being a test, I decided to remove and wait for better times for doing a proper test again :)

**Comment by maxferrario-msf** [comment]
Thanks @jnasselle ,
deleting the script allowed me to remove the package.

**Comment by Prathamesh314** [comment]
Can you provide me a script to remove wazuh-manager as well.
i am trying to uninstall it but it is throwing me errors

apt-get remove --purge wazuh-manager -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  wazuh-manager*
0 upgraded, 0 newly installed, 1 to remove and 4 not upgraded.
After this operation, 903 MB disk space will be freed.
(Reading database ... 176655 files and directories currently installed.)
Removing wazuh-manager (4.9.2-1) ...
dpkg: error processing package wazuh-manager (--remove):
 installed wazuh-manager package pre-removal script subprocess returned error exit status 127
dpkg: too many errors, stopping
Errors were encountered while processing:
 wazuh-manager
Processing was halted because there were too many errors.
E: Sub-process /usr/bin/dpkg returned an error code (1)
