### ISSUE TITLE
Solaris 11 library dependencies not working in all systems

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#268]
Hello team,

We have noticed that in Solaris 11 if any of the libraries required by are not in the same path as the machine where we built the package, the execution of some daemons will fail with the following message:
```
ld.so.1: ossec-execd: fatal: libgcc_s.so.1: open failed: No such file or directory

./ossec-control: line 119: 17718: Killed
```
Here you can see an example of which libraries wazuh-modulesd needs:
```
root@solaris11:/export/home/vagrant# ldd /var/ossec/bin/wazuh-modulesd
    libwazuhext.so => /var/ossec/bin/../lib/libwazuhext.so
    libsocket.so.1 => /lib/libsocket.so.1
    libnsl.so.1 => /lib/libnsl.so.1
    libresolv.so.2 => /lib/libresolv.so.2
    librt.so.1 => /lib/librt.so.1
    libpthread.so.1 => /lib/libpthread.so.1
    libc.so.1 => /lib/libc.so.1
    libgcc_s.so.1 => /opt/csw/lib/libgcc_s.so.1
    libmp.so.2 => /lib/libmp.so.2
    libucrypto.so.1 => /lib/libucrypto.so.1
    libelf.so.1 => /lib/libelf.so.1
    libcryptoutil.so.1 => /lib/libcryptoutil.so.1
    libz.so.1 => /lib/libz.so.1
```
We should include these libraries into the packages and make the daemons look for them there.

Regards,
Daniel Folch

**Comment by alguacilaguamara** [comment]
Hi DFolchA,

To solve this problem you can prove  to compile wazuh with FLAG  DISABLE_SHARED=true in install.sh option.

For example,
`root@solaris11:/wazuh# DISABLE_SHARED=yes ./install.sh`

Regards,
Alejandro Alguacil

**Comment by grg121** [comment]
This is related with https://github.com/wazuh/wazuh-packages/issues/330

**Comment by BraulioV** [comment]
Fixed in this commit: https://github.com/wazuh/wazuh-packages/commit/a2b902445579ca3be2c047798d69f41728974eb5
