### ISSUE TITLE
Add Filebeat template to Wazuh indexer

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2697]
## Description

As part of https://github.com/wazuh/internal-devel-requests/issues/600, it is necessary to modify the Wazuh indexer package to incorporate the Filebeat [wazuh-template
](https://github.com/wazuh/wazuh/blob/master/extensions/elasticsearch/7.x/wazuh-template.json)

For this, it is necessary to consider the following:

- To facilitate DevOps deployments, the template must be incorporated into the base file
- The template must be downloaded from the wazuh/wazuh repository
- The template must be installed in `/etc/wazuh-indexer/wazuh-template.json`
- If the template changes, the upgrade must modify the JSON
- The management of the current Filebeat template should not be modified by this development, the current commands will be maintained

### Working branch

- wazuh-packages: enhancement/2697-add-filebeat-template-indexer
- wazuh-jenkins: enhancement/wp2697-add-filebeat-template-indexer

**Comment by rauldpm** [comment]
## Update report

- Added new parameter `filebeat_module_reference` to generate_base.sh in indexer directory
  - If the parameter is empty, the version stored in the VERSION file will be used

![image](https://github.com/wazuh/wazuh-packages/assets/14913942/7dbb55aa-726c-44e1-9293-7809c5d33d95)

**Comment by rauldpm** [comment]
## Update report 

- On hold due https://github.com/wazuh/wazuh-qa/issues/4778

**Comment by rauldpm** [comment]
## Update report

- Created wazuh-jenkins PR https://github.com/wazuh/wazuh-jenkins/pull/6089
- Ready to test the changes

**Comment by davidjiglesias** [comment]
LGTM!
