### ISSUE TITLE
Wazuh-launcher unidentified developer (macOS)

### ISSUE THREAD

**Issue by mjcr99** [wazuh/wazuh-packages#2701]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.6.0 and others| Agent | Install | macOS |

# Description 
MacOS agents 4.5.4 and 4.6.0, and probably all the Wazuh versions are reporting the Wazuh-launcher item as an unidentified developer.

To test it, a wazuh agent package can be installed in macOS. Then, the command and output got are the following: 
```
sh-3.2# codesign --display --verbose=4  /Library/StartupItems/WAZUH/Wazuh-launcher
/Library/StartupItems/WAZUH/Wazuh-launcher: code object is not signed at all
sh-3.2# 
```
The same case is found for the `wazuh-control` file:
```
sh-3.2# codesign --display --verbose=4  /Library/Ossec/bin/wazuh-control 
/Library/Ossec/bin/wazuh-control: code object is not signed at all
sh-3.2# 
```
This is due to the signing procedure, when the macOS packages are built, these files are not signed. In the [Apple Code Signing Guide](https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40005929-CH1-SW1) is said that all the executables related to an app should be signed to provide greater confidence to the final user. The signing procedure should be reviewed to accomplish these good practices.

**Comment by mjcr99** [comment]
## Issue update:
**(26/01/2024)** Researching macos packages generation script and recreating each step locally.
**(29/01/2024)** Discarded hypothesis of the new signing files were not available when trying to sign them, researching deeper.
**(29/01/2024)** After giving some tries with the packages creation I have been researching deeply the codesign command and the signing process. The most useful information that I have found is here:
[Codesig Documentation](https://keith.github.io/xcode-man-pages/codesign.1.html)
[Technical Note TN2206 - macOS Code Signing In Depth](https://developer.apple.com/library/archive/technotes/tn2206/_index.html)
[Signing a Mac Product For Distribution
](https://developer.apple.com/forums/thread/128166)[Manual Code Signing Example](https://developer.apple.com/forums/thread/130855)

Since the Issue says all the executables should be signed, this statement has some exceptions.
To fully understand the problem we are trying to solve, we must understand what kind of files are being signed and what kind of files we want to sign.

Mac OS has a format called [Mach-O Executable Format](https://developer.apple.com/library/archive/documentation/Performance/Conceptual/CodeFootprint/Articles/MachOOverview.html) this kind of files are the ones that are being signed now by default when we generate our Mac OS packages. 

The files reported by this issue that are not signed are scripts, not binaries like the others. Since it's possible to sign this kind of file, it's mentioned in the [code signing guide](https://developer.apple.com/library/archive/technotes/tn2206/_index.html#:~:text=Store%20Python%2C%20Perl%2C%20shell%2C%20and%20other%20script%20files%20and%20other%20non%2DMach%2DO%20executables%20in%20your%20app%27s%20Contents/Resources%20directory.%20While%20it%27s%20possible%20to%20sign%20such%20executables%20and%20store%20them%20in%20Contents/MacOS%2C%20this%20is%20not%20recommended.) signing this kind of files is not recommended. The signature of this kind of file would need the usage of [extended attributes](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/listxattr.2.html) and it's said it can bring [problems while deploying the package](https://developer.apple.com/library/archive/technotes/tn2206/_index.html#:~:text=If%20the%20extended%20attributes%20are%20lost%20then%20the%20program%27s%20signature%20will%20be%20broken.%20Many%20file%20transfer%20techniques%20do%20not%20preserve%20extended%20attributes%2C%20nor%20are%20they%20preserved%20when%20uploading%20to%20the%20Mac%20App%20Store.) since many file transfer techniques do not preserve extended attributes.

We currently comply with the signing requirements and adding more signatures could result in problems instead of solutions.
**(05/02/2024)** Trying to sign the entire installation folder to sign all files implicitly.
**(06/02/2024)** Unsuccessful tries, having problems regarding the notarization phase.
**(08/08/2024)** Added test in https://github.com/wazuh/wazuh/pull/25091 to verify it solves the problem.

**Comment by MarcelKemp** [comment]
- Fixed by https://github.com/wazuh/wazuh/pull/25091
