### ISSUE TITLE
Port 443 is being used by another process. Please, check it before installing Wazuh.

### ISSUE THREAD

**Issue by justin-eight** [wazuh/wazuh-packages#2725]
I'm trying to install Wazuh version (4.7.1), but getting the error message "Port 443 is being used by another process. Please, check it before installing Wazuh."

For reference, I'm using your Wazuh Installation Assistant.

Ubuntu 22.04.3

**Comment by davidcr01** [comment]
Hello. The Wazuh components require some ports to have a correct and complete functionality. The list of ports and their use are explained in the following documentation: https://documentation.wazuh.com/current/getting-started/architecture.html#required-ports

In the case of the Wazuh web interface port, it is specified by default as the `443` port. The Wazuh installation assistant checks the availability of these ports before performing the installation, so the assistant is informing that the `443` port is not available in your system to perform the installation. 
To check if the port is being used, you can execute the `lsof -sTCP:LISTEN  -i:443` command. 

Also, the Wazuh installation assistant exposes an option to change the Wazuh web port interface in case this port is being used:
```
-p,  --port"

"Specifies the Wazuh web user interface port. By default is the 443 TCP port. Recommended ports are: 8443, 8444, 8080, 8888, 9000."
```
