### ISSUE TITLE
Shorten OVA description

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-packages#2729]
## Description
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.8.1 | OVA | Install | Any |

When attempting to deploy the appliance, using vCloud Director virtualized environment, directly from the provided .ova file it fails with a cryptic error:
“OVF descriptor file size cannot be greater than 12,582,912 bytes. Size of provided OVF is 2,570,936,320 bytes.”

The user found out that it was related to this:
![Screenshot from 2023-12-29 10-20-57](https://github.com/wazuh/wazuh-packages/assets/33964202/4148544f-b6ba-4db8-8729-af30ca35ff17)

The “description” field is too long (by 18 characters) to be successfully deployed. Limit is 255 Char.
By shortening it manually, the user was successful in deploying the package.

## Solution
To solve this issue, the OVA description should be shortened to 255 characters:
- [x] Shorten the OVA description
- [ ] Test it using vCloud Director if possible.

**Comment by davidcr01** [comment]
# Update Report

## The text

After consulting the new text with the @wazuh/marketing team, the proposed text is the following, with 243 characters, satisfying the required requisites: 

> Wazuh enhances security visibility in your infrastructure by monitoring endpoints at the operating system and application levels. Its capabilities include log analysis, file integrity monitoring, intrusion detection, and compliance monitoring.

## VMWare Cloud director

After creating an account in the VMWare services, I could not download the VMWare Cloud Director tool for free:

![image](https://github.com/wazuh/wazuh-packages/assets/72193239/599095a2-ecd6-4a31-a0ee-568f3af0cdbd)
