### ISSUE TITLE
Redundant gmake command in the Solaris 11 package generation file.

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-packages#273]
Hello team,

I have been working on the documentation of the agent installation via sources in Solaris 11, and I have found a possible gmake command that is redundant in [generate_wazuh_packages](https://github.com/wazuh/wazuh-packages/blob/master/solaris/solaris11/generate_wazuh_packages.sh) line 106. 

```
if [ "$arch" == "sparc" ]; then
        gmake -j $THREADS TARGET=agent PREFIX=${install_path} USE_SELINUX=no USE_BIG_ENDIAN=yes
else
        gmake -j $THREADS TARGET=agent PREFIX=${install_path} USE_SELINUX=no
fi
gmake -j $THREADS TARGET=$TARGET 
```
I think that `gmake -j $THREADS TARGET=$TARGET` has already been performed by either the if or the else and should be deleted.

Regards,
Jonathan M.V

**Comment by BraulioV** [comment]
Closed by https://github.com/wazuh/wazuh-packages/pull/274
