### ISSUE TITLE
The size of Wazuh Manager packages and derivatives (OVA, AMI) increased significantly

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-packages#2769]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
|v4.8.0-alpha2 | Manager | - | - |

# Description

During https://github.com/wazuh/wazuh/issues/21385 it was found that v4.8.0-alpha2 Wazuh Manager packages (deb, rpm) size increased significantly compared to the last productive version (v4.7.2 at this moment)

- RPM
  - v4.7.2 https://packages.wazuh.com/4.x/yum/wazuh-manager-4.7.2-1.x86_64.rpm 
  - v4.8.0-alpha2 https://packages-dev.wazuh.com/pre-release/yum/wazuh-manager-4.8.0-1.x86_64.rpm
- DEB
  - v4.7.2 https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-manager/wazuh-manager_4.7.2-1_amd64.deb
  - v4.8.0-alpha2 https://packages-dev.wazuh.com/pre-release/apt/pool/main/w/wazuh-manager/wazuh-manager_4.8.0-1_arm64.deb
- OVA
  - v4.7.2 https://packages.wazuh.com/4.x/vm/wazuh-4.7.2.ova
  - v4.8.0-alpha2 https://packages-dev.wazuh.com/pre-release/vm/wazuh-4.8.0.ova 

```
drwx------ 56 jnasselle jnasselle  16K Jan 11 16:21 ..
-rw-r--r--  1 jnasselle jnasselle 2.6G Jan 10 09:02 wazuh-4.7.2.ova
-rw-r--r--  1 jnasselle jnasselle 3.3G Jan 11 09:51 wazuh-4.8.0.ova
-rw-r--r--  1 jnasselle jnasselle 165M Jan 10 10:40 wazuh-manager_4.7.2-1_amd64.deb
-rw-r--r--  1 jnasselle jnasselle 166M Jan 10 10:01 wazuh-manager-4.7.2-1.x86_64.rpm
-rw-r--r--  1 jnasselle jnasselle 266M Jan 10 18:43 wazuh-manager_4.8.0-1_arm64.deb
-rw-r--r--  1 jnasselle jnasselle 351M Jan 10 17:29 wazuh-manager-4.8.0-1.x86_64.rpm
```

**Comment by vikman90** [comment]
@jnasselle This footprint change is due to the new Vulnerability Detector feed, that is now included out-of-the-box:

```shell
du -hd0 /var/ossec/queue/vd/feed
```

```
4.5G    /var/ossec/queue/vd/feed
```

It's known and approved by @santiago-bassett.

Best!

**Comment by pereyra-m** [comment]
The issue requires a new owner and a new estimation.

**Comment by MiguelazoDS** [comment]
The same level of compression used in wazuh-dashboard packaging was ported here. The size was reduced significantly with the drawback of greater execution time.
