### ISSUE TITLE
Add Mitre DB to DEB and RPM packages

### ISSUE THREAD

**Issue by danimegar** [wazuh/wazuh-packages#282]
|Issue|Host| 
|---|---|
| [#3709](https://github.com/wazuh/wazuh/issues/3709)|Manager|

Hi team! I have a Mitre json file in wazuh repository: /etc/mitre/enterprise-attack.json in 3.10-mitre branch so that Wazuh support the ATT&CK Matrix for Enterprise. It's necessary that this file is in DEB and RPM packages, too. When the Manager installation is finished, the file has to be copied in {var/ossec}/ruleset/mitre/enterprise-attack.json. 

Link to download json file: https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json

Permissions:
- json file: rw-r----- (640)
- folder /ruleset/mitre: rwxr-x--- (750), like folders /ruleset/rules or ruleset/decoders

**Comment by alguacilaguamara** [comment]
Hello danimegar.

I will try to enter that file to generate debian and rpms packages. For it:

[ ] Insert the file in the postins
[ ] Generate a new deb package
[ ] Insert in the %postun section of the SPEC file
[ ] Generate a new rpm

**Comment by alguacilaguamara** [comment]
Hello. 

In order to insert the file, I have added the file download and assigned the permissions. For this in the SPEC of 3.11 of deb and rpm I have added

```
# Copy mitre ruleset
curl -so enterprise-attack/enterprise-attack.json  https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json
mkdir -p ${DIR}/ruleset/mitre
cp enterprise-attack.json ${DIR}/ruleset/mitre/
```

Regards.
Alejandro

**Comment by alguacilaguamara** [comment]
Hello team.

I have tested that the package is generated, with changes in https://github.com/wazuh/wazuh-packages/issues/282#issuecomment-528236342, on the next OS:

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Fedora 30
- [ ] Centos 7

Best regards.
Alejandro Alguacil

**Comment by BraulioV** [comment]
Update: now the packages will install a `mitre.db` instead of a JSON file. The development of this issue can be followed in: [3.11-mitre](https://github.com/wazuh/wazuh-packages/compare/3.11-mitre).

**Comment by danimegar** [comment]
## Update
The packages will install a mitre.db from 3.13 on. The development of this issue can be followed in: [282-mitre-package](https://github.com/wazuh/wazuh-packages/compare/282-mitre-package).
