### ISSUE TITLE
Wazuh agent RPM package for AIX has a runtime dependency on bash

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-packages#2878]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| up to master | Agent | Install | AIX 6.1 TL9 |

## Description

It was found that Wazuh agent RPM package for AIX has a runtime dependency on bash that shows the following error during package installation on a clean AIX 6.1 TL9 requested to SiteOx

```
# WAZUH_MANAGER="10.0.0.2" rpm -ivh wazuh-agent-4.7.3-1.aix.ppc.rpm
Preparing...                          ################################# [100%]
Updating / installing...
   1:wazuh-agent-4.7.3-1              ################################# [100%]
/var/tmp/rpm-tmp.teEaab[40]: /var/ossec/tmp/src/init/register_configure_agent.sh:  not found
```

After installing bash, the installation works as expected.

## DoD

- [x] Add `Required` property to AIX RPM spec with bash and any dependency
- [x] Create a PR at wazuh/wazuh-documentation adding this installation dependency, since rpm will not solve this dependency but warn/error if is not meet

**Comment by vikman90** [comment]
Let's move this issue to the icebox.

**Comment by lchico** [comment]
# Update
I was able to create the PR and test it. Next, I need to create the PR for the documentation.
