### ISSUE TITLE
issue when installing the packages 

### ISSUE THREAD

**Issue by sundarrdeveloper** [wazuh/wazuh-packages#2884]
./generate_debian_package.sh -b v4.7.3 --packages-branch v4.7.3 -s /tmp -t api -a i386 -r my_rev
[+] Building 1.0s (12/12) FINISHED                                                                                                                         docker:default
 => [internal] load build definition from Dockerfile                                                                                                                 0.0s
 => => transferring dockerfile: 2.04kB                                                                                                                               0.0s
 => [internal] load metadata for docker.io/library/debian:7                                                                                                          0.8s
 => [internal] load .dockerignore                                                                                                                                    0.0s
 => => transferring context: 2B                                                                                                                                      0.0s
 => [1/7] FROM docker.io/library/debian:7@sha256:2259b099d947443e44bbd1c94967c785361af8fd22df48a08a3942e2d5630849                                                    0.0s
 => [internal] load build context                                                                                                                                    0.0s
 => => transferring context: 5.37kB                                                                                                                                  0.0s
 => CACHED [2/7] RUN echo "deb http://archive.debian.org/debian/ wheezy contrib main non-free" > /etc/apt/sources.list &&     echo "deb-src http://archive.debian.o  0.0s
 => CACHED [3/7] RUN apt-get update && apt-get build-dep python3.2 -y --force-yes                                                                                    0.0s
 => CACHED [4/7] RUN curl -OL http://packages.wazuh.com/utils/gcc/gcc-9.4.0.tar.gz &&     tar xzf gcc-9.4.0.tar.gz  && cd gcc-9.4.0/ &&     ./contrib/download_prer  0.0s
 => CACHED [5/7] RUN curl -OL http://packages.wazuh.com/utils/cmake/cmake-3.18.3.tar.gz &&     tar -zxf cmake-3.18.3.tar.gz && cd cmake-3.18.3 &&     ./bootstrap -  0.0s
 => CACHED [6/7] ADD build.sh /usr/local/bin/build_package                                                                                                           0.0s
 => CACHED [7/7] RUN chmod +x /usr/local/bin/build_package                                                                                                           0.0s
 => exporting to image                                                                                                                                               0.0s
 => => exporting layers                                                                                                                                              0.0s
 => => writing image sha256:f7f393152356ea0eb7f1b37f1e723e943d618b30238fa8e61c994236b1f059d9                                                                         0.0s
 => => naming to docker.io/library/deb_builder_amd64:latest                                                                                                          0.0s
+ build_target=api
+ wazuh_branch=v4.7.3
+ architecture_target=i386
+ package_release=my_rev
+ jobs=2
+ dir_path=/var/ossec
+ debug=no
+ checksum=no
+ wazuh_packages_branch=v4.7.3
+ use_local_specs=no
+ local_source_code=no
+ future=no
+ '[' -z my_rev ']'
+ '[' api = api ']'
+ '[' no = no ']'
+ curl -sL https://github.com/wazuh/wazuh-api/tarball/v4.7.3
+ tar zx

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

i'm getting this error when trying to install using this command 

**command** :   ./generate_debian_package.sh -b v4.7.3 --packages-branch v4.7.3 -s /tmp -t api -a i386 -r my_rev
help me to sort out this error 

**reference URL** :  https://documentation.wazuh.com/current/development/packaging/generate-deb-package.html

**Comment by rauldpm** [comment]
Hello

The API option was obsolete after 3.x, currently, the API is included in the Wazuh manager package, it is true that the documentation is wrong and should not mention this option, I am going to open an issue to fix this, the help of the script mentions the following:

    echo "    -t, --target <target>      [Required] Target package to build: manager or agent."
    

if you want to generate the Wazuh manager package refer to:

> ./generate_debian_package.sh -b v4.7.3 --packages-branch v4.7.3 -s /tmp -t manager -a amd64 -r my_rev.

**Comment by sundarrdeveloper** [comment]
okay, thanks for the update

**Comment by rauldpm** [comment]
@sundarrdeveloper Did you manage to generate the Wazuh manager package?

**Comment by sundarrdeveloper** [comment]
No, I can't able to run , but im trying my level to generate the package

**Comment by rauldpm** [comment]
Can you show me the error you are getting and the command you are running? Also, make sure you are using the v4.7.3 tag and not a numeric or master branch

**Comment by sundarrdeveloper** [comment]
Hi , 

I'm using this command to run this project 
 ./generate_debian_package.sh -b v4.7.3 --packages-branch v4.7.3  -t manager -a amd64.

**Comment by rauldpm** [comment]
Hi, I can't help you if you don't say which error are you getting, I can only confirm that the package generation is correct and functional using the v4.7.3 GitHub tag, please, make sure that you are using the correct GitHub tag as stated in the documentation

``` 
git clone https://github.com/wazuh/wazuh-packages && cd wazuh-packages/debs && git checkout v4.7.3
```

Also, make sure that the command does not have the `dot` in amd64, the command should be:

```
./generate_debian_package.sh -b v4.7.3 --packages-branch v4.7.3 -t manager -a amd64
```

A message like the following indeed appears, but the package should be created in the output directory correctly (located in the directory where you executed the command), I am talking with the team about those messages

```
(...)
W: wazuh-manager: executable-not-elf-or-script var/ossec/wodles/init.py
W: wazuh-manager: executable-not-elf-or-script var/ossec/packages_files/manager_installation_scripts/etc/templates/config/generic/localfile-logs/apache-logs.template
N: 19467 tags overridden (10 errors, 19457 warnings)
Finished running lintian.
```

After that, the following should appear:

```
WARNING generated by debuild:
Making debian/rules executable!

+ deb_file=wazuh-manager_4.7.3-1
+ [[ amd64 == \p\p\c\6\4\l\e ]]
+ deb_file=wazuh-manager_4.7.3-1_amd64.deb
+ pkg_path=/build_wazuh/manager
+ [[ no == \y\e\s ]]
+ mv /build_wazuh/manager/wazuh-manager_4.7.3-1_amd64.deb /var/local/wazuh
```

The package generated should be stored in a directory called output in the same directory

```
╰─➤  ls output                                                                                                                                                                                                                           1 ↵
wazuh-manager_4.7.3-1_amd64.deb
```

**Comment by sundarrdeveloper** [comment]
H Rauldpm , 


Thanks for helping. Based on the commands you gave, the file is now in the directory path. May I get the command to see the application in the browser?

**Comment by rauldpm** [comment]
The Wazuh manager is not a web application and therefore you cannot see it in the browser.

Please read the following documentation to understand what each component of Wazuh is and does.

- https://documentation.wazuh.com/current/getting-started/components/index.html

If you want to access Wazuh through the browser you must install the Wazuh dashboard and Wazuh indexer in addition to the Wazuh manager and Filebeat, for this, you can follow the installation guide, either through the Wazuh installation assistant or step-by-step guide

- https://documentation.wazuh.com/current/installation-guide/index.html

**Comment by sundarrdeveloper** [comment]
okay, thanks for helping me to install.
