### ISSUE TITLE
Implement debug symbol generation during the build process for macOS

### ISSUE THREAD

**Issue by ncvicchi** [wazuh/wazuh-packages#2886]
### Description

|Related issue|
|---|
|[#21734](https://github.com/wazuh/wazuh/issues/21734)|

Currently, maxOS packages generated do not include debug symbols, which can hinder debugging efforts when issues arise. This issue aims to implement the necessary steps to generate packages with debug symbols for macOS packages.

### Proposed Solution

1. **Update Packaging Scripts:**
   - Modify the scripts responsible for generating macOS installer packages to incorporate the inclusion of debug symbols.
   - Implement any necessary logic to ensure that debug symbols are correctly packaged and included.

### Research guidelines

Research on how we are currently compiling for macOS should be done.
A good understanding of the compiling process (which is different on macOS than on Linux) will be necessary. 
A fast search indicated that for macOS debug symbols are always created separated from the binary, and then must be joined by using the `dsymutil` tool to bring them together. This might simplify this issue if found to be true.

    
- **Enhanced Debugging:** Including debug symbols in the packages facilitates easier debugging and troubleshooting of issues encountered by users.
- **Improved Developer Experience:** Developers benefit from having access to debug symbols when investigating issues reported by users.

### Definition of Done
- The macOS packaging process is updated to incorporate the inclusion of debug symbols.

**Comment by Leoquicenoz** [comment]
The ETA is delayed as work was being done on this [issue](https://github.com/wazuh/wazuh/issues/21734).

**Comment by Leoquicenoz** [comment]
## Update

We are investigating the possibility of generating a .pkg file with the files containing the debug symbols, apparently it is a complicated task, so we are also analyzing the possibility of putting the `.dSYM` files generated in the compilation in a compressed package, what I am investigating is once I have them in the compressed file, how the user could install them if necessary.

**Comment by Leoquicenoz** [comment]
## Update

The changes made in the `Makefile` in which the debug symbols were separated from the binaries in macOS are moved to the `macos/package_files/build.sh` file.

```
ec2-user@ip-172-31-33-149 macos % ls repository/wazuh/src/symbols 
agent-auth.dSYM            host-deny.dSYM             libdbsync.dylib.dSYM       libsysinfo.dylib.dSYM      npf.dSYM                   wazuh-agentd.dSYM          wazuh-slack.dSYM
default-firewall-drop.dSYM ip-customblock.dSYM        libfimdb.dylib.dSYM        libwazuhext.dylib.dSYM     pf.dSYM                    wazuh-execd.dSYM
disable-account.dSYM       ipfw.dSYM                  librsync.dylib.dSYM        libwazuhshared.dylib.dSYM  restart-wazuh.dSYM         wazuh-logcollector.dSYM
firewalld-drop.dSYM        kaspersky.dSYM             libsyscollector.dylib.dSYM manage_agents.dSYM         route-null.dSYM            wazuh-modulesd.dSYM 
```

**Comment by ncvicchi** [comment]
Since a migration from packages repository to wazuh repository is being performed, this issue is being discarded
