### ISSUE TITLE
Prevent failed checks related to dashboard and indexer since 4.9.0

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh-packages#2901]
|Wazuh version|
|---|
| 4.9.0 | 

## Description

Due to the redesign of packages, and their corresponding migration, carried out in the following issue:
- https://github.com/wazuh/internal-devel-requests/issues/187

It is intended to prevent checks related to the dashboard and indexer from failing due to lack of updates. Because from `4.9.0` onwards, maintenance, and upgrades will be done in their own repositories.
> - https://github.com/wazuh/wazuh-packages/pull/2897#issuecomment-2031936506

To avoid failed checks, we want to prevent them from being triggered when the base branch is 4.9.0 or higher, so we will have to remove these checks from the GHA workflows, as well as from the CI checks executed in Jenkins, so that they are not executed again for these versions.

#### Unattended install + Distributed cases

These checks are executed from Jenkins within the Wazuh CI group, so it is necessary to apply the necessary settings in the wazuh-jenkins repository to prevent the execution of these checks. It seems that the files related to the triggers is the following:
- https://github.com/wazuh/wazuh-jenkins/blob/4.9.0/jenkins-files/pull_requests/pr_packages.groovy

#### Password tool script tests

This other case, when executing also the unattended install script, it is necessary that it is not executed either, as it will fail as the previous ones. In order not to execute it, it is simply necessary to delete the triggers (`on pull request`) that are in the workflow:
- https://github.com/wazuh/wazuh-packages/blob/4.9.0/.github/workflows/password-tool.yml

**Comment by MarcelKemp** [comment]
## Update

After being able to resume this issue (due to other higher priority issues), I have investigated the checks that are run for dashboard and indexer, and I am making the necessary changes to both `wazuh-packages` and `wazuh-jenkins` to prevent them from running:
- PR packages: https://github.com/wazuh/wazuh-packages/pull/2909
- Jenkins: investigating to try not to remove the checks that simply install the manager.

**Comment by rauldpm** [comment]
This issue does not match with the used objective, those checks are owned by other teams. Why is this being worked by the Core team and with this objective?
