### ISSUE TITLE
Wazuh macOS agent uninstall.sh script needs to be updated

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2926]
## Description

Uninstalling the Wazuh macOS agent, an "error" was observed in the `unload` command, it was reported in the following issue: https://github.com/wazuh/wazuh-documentation/issues/7109

Related PR: https://github.com/wazuh/wazuh-documentation/pull/7123/files

The fix consists of the documentation command removal but the wazuh-packages macOS `uninstall.sh` script was not modified, this script is used during the package generation, and we need to fix it

https://github.com/wazuh/wazuh-packages/blob/3ad9a509919c4196bbf7ccfc4a7aabb7ce94e62e/macos/uninstall.sh#L8

```
/Library/Developer/CommandLineTools/usr/bin/make -C ../framework clean
rm -f  *.o *.so.0
rm -f ../etc/ossec.mc
rm -f Config.OS
rm -rf external/cJSON external/curl external/libdb external/libffi external/libyaml external/openssl external/procps external/sqlite external/zlib external/audit-userspace external/msgpack external/bzip2 external/nlohmann external/googletest external/libpcre2 external/libplist external/pacman external/libarchive external/popt external/lua external/rpm external/rocksdb external/lzma external/cpp-httplib external/benchmark external/cpython external/jemalloc external/flatbuffers external/cpython/ external/cpython.tar.gz external/rocksdb/
+ /Users/vagrant/Documents/wazuh/packages/macos/uninstall.sh
wazuh-modulesd not running...
wazuh-logcollector not running...
wazuh-syscheckd not running...
wazuh-agentd not running...
wazuh-execd not running...
Wazuh v4.9.0 Stopped
/Library/LaunchDaemons/com.wazuh.agent.plist: Could not find specified service
Unload failed: 113: Could not find specified service
No receipt for 'com.wazuh.pkg.wazuh-agent' found at '/'.
No receipt for 'com.wazuh.pkg.wazuh-agent-etc' found at '/'.

Wazuh agent correctly removed from the system.

+ exit 1
```

Note: The version is 4.9.0 but the code is present in 4.8.0

**Comment by jotacarma90** [comment]
This issue will be solved in the package migration tier 1:
Specifically in this commit: https://github.com/wazuh/wazuh/commit/179170968498702b09178889937e460cc06a102e
When we have a PR for this branch, we link it with this issue.
