### ISSUE TITLE
Error executing 'ps' command when generating API package (debian)

### ISSUE THREAD

**Issue by druizz90** [wazuh/wazuh-packages#293]
Hi team,

I got this error while a `.deb` package from Wazuh API was generating:

```bash
./install_api.sh: line 79: ps: command not found
```

This error does not interrupt the process but I think it should be solved by installing `ps` command into the container which generates the package.

Best regards,

Demetrio.

**Comment by alguacilaguamara** [comment]
Hello team,

To solve this issue, I add to the compile deb dockerfiles the command `ps`.

Best regards,
Alejandro Alguacil
