### ISSUE TITLE
Different set of permission for plugins in Release 4.8.0

### ISSUE THREAD

**Issue by TheMuntu** [wazuh/wazuh-packages#2942]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| Release 4.8.0 | Manager | Install | Oracle Linux 8 x86_64 |

## Issue description

During the [Release 4.8.0 - RC 1 - E2E UX tests - Wazuh Dashboard](https://github.com/wazuh/wazuh/issues/23241) test, we discovered that the `wazuhCheckUpdates` and `wazuhCore` plugins have different permissions compared to others in the `/usr/share/wazuh-dashboard/plugins/` directory.

<img width="545" alt="image" src="https://github.com/wazuh/wazuh-packages/assets/59522058/3f08cc2a-2440-4fbe-b805-61f4ca7145a1">

Please review this issue and make the necessary corrections. 

Thank you.

cc: @rauldpm

**Comment by rauldpm** [comment]
LGTM
