### ISSUE TITLE
Fatal glibc error: CPU does not support x86-64-v2

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-packages#3007]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.8.0 | Manager | Install / Upgrade | Proxmox ≤ 7.x |

## Description

Users have reported encountering the following error while running our packages:

```
Fatal glibc error: CPU does not support x86-64-v2
```

This issue appears to be related to an incompatibility between the version of _glibc_ used in our 4.8.0 release and certain older CPUs. This error has been specifically noted in environments using Proxmox 7.x or earlier.

## Rationale

The root cause of this issue stems from the deprecation of older operating systems (e.g., CentOS 6 and Debian 7) and a change related to CURL:
- https://github.com/wazuh/wazuh-packages/pull/2164
- https://github.com/wazuh/wazuh/issues/16279

Additionally, _glibc_ has introduced requirements that certain CPU features must be present, which are only available in CPUs starting from the Intel Core 2 Duo architecture. This means that any CPU lacking these features, or virtual environments not properly emulating them, will fail to execute the binaries.

While Proxmox version 8 and later should not face this issue, older CPUs and certain virtual environments (e.g., Proxmox 7.x or earlier) may not meet the necessary requirements. The failure is likely due to virtualized environments where the CPUID presented to the guest OS does not include the necessary feature flags.

## Affected Platforms

- Physical machines with CPUs older than Intel Core 2 Duo.
- Virtual environments using Proxmox 7.x or earlier.
    They do not properly emulate the required CPU features.

## Next Steps

1. **Reproduce the issue:**
    Set up an environment with an affected CPU or a Proxmox 7.x (or earlier) virtual environment to confirm the error.
2. **Assess the impact**:
    Determine whether the number of affected users and the criticality of this issue justify the development effort for a fix.
3. **Develop the fix**:
    If deemed necessary, implement a fix by adjusting the compilation flags used when generating the official packages to ensure compatibility with x86-64-v1 CPUs.

## Related forums

- [Wazuh Slack channel - Jun 12th](https://wazuh.slack.com/archives/C0A933R8E/p1718208995510019)
- https://github.com/wazuh/wazuh-kubernetes/issues/719
  - [Wazuh Slack channel - Jun 18th](https://wazuh.slack.com/archives/C0A933R8E/p1718712897410949)

### Related issue with MySQL

- https://github.com/docker-library/mysql/issues/1055
- [mysql8) Fatal glibc error: CPU does not support x86-64-v2](https://svrforum.com/svr/1447270)

All these cases are related to **Proxmox 7.x**.

## References

- [Proxmox Roadmap](https://pve.proxmox.com/wiki/Roadmap)

**Comment by crlsgms** [comment]
To workaround this issue without going to proxmox 8 change the cpu type on kubernetes node machines to host or  Broadwell-noTSX
![image](https://github.com/wazuh/wazuh-packages/assets/4990453/35020cea-09f6-4bb3-838f-6d05d27e68aa)

anyhow to use the 4.8.0 images the k8s nodes need to be rebooted to get the new cpu type. 

just to register on this same array of hardware / proxmox wazuh 4.7.5 runs normally

**Comment by vikman90** [comment]
## Update

I have attempted to reproduce this issue using a VirtualBox virtual machine with the following CPUID (basic functionality + SSE + SSE2):

|Leaf|EAX|EBX|ECX|EDX|
|--|--|--|--|--|
|`1`|`00000f12`|`00000000`|`00000000`|`3febfbff`|

```
.\VBoxManage.exe modifyvm debian_jammy_1718810405219_28512 --cpuidset 1 00000f12 00000000 00000000 3febfbff
```

### Results

|OS|Kernel|Result|Screenshot|
|--|--|--|--|
|CentOS 7|3.10.0-1160.95.1.el7.x86_64| ❌ Kernel panic|![image](https://github.com/wazuh/wazuh-packages/assets/10536251/54820d49-a853-41b4-ae28-10f0152fa861)|
|Ubuntu 22.04|5.15.0-89-generic| ❌ System hang|![image](https://github.com/wazuh/wazuh-packages/assets/10536251/6db723db-ddad-4827-89f3-05acea81181a)|

Neither of these kernels booted, which leads me to believe that the kernels used in these distributions for Kubernetes/Proxmox are modified.

Given that this issue has only been reported on virtualized systems with Proxmox 7.x, I propose associating the cause of the problem with this specific system. Therefore, I do not see the need to recompile Wazuh for older systems.

## Workarounds

- Upgrade Proxmox to version 8 or higher.
- Change the CPU type to Broadwell-noTSX (thanks @crlsgms!).

**Comment by swiftbird07** [comment]
Hello, do you have a workaround for AMD CPUs (I currently can't update Proxmox)? @vikman90

**Comment by crlsgms** [comment]
> Hello, do you have a workaround for AMD CPUs (I currently can't update Proxmox)? [@vikman90](https://github.com/vikman90)

Have you tried setting the CPUs to host?

**Comment by zhangguanzhang** [comment]
change to max works

<img width="1035" height="490" alt="Image" src="https://github.com/user-attachments/assets/520aff65-39cd-4a21-83ee-3a3da8d8798d" />
