### ISSUE TITLE
Add output styling to Installation assistant

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-packages#3017]
## Description

The Wazuh installation assistant is a very used tool by our team and community. It's one of the best and fastest ways to install Wazuh, even it is included in the [Quickstart documentation](https://documentation.wazuh.com/current/quickstart.html#installing-wazuh).

However, although this tool has many functionalities, the console output it generates is plain, without formatting and uncolored. Currently, many bash scripts and functionalities have colored and formatted outputs. This is widely developed in Python script, for example, as in the Allocation module:
![image](https://github.com/wazuh/wazuh-packages/assets/72193239/27666c0d-6f8e-44b4-a94a-0a109b6bba27)

Adding this kind of feature will make the Installation assistant more attractive and friendly to our community users.

## Proposed changes

- Information messages in :green_circle: color.
- Warning messages in :orange_circle: color.
- Error messages in :red_circle: color.
- Important messages in **bold** (for examples, passwords).

## Validation

- [ ] The code should not suffer many changes.
- [ ] The information messages are printed in green.
- [ ] The warning messages are printed in orange.
- [ ] The error messages are printed in red.
- [ ] The important messages are printed in bold.
- [ ] The formatting is set back to default after generating a formatted message.

**Comment by davidjiglesias** [comment]
We are not doing this now.
