### ISSUE TITLE
Scheduled upward merges for numbered branches in wazuh-packages repository - Fortnight #11

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-packages#3027]
## Description

The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.8.1-into-4.9.0`.

### 4.8.1
- [x] Update changelog.
- https://github.com/wazuh/wazuh-packages/pull/3029
  - Migrated code will be handled in the owner's issues
  - Code not migrated should be merged

**Comment by vikman90** [comment]
## Issue Blocked

- https://github.com/wazuh/wazuh-packages/issues/3030
- https://github.com/wazuh/wazuh-packages/issues/3031
