### ISSUE TITLE
README files with broken link  

### ISSUE THREAD

**Issue by alguacilaguamara** [wazuh/wazuh-packages#303]
Hello team,

The following README files there are broken link web.

- wazuh-packages / debs / repository / src / external / libffi / README. URL http://moxielogic.org/wiki/index.php?title=Libffi_3.2 -> Error 404 File not found

- wazuh-packages / debs / repository / src / external / msgpack / README. The phrase See QUICKSTART-C.md for more details links to another file. This has the following broken links:
https://www.gentoo-portage.com/dev-libs/msgpack, http://msgpack.org/releases/cpp/

- wazuh-packages / debs / repository / src / external / zlib / contrib / masmx64 and masmx86 / readme.txt. URL http://www.winimage.com/zLibDll/zlib124_masm_obj.zip

- wazuh-packages / debs / repository / src / external / audit-userspace / README. URL http://marc.theaimsgroup.com/?t=107815888100001&r=1&w=2 and http://marc.theaimsgroup.com/?t=107901570800002&r=1&w=2

- wazuh-packages / debs / repository / src / external / cJSON / README.md. In the phrase and the other cJSON contributors.

- https://github.com/wazuh/wazuh-jenkins/issues/523#issuecomment-530695939

Regards
Alejandro Alguacil

**Comment by BraulioV** [comment]
Hi @alguacilaguamara,

Those links belong to external dependencies such as `zlib`, `cJSON`, etc. which are download while building the agent/manager. So we don't need to maintain those READMEs.

Regards.

**Comment by alguacilaguamara** [comment]
Hi @BraulioV.

Do I delete all those links in a PR?.

Regards.
