### ISSUE TITLE
Error at building wazuh-manager RPM

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-packages#3030]
|Wazuh version|Install type|
|---|---|
| 4.8.1 → 4.9.0 | Manager |

## Source

- https://github.com/wazuh/wazuh-packages/pull/3029
- https://github.com/wazuh/wazuh-packages/actions/runs/9842448379/job/27171395297?pr=3029

## Error

```
error: Installed (but unpackaged) file(s) found:
   /var/ossec/framework/wazuh/core/cluster/hap_helper/__init__.py
   /var/ossec/framework/wazuh/core/cluster/hap_helper/hap_helper.py
   /var/ossec/framework/wazuh/core/cluster/hap_helper/proxy.py
   /var/ossec/framework/wazuh/core/cluster/hap_helper/wazuh.py
```

**Comment by Selutario** [comment]
As mentioned by @MarcelKemp, this was already fixed in 4.9.0, the SPECS was updated in wazuh/wazuh (https://github.com/wazuh/wazuh/commit/12af0aa8b31fbb3167b607186b03abd2b77b2e4a). @vikman90 suggested disabling these tests.

**Comment by rauldpm** [comment]
Tests and repository code are pending removal from 4.9.0, we should ignore those tests.

**Comment by rauldpm** [comment]
We are not going to maintain the migrated code, as I stated in my last message, the migrated code should be removed from wazuh-packages in the future
