### ISSUE TITLE
Review package related files due to new AWS module file

### ISSUE THREAD

**Issue by RamosFe** [wazuh/wazuh-packages#3046]
|Wazuh version|
|---|
| 5.0.0 |

This Issue aims to add the new `constants.py` file for the AWS wodle added in https://github.com/wazuh/wazuh/issues/21603.

# Tasks
- [ ] Review that the changes made to the AWS Module have their counterpart in the corresponding `wazuh-packages` files (e.g. `solaris/solaris11/SPECS/template_agent.json`)
- [ ] Test the correct build of the packages that required a modification on their files.

**Comment by fdalmaup** [comment]
Due to the changes planned for version 5.0, the analysis that is being carried out regarding the External integrations modules, and the DevOps overhaul for 5.0.0, this issue is being closed as not planned.
