### ISSUE TITLE
Add support for arm64 

### ISSUE THREAD

**Issue by tur11ng** [wazuh/wazuh-packages#3058]
Hello,

I would like to ask if it is possible to add support for arm64 deb package in order to be able to use it in raspberry pi 5. From what I read here https://documentation.wazuh.com/current/installation-guide/packages-list.html , only the packages Filebeat, Indexer and Dashboard are missing. I also read a comment here mentioning the process https://github.com/wazuh/wazuh-docker/issues/1306#issuecomment-2097879448. Is there any other obstacle that makes it difficult to support this architecture?

Best regards!

**Comment by davidcr01** [comment]
Hello. Unfortunately, in our roadmap, we are not going to add support for the central components of Wazuh (indexer, server, dashboard). However, we will maintain the support for the Wazuh agent ARM in the rest of the OSs. Sorry about the inconvenience this may cause.
