### ISSUE TITLE
Update README files from this repository

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-packages#306]
Hi team,

We noticed that some of the README files from this repository are not up to date, especially the help messages from those files, or maybe the options. We must review those files and update them.

Regards.

**Comment by DFolchA** [comment]
Hello team, 
We have decided that we will move the readmes of this repo to wazuh-documentation, so in the future, the readmes will only contain a link to the documentation.
You can follow the progress in this issue #256 
Regards,
Daniel Folch

**Comment by alberpilot** [comment]
Duplicated: https://github.com/wazuh/wazuh-packages/issues/256
