### ISSUE TITLE
Unable to start Wazuh OVA on XCP-NG hypervisor

### ISSUE THREAD

**Issue by MatrixInfosec** [wazuh/wazuh-packages#3069]
Version: Wazuh 4.8.1 
Install Type: OVA 
Platform: XCP-NG

The VM stops at "Booting the kernel" and never continues.

**Comment by davidcr01** [comment]
Hello. 

In our [documentation](https://documentation.wazuh.com/current/deployment-options/virtual-machine/virtual-machine.html), we do not support the XCP-NG Virtualization system. We recommend you to use VirtualBox or VMWare. 

If you are having some trouble when starting the machine, it could be related to the graphics controller. Notice that, when using VirtualBox, the `VMSVGA` graphic controller must be assigned.
