### ISSUE TITLE
SPECS for new SCA Windows Server 2012 (non R2)

### ISSUE THREAD

**Issue by jk-olaoluwa** [wazuh/wazuh-packages#3073]
Create SPECS as needed for a new OS SCA

PR - https://github.com/wazuh/wazuh/pull/21794 Is ready to merge
Branch - https://github.com/wazuh/wazuh/tree/18535-create-sca-policy-for-windows-server-2012-non-r2

PLEASE confirm with @wazuh/threat-intel before merging.

**Comment by lchico** [comment]
Hello @jk-olaoluwa, For windows, we don't need to change the SPCEC, just add it to `wazuh/src/win32/wazuh-installer.wxs`, so you can do it on the same PR that you work on. Here you will have an example: https://github.com/wazuh/wazuh/pull/13899
Please let me know if you need any help with that.

**Comment by jk-olaoluwa** [comment]
> Hello @jk-olaoluwa, For windows, we don't need to change the SPCEC, just add it to `wazuh/src/win32/wazuh-installer.wxs`, so you can do it on the same PR that you work on. Here you will have an example: [wazuh/wazuh#13899](https://github.com/wazuh/wazuh/pull/13899) Please let me know if you need any help with that.

The wazuh/src/win32/wazuh-installer.wxs file has been updated here - https://github.com/wazuh/wazuh/commit/e5d2e5681ccd7a17d9bfc2ad948c080126c6dcc1

**Comment by lchico** [comment]
# Update
I followed up with @jk-olaoluwa; this was already solved, as he mentioned in this commit https://github.com/wazuh/wazuh/commit/e5d2e5681ccd7a17d9bfc2ad948c080126c6dcc1.

**Comment by MarcelKemp** [comment]
The changes that have been merged do not work correctly, as the following line is missing:
```
            <ComponentRef Id="SCA_WIN2012NONR2" />
```

This is causing failures in the checks and msi generation:
- https://github.com/wazuh/wazuh/actions/runs/10557708872/job/29245985099

**Comment by jk-olaoluwa** [comment]
> The changes that have been merged do not work correctly, as the following line is missing:
> 
> ```
>             <ComponentRef Id="SCA_WIN2012NONR2" />
> ```
> 
> This is causing failures in the checks and msi generation:
> 
> * https://github.com/wazuh/wazuh/actions/runs/10557708872/job/29245985099

Hello @MarcelKemp, this has been resolved here - https://github.com/wazuh/wazuh/commit/f1bc6f0b8dde0038f34ebb86bbed0ecbaad372b5

**Comment by MarcelKemp** [comment]
Hi @jk-olaoluwa, 
As soon as you merge the commit, let us know, and we will check that everything works correctly, so we can close the issue. 

Thanks in advance!

**Comment by jk-olaoluwa** [comment]
> Hi @jk-olaoluwa, As soon as you merge the commit, let us know, and we will check that everything works correctly, so we can close the issue.
> 
> Thanks in advance!

Commit has been merged - https://github.com/wazuh/wazuh-packages/issues/3073#issuecomment-2312183590

**Comment by MarcelKemp** [comment]
As I see that the job is now working correctly, I am closing the issue as completed:
- https://github.com/wazuh/wazuh/actions/runs/10576674319/job/29303146204 -> :green_circle:
