### ISSUE TITLE
Generate final tag and publish draft release for Wazuh 4.9.0

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-packages#3096]
## Description

This issue attempts to publish draft release and generate final tag for version 4.9.0 in the wazuh-packages repository.

## Tasks

- [x] Generate final tag v4.9.0 from branch 4.9.0 on wazuh-packages repository.
- [x] Publish [GitHub draft release](https://github.com/wazuh/wazuh-packages/releases) from [tag v4.9.0](https://github.com/wazuh/wazuh-packages/tree/v4.9.0).

**Comment by vikman90** [comment]
**Release draft:**

https://github.com/wazuh/wazuh-packages/releases/edit/untagged-741dd012cbd01c1e1dbc
