### ISSUE TITLE
Updating Filebeat credentials when trying to install Wazuh dashboard

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-packages#3115]
It was detected that when the central components are installed individually, at the time of installing Wazuh dashboard, the validation that is done when updating the password is incomplete since it only validates that if Filebeat is installed it enters, the problem is that this should only happen in the cases of installing Wazuh manager.

![image](https://github.com/user-attachments/assets/daae62bf-2681-4047-9930-92853677bf3d)

https://github.com/wazuh/wazuh-packages/blob/11c56bc0a1fc507e6bf360b94d58cdea0e527e4e/unattended_installer/passwords_tool/passwordsFunctions.sh#L48-L66

This corresponds to the password tool, and we must only execute the password change of the component that is being installed.

**Comment by CarlosALgit** [comment]
# Update Report
I've tried the fix for this and I'm currently testing different types of installations.
I need to test the installation component by component, an AIO and in both `rpm` and `deb` package managers.
I also need to test if the change breaks the Wazuh Password tool when it's used alone.
