### ISSUE TITLE
Generate final tag and publish draft release for Wazuh 4.9.2

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh-packages#3163]
## Description

This issue attempts to publish draft release and generate final tag for version 4.9.2 in the wazuh-packages repository.

## Tasks

- [x] Generate final tag v4.9.2 from branch 4.9.2 on wazuh-packages repository.
- [x] Publish [GitHub draft release](https://github.com/wazuh/wazuh-packages/releases) from [tag v4.9.2](https://github.com/wazuh/wazuh-packages/tree/v4.9.2).

**Comment by vikman90** [comment]
Draft:

https://github.com/wazuh/wazuh-packages/releases/edit/untagged-2bd50a1394252d78ac4a
