### ISSUE TITLE
SPECS for new SCA policy for Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by Johnng007** [wazuh/wazuh-packages#3170]
Create SPECS as needed for a new OS SCA

Issue: https://github.com/wazuh/wazuh/issues/23194

Branch - https://github.com/wazuh/wazuh/tree/enhancement/23194-create-sca-policy-for-the-ubuntu-24-04-lts

PR: https://github.com/wazuh/wazuh/pull/27253

PLEASE confirm with @wazuh/threat-intel before merging.

**Comment by vikman90** [comment]
@Johnng007 Can you tell us what the main issue is? It will help us to keep track and inherit both priority and target version. 

Thanks.

**Comment by Johnng007** [comment]
> @Johnng007 Can you tell us what the main issue is? It will help us to keep track and inherit both priority and target version.
> 
> Thanks.

Hi @vikman90 Here is the Issue: https://github.com/wazuh/wazuh/issues/23194

**Comment by jotacarma90** [comment]
Blocked until SCA file is merged:
https://github.com/wazuh/wazuh/tree/enhancement/23194-create-sca-policy-for-ubuntu-24-04-lts

**Comment by Johnng007** [comment]
@jotacarma90 
SCA has been merged.
https://github.com/wazuh/wazuh/pull/27253
