### ISSUE TITLE
 Error installing Wazuh API (DEB)

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-packages#32]
If you have a "dirty" machine, the installer thinks you are doing an upgrade because it founds some directories under /tmp then it applies some code lines in the wrong way.

We need to review the way we check if it's an upgrade or not.

Regards!

**Comment by BraulioV** [comment]
Hi @jesusgn90,

in this commit https://github.com/wazuh/wazuh-packages/commit/27ee216f4cef75498ca17ea45f5bba59a3ff6acc I fixed this issue in the wazuh-api package, wazuh-manager and wazuh-agent.

This fixed will be published with the new 3.6.0 release.

Regards, 
Braulio.

**Comment by jesusgn90** [comment]
Roger
