### ISSUE TITLE
Building rpm on fedora 30 fails due to selinux

### ISSUE THREAD

**Issue by timhughes** [wazuh/wazuh-packages#320]
When attempting to build the agent on fedora 30 there is a permission issue if selinux is running

```
+ checksum=no
+ disable_debug_flag='%debug_package %{nil}'
+ '[' -z 100 ']'
+ '[' no == no ']'
+ echo %debug_package '%{nil}'
+ build_dir=/build_wazuh
+ rpm_build_dir=/build_wazuh/rpmbuild
+ mkdir -p /build_wazuh/rpmbuild/BUILD /build_wazuh/rpmbuild/BUILDROOT /build_wazuh/rpmbuild/RPMS /build_wazuh/rpmbuild/SOURCES /build_wazuh/rpmbuild/SPECS /build_wazuh/rpmbuild/SRPMS
+ package_name=wazuh-agent-3.10.2
+ cd /build_wazuh
+ tar czf /build_wazuh/rpmbuild/SOURCES/wazuh-agent-3.10.2.tar.gz wazuh-agent-3.10.2
tar: wazuh-agent-3.10.2: Cannot open: Permission denied
tar: Exiting with failure status due to previous errors
```

Environment:

Vagrant image of fedora 30. Vagrant file is as follows:

```
Vagrant.configure("2") do |config|
  config.vm.box = "fedora/30-cloud-base"
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 2
    libvirt.memory = 2048
    libvirt.nested = true
    libvirt.graphics_type = 'spice'
    libvirt.video_type = 'virtio'
  end
end
```

If you disable selinux it works

```
setenforce 0
```

Expected:

I would not expect to disable the security of my system to build an rpm

**Comment by alguacilaguamara** [comment]
Hello, @timhughes.

The SELinux problem is related to the shared folder between the host and the Docker container.

By default, the SELinux policy blocks the Docker container to write on the host and makes it impossible to complete the script.

To solve this, we added a new SELinux context in docker to allow write in the host when SELinux is available. This change is in PR https://github.com/wazuh/wazuh-packages/pull/340.

Bests regards.
Alejandro Alguacil

**Comment by timhughes** [comment]
Cool, thanks all.

**Comment by alberpilot** [comment]
Hello all.

 The PR was merged. Thanks to @timhughes for reporting, @alguacilaguamara for the PR, @BraulioV for reviewing, great!

Best regards, 
Alberto R
