### ISSUE TITLE
Repository check before clone

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#326]
Hello team,

I have noticed that when a repository is already downloaded by a previous run that ended prematurely of some generation scripts, for example, Debian and RPM the script continues building the package with the old sources instead of downloading the new ones.

This can cause the failure of the script because of trying to build an agent or manager package with the API sources, or vice-versa, or the building of a version different from the specified.

We should add a check for the repository and checkout to build the right branch or just run the clean function at the beginning of the script.

Regards,
Daniel Folch

**Comment by alguacilaguamara** [comment]
Hello team,

I'm going to add the clean function at the beginning of the script to the `generate_debian_package.sh` and `generate_rpm_package.sh` script.

Regards,
Alejandro Alguacil
