### ISSUE TITLE
Wazuh 3.11.0 package generation doesn't work for Solaris 10 (DISABLE_SHARED=yes)

### ISSUE THREAD

**Issue by grg121** [wazuh/wazuh-packages#330]
Hello team, we've detected that the package generation for Solaris does not work and this problem seems to be related with the flag `DISABLE_SHARED=yes`.

We thought it was a problem with our Vagrant box because it compiled in another box but not in ours. Nevertheless, after making some tests we've concluded that it works in both machines just by running:

```java
git clone https://github.com/wazuh/wazuh -b 3.11
gmake -C wazuh/src deps
gmake -C wazuh/src TARGET=agent OSSEC_LDFLAGS="'-Wl,-rpath,/../lib' -O2" -j2
```

And fails on both using the package generation script.

Running gmake with setting option we got:

```
General settings:
    TARGET:             agent
    V:                  
    DEBUG:              
    DEBUGAD             
    PREFIX:             /var/ossec
    MAXAGENTS:          14000
    DATABASE:           
    ONEWAY:             no
    CLEANFULL:          no
    RESOURCES_URL:      https://packages.wazuh.com/deps/3.11
User settings:
    OSSEC_GROUP:        ossec
    OSSEC_USER:         ossec
    OSSEC_USER_MAIL:    ossecm
    OSSEC_USER_REM:     ossecr
USE settings:
    USE_ZEROMQ:         no
    USE_GEOIP:          no
    USE_PRELUDE:        no
    USE_INOTIFY:        no
    USE_BIG_ENDIAN:     no
    USE_SELINUX:        no
    USE_AUDIT:          no
    USE_FRAMEWORK_LIB:  no
Mysql settings:
    includes:           
    libs:               
Pgsql settings:
    includes:           
    libs:               
Defines:
    -DMAX_AGENTS=14000 -DOSSECHIDS -DDEFAULTDIR="/var/ossec" -DUSER="ossec" -DREMUSER="ossecr" -DGROUPGLOBAL="ossec" -DMAILUSER="ossecm" -DSunOS -DSOLARIS -DHIGHFIRST -std=gnu99 -D_REENTRANT -DENABLE_SYSC -DENABLE_CISCAT -DENABLE_SHARED -DCLIENT
Compiler:
    CFLAGS             -DNDEBUG -O2 -DMAX_AGENTS=14000 -DOSSECHIDS -DDEFAULTDIR="/var/ossec" -DUSER="ossec" -DREMUSER="ossecr" -DGROUPGLOBAL="ossec" -DMAILUSER="ossecm" -DSunOS -DSOLARIS -DHIGHFIRST -std=gnu99 -D_REENTRANT -DENABLE_SYSC -DENABLE_CISCAT -DENABLE_SHARED -DCLIENT -pipe -Wall -Wextra -I./ -I./headers/ -Iexternal/openssl/include -Iexternal/cJSON/ -Iexternal/libyaml/include -Iexternal/curl/include -Iexternal/msgpack/include
    LDFLAGS           '-Wl,-rpath,/../lib' -O2
    CC                gcc
    MAKE              gmake
```

when running gmake without using the generation script and 

```java
General settings:
    TARGET:             agent
    V:                  
    DEBUG:              
    DEBUGAD             
    PREFIX:             /var/ossec
    MAXAGENTS:          14000
    DATABASE:           
    ONEWAY:             no
    CLEANFULL:          no
    RESOURCES_URL:      https://packages.wazuh.com/deps/3.10
User settings:
    OSSEC_GROUP:        ossec
    OSSEC_USER:         ossec
    OSSEC_USER_MAIL:    ossecm
    OSSEC_USER_REM:     ossecr
USE settings:
    USE_ZEROMQ:         no
    USE_GEOIP:          no
    USE_PRELUDE:        no
    USE_INOTIFY:        no
    USE_BIG_ENDIAN:     no
    USE_SELINUX:        no
    USE_AUDIT:          no
    USE_FRAMEWORK_LIB:  no
Mysql settings:
    includes:           
    libs:               
Pgsql settings:
    includes:           
    libs:               
Defines:
    -DMAX_AGENTS=14000 -DOSSECHIDS -DDEFAULTDIR="/var/ossec" -DUSER="ossec" -DREMUSER="ossecr" -DGROUPGLOBAL="ossec" -DMAILUSER="ossecm" -DSunOS -DSOLARIS -DHIGHFIRST -std=gnu99 -D_REENTRANT -DENABLE_SYSC -DENABLE_CISCAT -DCLIENT
Compiler:
    CFLAGS             -DNDEBUG -O2 -DMAX_AGENTS=14000 -DOSSECHIDS -DDEFAULTDIR="/var/ossec" -DUSER="ossec" -DREMUSER="ossecr" -DGROUPGLOBAL="ossec" -DMAILUSER="ossecm" -DSunOS -DSOLARIS -DHIGHFIRST -std=gnu99 -D_REENTRANT -DENABLE_SYSC -DENABLE_CISCAT -DCLIENT -pipe -Wall -Wextra -I./ -I./headers/ -Iexternal/openssl/include -Iexternal/cJSON/ -Iexternal/libyaml/include -Iexternal/curl/include -Iexternal/msgpack/include
    LDFLAGS           '-Wl,-rpath,/../lib' -O2
    CC                gcc
    MAKE              gmake
```

When running the package generation script.

The only difference is the use of `-DENABLE_SHARED ` on the working case. So we're discussing the need to modify the packet generation script to set this flag to "no" (or not to set it, the behavior would be the same).

Talking with the core team we've concluded that enabling shared libraries would be an advantage instead of a problem, and we're not sure of the reason of disabling it in the past.

We will have to test the package generation with `DISABLED=SHARED=no` with all the previous versions and extract conclusion with respect to the use of this flag.

Also, we would have to check what happens in Solaris 11 with such flag. 

----

Related with https://github.com/wazuh/wazuh-packages/issues/268

**Comment by grg121** [comment]
Hello team, we've tested the package generation with `DISABLE_SHARED=no` on Solaris 10 (3.11, v3.10.2, v3.9.5) and the package is correctly installed, the agent connected to the manager and generating alerts. 

3.11 https://jenkins-production.wazuh.info/job/Build_solaris_packages/1038/console
3.10.2 https://jenkins-production.wazuh.info/job/Build_solaris_packages/1040/console
3.9.5 https://jenkins-production.wazuh.info/job/Build_solaris_packages/1041/console

**Comment by grg121** [comment]
Hello team, I reopen this issue until we decided if it is necessary to add any change related with Solaris 10 SPARK or even for Solaris 11 and the flag `DISABLE_SHARED=yes`.

**Comment by BraulioV** [comment]
To avoid compatibility issues related to the libwazuhext.so and how the .so objects work in Solaris 11, we have decided to link the binaries against the libwazuh.a. This will make heavier packages but it at least, we will have one package for all the Solaris 11 supported versions.
