### ISSUE TITLE
Why are MD5 checksum used for package verification

### ISSUE THREAD

**Issue by alphaDev23** [wazuh/wazuh-packages#34]
Given that there are hashing algos less susceptible to collisions than MD5 (https://www.kb.cert.org/vuls/id/836068) and that Wazuh is software cantered around security, why are MD5 checksums used to verify packages (https://documentation.wazuh.com/current/installation-guide/packages-list/index.html#packages)?

**Comment by alphaDev23** [comment]
SHA-256 is the checksum algo used by OSSEC (https://www.ossec.net/downloads.html) for users to verify downloads.

**Comment by jesusgn90** [comment]
We note down your advice, thanks @alphaDev23 .

Regards,
Jesús

**Comment by jesusgn90** [comment]
Ok @alphaDev23 , finally we are going to use  SHA-512 for all our packages. Closing this issue. Next release will come with  SHA-512, thanks @alphaDev23 !

**Comment by alphaDev23** [comment]
Thank you for considering the recommendation and making the change.

**Comment by jesusgn90** [comment]
You are welcome @alphaDev23
