### ISSUE TITLE
Change the readme files in order to follow the documentation guide

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#343]
Hello team

  According to PR https://github.com/wazuh/wazuh-documentation/pull/1907, in order to avoid duplicate work, we need to change our README files in all packages. The new content will redirect the users to the official documentation and now, all changes done in script uses etc has to be reflected in the documentation. 

Best regards,
Alberto R

**Comment by alguacilaguamara** [comment]
Hello team.

In order to facilitate readme-files updates, I am going to put in these files only the description of what corresponds to each package and for the rest of the information, I will put Wazuh documentation links instead of instructions.  

Best regards,
Alejandro Alguacil
