### ISSUE TITLE
Package installation fails if broken install preceeded

### ISSUE THREAD

**Issue by alphaDev23** [wazuh/wazuh-packages#35]
Received the following during install (after apt-get install failed):

$dpkg -i wazuh-agent_3.5.0-1_amd64.deb

Preparing to unpack wazuh-agent_3.5.0-1_amd64.deb ...
mkdir: cannot create directory ‘/tmp/wazuh-agent/group’: File exists
dpkg: error processing archive wazuh-agent_3.5.0-1_amd64.deb (--install):
 subprocess new pre-installation script returned error exit status 1
 Removing any system startup links for /etc/init.d/wazuh-agent ...
Errors were encountered while processing:
 wazuh-agent_3.5.0-1_amd64.deb

**Comment by alphaDev23** [comment]
The documentation should be updated to reflect the fact that Debian packages are untested.  There is no mention that apt-get packages are not tested or that it is broken at: https://documentation.wazuh.com/current/installation-guide/installing-wazuh-agent/wazuh_agent_deb.html

Hopefully, this comment will save others from wasting time trying to install untested packages using apt-get until #32 and this defect are resolved.

**Comment by snaow** [comment]
Hi @alphaDev23,

Thanks for the feedback, it's really welcome.
We are working on fixing the package for the scenario you reported.

Clean and upgrade installations work properly, I and the team just test the documentation guide and works fine.
I can confirm as well the package installation is not working in the scenario you describe, if apt/package manager fails in the middle of the installation, the package can't be installed right away again, you need to purge/remove previous files manually and perform a clean installation to make it work.
We are working on fixing this as I write this issue, my colleague @BraulioV will attach here a 3.5 package version so you can use it in your environment.
The fix will be included in the next Wazuh release.

In the meantime, if you want to perform a clean installation, you can run:

`rm -rf /var/ossec && dpkg --purge wazuh-agent && dpkg -i wazuh-agent_3.5.0-1_amd64.deb`

I hope it helps, best regards,
Pedro.

**Comment by alphaDev23** [comment]
There may be several other apt-get commands that need to be tested which are commonly expected to work without issue, e.g. apt-get install -f (which did not fix the wazuh-agent broken install). 

When functionality, especially common functionality, goes untested it not only wastes my time but also potentially many others. Within half a day of using Wazuh, I entered 4 unique issues (this count does not include #33 which was closed).  Each of these issues takes time to determine if the issue is with Wazuh, with dependencies, missed instruction detail, setting, etc. and then to actually write up the issue and communicate back and forth regarding it.

As a note, I was able to install via a package download directly although MD5 checksums are provided to verify packages which are susceptible to hashing collisions (see #34).

**Comment by BraulioV** [comment]
Hi @alphaDev23,

see attached the wazuh-agent .deb package with this issue solved. This issue has been solved in this commit: https://github.com/wazuh/wazuh-packages/commit/27ee216f4cef75498ca17ea45f5bba59a3ff6acc, please feel free to send us more feedback.

Regards,
Braulio.
[wazuh-agent_3.5.0-2_amd64.deb.zip](https://github.com/wazuh/wazuh-packages/files/2325587/wazuh-agent_3.5.0-2_amd64.deb.zip)

PS: you will need to extract the .deb from the .zip file. GitHub doesn't allow to attach .deb files.

**Comment by alphaDev23** [comment]
I appreciate the quick turnaround for responses; however, the issue was not the deb package itself.  That installed without issue even with the broken install.  The issue was the package in Ubuntu's 14.04 and 16.04 (possibly 18.04 but I did not attempt) repositories (accessible via apt-get).

**Comment by BraulioV** [comment]
Hi @alphaDev23 ,

the packages of the repository will fail only if the `/tmp/wazuh-*****` exists but in normal cases, they will work. By the way, we will release a new version of Wazuh very soon so this problem will be fixed with the new packages.

Regards,
Braulio.

**Comment by alphaDev23** [comment]
Thank you for fixing the issue.  Ensuring that the package management installs work as expected, and to recover from issues using the standard tools, is important especially given that the Wazuh agent is installed on numerous machines.
