### ISSUE TITLE
Update SPEC files for Wazuh 3.12.x 

### ISSUE THREAD

**Issue by grg121** [wazuh/wazuh-packages#354]
Hello team,

The RPM SPECS files must be updated for Wazuh 3.12.x in order to avoid failures such as the following during package generation: 

```java
11:58:48      RPM build errors:
11:58:48          Installed (but unpackaged) file(s) found:
11:58:48         /var/ossec/api/configuration/ssl/server.crt
11:58:48         /var/ossec/api/configuration/ssl/server.key
11:58:48    stdout_lines: <omitted>
11:58:48  ...ignoring
```
https://jenkins-production.wazuh.info/job/Build_rpm_packages/2893/console

Best regards,

**Comment by BraulioV** [comment]
Closed by #353
