### ISSUE TITLE
Ubuntu 12 / Debian 7 wazuh-api service does not start after package installation

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#362]
Hello team

  We noticed that the Wazuh API installation on Ubuntu 12 and Debian 7 has the following problem: the service does not start automatically after the installation. This is unexpected behaviour, the service must start after finish the installation. 

Best regards, 
Alberto R

**Comment by BraulioV** [comment]
Hi all,

We've been doing some tests to check what's happening with the .deb packages in Debian 7 and Ubuntu 12. First, we found something really interesting related to the installation of the package using directly `dpkg` and `apt-get`.

If you install the package using `dpkg` the package can start the Wazuh API service without problems, working as expected and as in newer OS. If the package is installed using `apt-get`, the service is not able to start. In addition, is like the package didn't execute `service wazuh-api start`.

A possibility that we are studying is that `apt-get` use a very limited `PATH` and the binaries used to start the service can't be executed from the post-install script.

**Comment by BraulioV** [comment]
Hi team,

With the release of Wazuh 4.x we've reworked the Wazuh API, moving it to Python and installing it alongside the Wazuh Manager. This means the Wazuh API package won't be necessary once we released Wazuh v4.0.0, the Wazuh API service will no longer exist and this problem has been solved with the rework of the API.

I'm closing this issue but feel free to re-open it if you consider it.

Regards.
