### ISSUE TITLE
Agents-timestamp file being deleted when upgrading by packages.

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-packages#377]
Hello team, a user has reported an inconsistent behavior when upgrading wazuh from packages. I detail the information below:

## Description
The file `agents-timestamp` located in `/var/ossec/queue` is a file which is used to put the agent registration dates back into the database after upgrading wazuh. The user wanted to edit the registration dates of the agents, for which it is necessary to upgrade after modifying the file. However, as he reports, the file is deleted when upgrading by packages.

## Expected behavior

The expected behavior and the one that is fulfilled when updating by sources is that the existing agents-timestamp file is maintained when upgrading in order to recover the information from it.

## How to reproduce the error

While on wazuh 3.10.2 with at least a registered agent:
- Check that the registration date matches the one of the agents-timestamp file: `curl -u foo: bar "http://localhost:55000/agents"`
- Modify `/var/ossec/queue/agents-timestamp` file with different dates.
- If we upgrade to wazuh 3.11.1 by sources, the file is maintained and calling the api shows the edited dates `curl -u foo: bar "http://localhost:55000/agents"`
- If we upgrade to wazuh 3.11.1 by packages, the file is deleted and is not loaded into the database. The dates shown when calling the api are the same as before editing the file.

Here is the user's message in case it helps. https://groups.google.com/d/msg/wazuh/td6bAVmxTjg/7B7O5dd9DQAJ

Kind regards,
Jose Luis.

**Comment by BraulioV** [comment]
Hi @Selutario ,

Sorry for the late response. I marked this as `wontfix` because the `agents-timestamp` file is no longer used in Wazuh 4.x. The registration dates of the agents are recorded in the global.db as a timestamp. 
```shellsession
[root@e81e0ea69efd /]# sqlite3 /var/ossec/queue/db/global.db
SQLite version 3.7.17 2013-05-20 00:56:22
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> select date_add from agent where id==001;
1608030538
```
Also, the `global.db` is now fully managed by `wazuh-db`, so the package doesn't interact with it.

I'm closing this issue, but if you have any other questions, feel free to reopen it.
