### ISSUE TITLE
Windows installer can't install with password

### ISSUE THREAD

**Issue by darkpixel** [wazuh/wazuh-packages#380]
I generated a transform for the Windows installer with the variables I need.

When I deploy the file, I get the following error:

```Product: Wazuh Agent -- Error 1721. There is a problem with this Windows Installer package. A program required for this install to complete could not be run. Contact your support personnel or package vendor. Action: CustomAction_NoGroup_NoName_RunAuthd_Password, location: C:\Program Files (x86)\ossec-agent\, command: C:\Program Files (x86)\ossec-agent\agent-auth.exe -m mymanager.tld -p 1515 -P mypassword```

I also tried with the original variable names and get the same results.

**Comment by darkpixel** [comment]
Changing to the proper directory and running that exact command that is listed in the event viewer as having a problem worked perfectly and allowed the service to start and begin reporting.

**Comment by darkpixel** [comment]
![Screenshot from 2020-01-21 13-33-29](https://user-images.githubusercontent.com/158380/72943656-7db31d80-3d2b-11ea-8838-e2643546e3aa.png)

**Comment by DFolchA** [comment]
Hello @darkpixel,

I was able to create an MST by using the WIX Toolset `burn.exe` too and it worked correctly for me, I guess you already know how to do it but ill explain the process for clarity.

First, you need  to  build a custom MSI with your desired auto-deployment variables already set in the WXS file, to do this you can use the tools provided in this repository:

https://github.com/wazuh/wazuh-packages/tree/master/windows

Before running the `generate_wazuh_msi.ps1` script just edit the WXS file and set the properties in these lines as you like:

https://github.com/wazuh/wazuh/blob/2ccb1f40b2d123933964bfd3763e7beb60c29bc9/src/win32/wazuh-installer.wxs#L6-L31

You should end with something similar to this:

```
        <Property Id="WAZUH_MANAGER" Secure="yes">"MANAGER_IP"</Property>
        <Property Id="WAZUH_MANAGER_PORT" Secure="yes">
        </Property>
        <Property Id="WAZUH_PROTOCOL" Secure="yes">
        </Property>
        <Property Id="WAZUH_REGISTRATION_SERVER" Secure="yes">"REGISTRATION_IP"</Property>
        <Property Id="WAZUH_REGISTRATION_PORT" Secure="yes">1515</Property>
        <Property Id="WAZUH_REGISTRATION_PASSWORD" Secure="yes">PASSWORD</Property>
        <Property Id="WAZUH_KEEP_ALIVE_INTERVAL" Secure="yes">
        </Property>
        <Property Id="WAZUH_TIME_RECONNECT" Secure="yes">
        </Property>
        <Property Id="WAZUH_REGISTRATION_CA" Secure="yes">
        </Property>
        <Property Id="WAZUH_REGISTRATION_CERTIFICATE" Secure="yes">
        </Property>
        <Property Id="WAZUH_REGISTRARTION_KEY" Secure="yes">
        </Property>
        <Property Id="WAZUH_AGENT_NAME" Secure="yes">
        </Property>
        <Property Id="WAZUH_AGENT_GROUP" Secure="yes">
        </Property>
```

Next, run `generate_wazuh_msi.ps1` to generate the custom MSI.

Now  download the official MSI that you can find at our documentation:

https://documentation.wazuh.com/3.12/installation-guide/packages-list/#packages.python_paths

And use torch.exe with the two MSI files:

```
torch.exe wazuh-agent-3.12.0-1.msi custom-wazuh-mis.msi -out wazuh-agent.mst
``` 

With this MST you can automatically set the deployment variables automatically and it should work for all versions.

```
.\wazuh-agent-3.12.0-1.msi FORMAT="wazuh-agent.mst" /q
```

Lastly, make sure you have permission to run programs from the installer as it seems that your system is preventing `agent_auth.exe` at installation time.

For future questions consider using our mailing list, I am sure everyone will be happy to help you with anything you need.

Regards,
Daniel Folch

**Comment by darkpixel** [comment]
Aah....I was using InstEd to generate a transform, and applying it using ```TRANSFORM=mytransform.mst```

Unfortunately the project has been put on hold due to 'current events'.  I'll give it a shot when they pick it back up again.
