### ISSUE TITLE
Solaris 10 package contains error lines in log in a fresh install

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-packages#385]
Hi team,

We found two error lines in the `ossec.log` after doing a fresh install of the Solaris 10 package. Here you can see both lines:
```log
2020/01/28 13:37:03 ossec-agentd: ERROR: (4112): Invalid server address found: 'MANAGER_IP'
2020/01/28 13:37:03 ossec-agentd: CRITICAL: (1215): No client configured. Exiting.
```
Probably, the build script is starting the agent while the package is being built, those lines are logged in the log file and then, this log file is packaged with the rest of the files.

We must review and fix this.

**Comment by DFolchA** [comment]
Hello team,

I have found the root of this issue and fixed it in this branch:
https://github.com/wazuh/wazuh-packages/tree/385-solaris10-error-in-log

Also added option to generate WPKs for different installation paths than /var/ossec.

Regards.
