### ISSUE TITLE
Create 'queue/fim/db' folder in agent's installation

### ISSUE THREAD

**Issue by DaveVG1** [wazuh/wazuh-packages#387]
|Wazuh version|Install type|
|---|---
| [3319-fim-rework-sqlite](https://github.com/wazuh/wazuh/tree/3319-fim-rework-sqlite) | Agent |

In order to accomplish the SQLite development for the FIM rework the agent's installation should create a folder in `INSTALLATION_FOLDER/queue/fim/db`.

This folder is already present in the manager, but it will also be necessary for the agent (as it's going to have the database in that folder).

This folder must be deleted while uninstalling.

### IMPORTANT
The fix for this issue **should not** be merged until it's decided if the SQLite integration is going to make it to the final development of the FIM rework.

**Comment by alberpilot** [comment]
Hello
Fixed here: https://github.com/wazuh/wazuh-packages/commit/a44943b3e1d6cc3d6ec69828a77e0bc39d1e227f.

Regards, 
Alberto R

**Comment by okynos** [comment]
Hello team,

This fix also need to be added to the manager, we will reopen it.

Regards.
