### ISSUE TITLE
Add a tool to build Solaris packages.

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-packages#43]
Hi team,

as said in #42, it is necessary to add a new tool to build the Solaris packages using `fpm`. 

Tasks to do:
- [ ] Build the Dockerfile with all the dependencies needed to build the package.
- [ ] Build a new script to generate the package using fpm.
- [ ] Add the` preinstall`, `postinstall`, `preremove` and `postinstall` scripts.
- [ ] Add support for Solaris 10.
- [ ] Add support for Solaris 11.
- [ ] Check the compatibility with SPARC architecture.
- [ ] Test.

Regards.

**Comment by alberpilot** [comment]
Done.
BR, 
Alberto R
