### ISSUE TITLE
RedHat wazuh agent v3.11.2 installation path

### ISSUE THREAD

**Issue by Aviv641999** [wazuh/wazuh-packages#452]
Hi,
I am trying to compile redhat wazuh agent version 3.11.2 in custom directory.

`./generate_rpm_package.sh -b v3.11.2 -t agent -a x86_64 -p /var/myAgent`

And it create the items in **/var/myAgent/ossec/**

```
[root@redhat ~]# cd /var/myAgent/ossec/
[root@redhat ossec]# ls
active-response  agentless  backup  bin  etc  lib  logs  queue  ruleset  tmp  var  wodles
```

However in ubuntu build package it create the items in **/var/myAgent/**

```
[root@ubuntu ~]# cd /var/myAgent
[root@ubuntu myAgent]# ls
active-response  agentless  backup  bin  etc  lib  logs  queue  ruleset  tmp  var  wodles
```

Is there any option to move the redhat agent to **/var/myAgent** directory like ubuntu?

**Comment by BraulioV** [comment]
Hi @Aviv641999,

For .rpm packages that isn't possible yet. The directory is defined as `path_variable/ossec`: https://github.com/wazuh/wazuh-packages/blob/332485a1d22c857cb618a1fd8e1e6f814a162fc8/rpms/SPECS/3.13.0/wazuh-manager-3.13.0.spec#L732-L738

We are preparing a fix to unify both options and be able to create .deb and .rpm with the path defined with the `-p` parameter, without the `ossec` directory.

I'll keep you updated.

Regards.

**Comment by BraulioV** [comment]
Hi again @Aviv641999,

Now you can build RPM packages for `/var/myAgent` without any issues. We have removed the `ossec` subdirectory from the build path in #453 .

Best regards,
Braulio.
