### ISSUE TITLE
No such file exists /var/ossec/ruleset/sca/cis_debian7_L2.yml, during manager upgrade.

### ISSUE THREAD

**Issue by jeffdyke** [wazuh/wazuh-packages#455]
| Wazuh version | Component | Install type | Install method | Platform |
|---|---|---|---|---|
Wazuh Version 3.13.1 | Manager | Installed from apt using `deb https://packages.wazuh.com/3.x/apt stable main` | Packages | Ubuntu 18.04.4 | 

I have actually seen this in the last couple upgrades to the manager, the root issue seems to be that `restore-permissions.sh` contains `chmod` and `chown` directives for files that do not exist in `/var/ossec/packages_files/manager_installation_scripts/restore-permissions.sh`

To fix this i go into that file and delete the following entries
```
chown -- 'root:ossec' '/var/ossec/ruleset/sca/cis_debian7_L2.yml'
chmod 640 '/var/ossec/ruleset/sca/cis_debian7_L2.yml'
chown -- 'root:ossec' '/var/ossec/ruleset/sca/cis_debian9_L2.yml.disabled'
chmod 640 '/var/ossec/ruleset/sca/cis_debian9_L2.yml.disabled'
chown -- 'root:ossec' '/var/ossec/ruleset/sca/cis_debian7_L1.yml'
chmod 640 '/var/ossec/ruleset/sca/cis_debian7_L1.yml'
chown -- 'root:ossec' '/var/ossec/ruleset/sca/cis_debian9_L1.yml.disabled'
chmod 640 '/var/ossec/ruleset/sca/cis_debian9_L1.yml.disabled'
```
Then i usually get a response that `APT had planned for dpkg to do more than it reported back (0 vs 4).` so as root i run `dpkg --configure -a` then update the package and since those are gone from the bash script, everything works fine and `/var/ossec/package_files` directory is removed. 

Happy to answer any questions, there is nothing creating about this setup been using it for about 3 years since moving away from OSSEC.  I think this is the 3rd manager upgrade that has had this issue.

Jeff

**Comment by BraulioV** [comment]
Hi @jeffdyke,

First, I transferred the issue from wazuh/wazuh to this repository. Here we have all our packages specs files and tools to build binary packages, issue trackers, etc.

That file is used to set the correct user, group, and permissions of each file. It is dynamically created while building the binary package: https://github.com/wazuh/wazuh-packages/blob/2a3fb4a5b6ec97f9227664c5b597ab8b74059962/debs/SPECS/3.13.1/wazuh-manager/debian/rules#L85

Then, it is executed in the `postinstall` script: https://github.com/wazuh/wazuh-packages/blob/2a3fb4a5b6ec97f9227664c5b597ab8b74059962/debs/SPECS/3.13.1/wazuh-manager/debian/postinst#L132-L133

This script comes very legacy code and we are planning to remove it for the next major release but, our CI environment has never reported any issue related to this file.  Do you have any special configuration in this file `/etc/dpkg/dpkg.cfg` or `/etc/dpkg/dpkg.cfg.d/*`?

Thank you for your feedback.
