### ISSUE TITLE
 Uninstalling by MSI package maintains more content than desired 

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh-packages#47]
Empty directories:
- active-response
- bookmarks
- logs
- queue/diff
- merge.mg
- syscheck
- upgrade

Files:
- .agent_info
- last-ossec.conf
- ossec-agent.state
- wodles/syscollector

**Comment by chemamartinez** [comment]
Solved at https://github.com/wazuh/wazuh/pull/1519
