### ISSUE TITLE
Debian packages: No notification if ossec.conf was changed between releases

### ISSUE THREAD

**Issue by kdslkdsaldsal** [wazuh/wazuh-packages#5]
Hi,

after doing a fresh installation of a wazuh-agent 2.1.0 on Debian i've noticed that the ossec.conf of that agent differs to a host where the wazuh-agent 2.0.0 was installed initially. However there was no notice about this changes during the upgrade of that package like commonly done in Debian packages.

Could it be possible to notice the user during the package upgrade if the config was changed? An alternative could be to place a e.g. ``ossec.conf.changed`` side-by-side to the ossec.conf for easier comparison.

If this is something which can't be handled on package level it probably could also be handled by adding a note to compare the ossec.conf at https://documentation.wazuh.com/current/installation-guide/upgrading/index.html

*Edit*

Sorry, forgot to mention that both packages, wazuh-manager and wazuh-agent are affected. e.g. i currently was missing the following in my ossec.conf of manager and agent:

```
  <!-- Choose between plain or json format (or both) for internal logs -->
  <logging>
    <log_format>plain</log_format>
  </logging>
```

as well as the netstat changes from https://github.com/wazuh/wazuh/pull/145

**Comment by erseco** [comment]
Hi, 
Upgrading a minor package release (`2.x.x` to `2.1.x`) will not overwrite the `ossec.conf` file. 
If you have a previous configuration this will remain in `/var/ossec/etc/ossec.conf`. This is mandatory to prevent the previous configuration from being lost.

In case that you want to force an upgrade of the configuration file you can rename your current `ossec.conf` file before the upgrade to get the new `ossec.conf` file and after that apply manually your changes to the new configuration file.

Best regards!

**Comment by kdslkdsaldsal** [comment]
Hey, thanks for your reply. I think there are a few possibilities like you have explained to handle this.

But i'm seeing this from user perspective without knowing such details. Currently you won't get any notice at all if some config entries where added / changed on minor releases (i don't know how often this happens).

AFAIK on many Debian packages this is handled by marking the ossec.conf as a "config" file and by shipping a default config within the package. The package manager then somehow knows that the file got changed and is offering a possibility to the user to keep the local file version, choose the package maintainers file version or show the difference between the new and old file.

But from what i see the ossec.conf gets created dynamically during the installation? If yes then there are probably only two ways left to solve / improve this:

1. If the ossec.conf already exists create a new one (e.g. ossec.conf.orig) side by side to the ossec.conf. This could easily allow to compare the current ossec.conf with the default ossec.conf of that next release.

2. Add the info to rename the ossec.conf to e.g. ossec.conf.old before the package update to the updating/upgrading manuals at https://documentation.wazuh.com/current/installation-guide/upgrading/index.html and explain that the local changes needs to be applied afterwards.

Any opinions about this?

**Comment by jlruizmlg** [comment]
Hi @kdslkdsaldsal 

About mark ossec.conf as "config", in our experience this option causes many problems, although not technically the problem is in the human side; a high number of configurations have been lost using that option because the habitual answer of "yes", often times without reading the questions.

About your two options, i think the best is option is the first one, we can create a ossec.conf.new or something like that with the last configurations available, and then if you want move your actual configuration to this new file.

**Comment by erseco** [comment]
Hi @kdslkdsaldsal, 

Now in the new `3.0.0` deb packages if you are upgrading from a previous version the package maintains the previous `ossec.conf` file and save a new default configuration file in `/var/ossec/etc/ossec.conf.new`

This packages will be available very soon!

Best regads
