### ISSUE TITLE
Wazuh API CentOS 7

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-packages#50]
`yum install wazuh-api-3.6.1` + `yum remove wazuh-api` + `yum install wazuh-api-3.6.1`

```
cp: cannot stat '/var/ossec/api/configuration/auth/htpasswd': No such file or directory
cat: /var/ossec/~api/package.json: No such file or directory
/var/tmp/rpm-tmp.lIMJKu: line 16: =: command not found
```

/var/ossec/api/configuration is the problem

**Comment by BraulioV** [comment]
Hi @jesusgn90,

this issue is caused by this code: https://github.com/wazuh/wazuh-packages/blob/49b58bdebbd88ba2532e5909f76b1c9492f26461/rpms/SPECS/3.6.1/wazuh-api-3.6.1.spec#L79-L89

I'm investigating how to solve it.

**Comment by BraulioV** [comment]
For now, the best fix is to delete the `/var/ossec/api` directory when removing the package. This is done in https://github.com/wazuh/wazuh-packages/commit/e45042fe35acbf648cfaaaa97a2b1e331007fb8d but, those lines need an improvement. 

This improvement will be done in #21.

Regards,
Braulio.

**Comment by BraulioV** [comment]
After discussing this issue with the team, changing the `ossec-init.conf` will cause problems in the Wazuh app because this date is considered as the _compilation date_ and not the installation date.
