### ISSUE TITLE
Debian install fails because of large quantity of files in directory

### ISSUE THREAD

**Issue by jcarr** [wazuh/wazuh-packages#533]
When installing debian packages, I believe this becomes a problem when one of the directories fills up and the `rm` command has too many arguments.  This causes the installation to fail and puts the `/var/ossec` directory into a weird state that prevents existing installations from working and prevents new installations.

https://github.com/wazuh/wazuh-packages/blob/f8a7331df6a2af0475ca6296f67aeca9dc2b82f2/debs/SPECS/4.0.0/wazuh-manager/debian/preinst#L104
https://github.com/wazuh/wazuh-packages/blob/f8a7331df6a2af0475ca6296f67aeca9dc2b82f2/debs/SPECS/4.0.0/wazuh-manager/debian/preinst#L109

**Comment by okynos** [comment]
Hello @jcarr,

Sorry for the late reply. Could you send us the trace or the steps to reproduce your issue? Please send us the following information:
1. Operating system version.
2. System Specifications.
3. Did you perform an upgrade or a clean installation?
4. There was a custom package or official packages.wazuh.com package?
5. Did you use dpkg or apt?

Meanwhile, could you test the latest official packages at the moment of writing? 4.1.4

Regards.

**Comment by alberpilot** [comment]
I proceed to close this issue due to inactivity. Please don't hesitate to open it again if needed. 

Regards, 
Alberto
