### ISSUE TITLE
Fix wazuh-logtest group on RPM package

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-packages#542]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.1.0 | Manager | Install | RPM |

Hello team,

We have detected that wazuh-logtest have different permission mask on RPM than DEB packages, we must fix RPM one changing the group to `ossec` instead of `root`.

Regards.

**Comment by jnasselle** [comment]
Hi team!

This issue still exist on Wazuh 4.2.0 so i'll reopen and fix it.

Regards,
Nico
