### ISSUE TITLE
Apply Wazuh tools name changing to the package specs

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-packages#547]
### Description

According to the changes proposed at [#6766](https://github.com/wazuh/wazuh/issues/6766), the following tools will be renamed or totally removed from new Wazuh installations.

- `ossec-control` -> `wazuh-control`
- `ossec-regex` -> `wazuh-regex`
- `rootcheck_control` -> Removed
- `syscheck_control` -> Removed
- `syscheck_update` -> Removed
- `ossec-logtest` -> Removed (it was replaced by `wazuh-logtest`)
- `ossec-makelists` -> Removed

In the package SPECS there exist references to these tools. For example, when trying to build an RPM package we get the following error:

```
RPM build errors:
    File not found: /build_wazuh/rpmbuild/BUILDROOT/wazuh-manager-4.1.0-1.x86_64/var/ossec/bin/ossec-control
    File not found: /build_wazuh/rpmbuild/BUILDROOT/wazuh-manager-4.1.0-1.x86_64/var/ossec/bin/ossec-regex
```

In addition, CDB lists are no longer built when installing the manager. Therefore, files with the extension `.cdb` are generated when the manager starts instead of when it is installed.

### Requirements

- Old tools should be removed on upgrades

Best regards.

**Comment by jmv74211** [comment]
Hello team,

I have already made the necessary changes in the SPECS of 4.2.0 (see https://github.com/wazuh/wazuh-packages/commit/eab5da74569808804bf6e0a31f5c771a9ba24cc4). In order to test them, I need the `wazuh/wazuh` branch where the changes have been applied (`6766-change-wazuh-tools-name`), to be bumped to version `4.2.0`, since it is currently in `4.1.0` (see https://github.com/wazuh/wazuh/blob/6766-change-wazuh-tools-name/src/VERSION).

Best regards.

**Comment by jmv74211** [comment]
Hello team,

After testing the changes, it seems that the package does not build correctly because there may be some additional changes that have not been described in the issue.

```
13:41:04  Processing files: wazuh-manager-4.2.0-jmv74211.change.tools.name.x86_64
13:41:04  error: File not found: /build_wazuh/rpmbuild/BUILDROOT/wazuh-manager-4.2.0-jmv74211.change.tools.name.x86_64/var/ossec/bin/util.sh
13:41:04  error: File not found: /build_wazuh/rpmbuild/BUILDROOT/wazuh-manager-4.2.0-jmv74211.change.tools.name.x86_64/var/ossec/etc/lists/audit-keys.cdb
13:41:04  error: File not found: /build_wazuh/rpmbuild/BUILDROOT/wazuh-manager-4.2.0-jmv74211.change.tools.name.x86_64/var/ossec/etc/lists/security-eventchannel.cdb
13:41:04      File not found: /build_wazuh/rpmbuild/BUILDROOT/wazuh-manager-4.2.0-jmv74211.change.tools.name.x86_64/var/ossec/bin/util.sh
13:41:04  RPM build errors:
13:41:04      File not found: /build_wazuh/rpmbuild/BUILDROOT/wazuh-manager-4.2.0-jmv74211.change.tools.name.x86_64/var/ossec/etc/lists/audit-keys.cdb
13:41:04      File not found: /build_wazuh/rpmbuild/BUILDROOT/wazuh-manager-4.2.0-jmv74211.change.tools.name.x86_64/var/ossec/etc/lists/security-eventchannel.cdb
```

I am waiting for indications about this.
