### ISSUE TITLE
Adapt Linux specs to include new SCA policies in the version 5.0

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh-packages#557]
### Description

As part of the epic https://github.com/wazuh/wazuh-ruleset/issues/784, it was necessary to create version 5.0 of all the packages. This version was created in the middle of the fix for issue #536 in which the specs were updated to include the new SCA policies. So the new SCA policies should be present also in version 5.0 of the packages.

**Comment by pereyra-m** [comment]
This issue has become obsolete, because the `master` branch already has all the proposed changes in #558.
Also, they weren't related to the **Ruleset normalization to Wazuh standard** wazuh/wazuh-ruleset#812.
