### ISSUE TITLE
Apply Wazuh daemons name changing to the package specs

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-packages#562]
### Description

According to the changes proposed at [#6741](https://github.com/wazuh/wazuh/issues/6741), the following daemons will be renamed or totally removed from new Wazuh installations.

- Unix:
  - `ossec-agentd` -> `wazuh-agentd`
  - `ossec-agentlessd` -> `wazuh-agentlessd`
  - `ossec-analysisd` -> `wazuh-analysisd`
  - `ossec-authd` -> `wazuh-authd`
  - `ossec-csyslogd` -> `wazuh-csyslogd`
  - `ossec-dbd` -> `wazuh-dbd`
  - `ossec-execd` -> `wazuh-execd`
  - `ossec-integratord` -> `wazuh-integratord`
  - `ossec-logcollector` -> `wazuh-logcollector`
  - `ossec-maild` -> `wazuh-maild`
  - `ossec-monitord` -> `wazuh-monitord`
  - `ossec-remoted` -> `wazuh-remoted`
  - `ossec-reportd` -> `wazuh-reportd`
  - `ossec-syscheckd` -> `wazuh-syscheckd`

- Windows:
  - `ossec-agent.exe` -> `wazuh-agent.exe`
  - `ossec-agent-eventchannel.exe` -> `wazuh-agent-eventchannel.exe`
  - `ossec-rootcheck.exe` -> deprecated
  - `OssecSvc` -> `WazuhSvc`

In the package SPECS there exist references to these daemons.

Example error build (RPM manager): https://github.com/wazuh/wazuh/pull/6813/checks?check_run_id=1539528102

```
Processing files: wazuh-manager-4.1.0-0.commit828762d.x86_64
error: File not found: /build_wazuh/rpmbuild/BUILDROOT/wazuh-manager-4.1.0-0.commit828762d.x86_64/var/ossec/bin/ossec-agentlessd
error: File not found: /build_wazuh/rpmbuild/BUILDROOT/wazuh-manager-4.1.0-0.commit828762d.x86_64/var/ossec/bin/ossec-analysisd
error: File not found: /build_wazuh/rpmbuild/BUILDROOT/wazuh-manager-4.1.0-0.commit828762d.x86_64/var/ossec/bin/ossec-authd
error: File not found: /build_wazuh/rpmbuild/BUILDROOT/wazuh-manager-4.1.0-0.commit828762d.x86_64/var/ossec/bin/ossec-csyslogd
error: File not found: /build_wazuh/rpmbuild/BUILDROOT/wazuh-manager-4.1.0-0.commit828762d.x86_64/var/ossec/bin/ossec-dbd
error: File not found: /build_wazuh/rpmbuild/BUILDROOT/wazuh-manager-4.1.0-0.commit828762d.x86_64/var/ossec/bin/ossec-execd
error: File not found: /build_wazuh/rpmbuild/BUILDROOT/wazuh-manager-4.1.0-0.commit828762d.x86_64/var/ossec/bin/ossec-integratord
error: File not found: /build_wazuh/rpmbuild/BUILDROOT/wazuh-manager-4.1.0-0.commit828762d.x86_64/var/ossec/bin/ossec-logcollector
error: File not found: /build_wazuh/rpmbuild/BUILDROOT/wazuh-manager-4.1.0-0.commit828762d.x86_64/var/ossec/bin/ossec-maild
error: File not found: /build_wazuh/rpmbuild/BUILDROOT/wazuh-manager-4.1.0-0.commit828762d.x86_64/var/ossec/bin/ossec-monitord
error: File not found: /build_wazuh/rpmbuild/BUILDROOT/wazuh-manager-4.1.0-0.commit828762d.x86_64/var/ossec/bin/ossec-remoted
error: File not found: /build_wazuh/rpmbuild/BUILDROOT/wazuh-manager-4.1.0-0.commit828762d.x86_64/var/ossec/bin/ossec-reportd
error: File not found: /build_wazuh/rpmbuild/BUILDROOT/wazuh-manager-4.1.0-0.commit828762d.x86_64/var/ossec/bin/ossec-syscheckd
```

### Requirements

- Old daemons should be removed on upgrades.

**Comment by jnasselle** [comment]
Hi team!

Solaris 11 agent package SPECS still refer `ossec-agentd.state` as state file for `wazuh-agentd` (issue here: wazuh/wazuh#6770), while currently is `wazuh-agentd.state`.

Regards,
Nico
