### ISSUE TITLE
Update the packages to take the oscap content from the new location in the wazuh repository

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh-packages#568]
### Description

This is a tracking purposes issue to reflect the changes introduced in the packages as part of the issue https://github.com/wazuh/wazuh/issues/6915 and the epic https://github.com/wazuh/wazuh/issues/6898.

As part of this issue, the packages should be modified in order to take the `oscap` content from the new location within the `wazuh` repository.

**Comment by palaciosjeremias** [comment]
Closing this issue because **wazuh/wazuh#6915** doesn't require any change of the packages.
