### ISSUE TITLE
Maintainer scripts doesn't work as expected.

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-packages#58]
Hi team, 

currently, the maintainer scripts of the .deb packages are too generic. The flow charts that you can see here https://wiki.debian.org/MaintainerScripts show how the package must work for all the cases, but, in the maintainer scripts you can see that for many cases, the package will execute the same code: https://github.com/wazuh/wazuh-packages/blob/084e06b68636236a2f3b3f8f555d6c40b03a9208/debs/SPECS/3.7.0/wazuh-manager/debian/postrm#L8-L10

This may cause errors and leave the package in an inconsistent state.

**Comment by alberpilot** [comment]
Pending for new major Wazuh-packages implementation
