### ISSUE TITLE
Add macOS SCA policies to packages SPECS

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-packages#587]
Hi team,

New SCA policies are being added for macOS platforms:

- macOS Mojave (10.14): https://github.com/wazuh/wazuh/pull/7035
- macOS Catalina (10.15): https://github.com/wazuh/wazuh/pull/7036
- macOS Big Sur (11.01 - 11.1): https://github.com/wazuh/wazuh/pull/7037

In the core repository, changes have been added to the SCA templates in order to add support for the new policies (https://github.com/wazuh/wazuh/pull/7039).

Packages SPECs should be adapted to include the new policies as well.

Best regards.

**Comment by alberpilot** [comment]
Merged. Thanks
