### ISSUE TITLE
Use conffiles in debian scripts 

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-packages#59]
Hi team,

the .deb packages don't use the `conffiles` feature to prevent the overwrite of the important files as `ossec.conf`, `client.keys`, `local_internal_options.conf`, etc. For this reason, we must create some "`tmp`" directory to save these files while upgrading to avoid the overwrite. 

More info about the `conffiles` here: https://www.debian.org/doc/manuals/maint-guide/dother.en.html#conffiles

PS: if `conffiles` option is used, it is possible that we must create a new directory in the packages to make this work properly.

**Comment by alberpilot** [comment]
Pending for new major Wazuh packages implementation
