### ISSUE TITLE
Adapt SPECS to the compilation changes from Wazuh core

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-packages#611]
Hi team,

This issue describes some changes that will be applied at the Wazuh's compilation that may affect the package building process. High-level changes are described at https://github.com/wazuh/wazuh/issues/6938.

- The flag `PREFIX` will be deprecated from the `make deps`. It is no longer needed to specify a destination path.

- A flag called `PYTHON_SOURCE` is added to download the python interpreter sources instead of the pre-installed one. This flag can be enabled with values `YES`, `yes`, `y`, `Y`, `1` but is disabled by default.

- The flag `PREFIX` is also deprecated when compiling the Wazuh binaries since the compilation does no longer depend on the installation path. However, it will be also used to call the Makefile for other purposes such as the API installation.

- The flag `USE_FRAMEWORK_LIB` is deprecated. It appears in the RPM SPECS.

- The `libsqlite3.so.0` is no longer installed as well.

Please, ask @wazuh/core for any questions.

Best regards,
Chema.

### Update

- Finally, the `PREFIX` flag is renamed to `INSTALLDIR`. This flag will be needed when the python interpreter has to be built, since the configure script should know where the interpreter will be installed. Here you can see the standard use of this flag:
```
# make deps TARGET=server PYTHON_SOURCE=yes
# make TARGET=server INSTALLDIR=/var/ossec
```

**Comment by DFolchA** [comment]
### STATUS REPORT

Change PREFIX tag to INSTALLDIR and test packages.

**Comment by DFolchA** [comment]
### STATUS REPORT

**Working branch:** https://github.com/wazuh/wazuh-packages/tree/611-compilation-changes

Finish SPECS changes in:
- RPM
- DEB
- macOS
- Solaris 10
- Solaris 11

Test packages.
