### ISSUE TITLE
Make sure services are restarted after upgrade

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#625]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.2.0| Manager/Agent | Upgrade | RPM/DEB|

Hello team,

We noticed that after updating Wazuh from 4.0.x to 4.2.0, in some cases the old services are not properly stopped, this is due to an inconsistency in systemctl that appears if we use ossec-control to start Wazuh.

Here we can see how after upgrading the old pid files are still present in `/var/ossec/var/run`.
![image](https://user-images.githubusercontent.com/19505384/106443515-da87fe80-647c-11eb-9c21-a0fb5ea8ad53.png)

Regards,
Daniel Folch

**Comment by alberpilot** [comment]
Solved with: https://github.com/wazuh/wazuh-packages/issues/723
