### ISSUE TITLE
Build tool for AIX

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh-packages#63]
Hi team,

It is necessary to add a build tool for IBM AIX packages, similar to the one that we have for Linux RPM packages.

Regards.

**Comment by BraulioV** [comment]
Hi team,

I added in this commit https://github.com/wazuh/wazuh-packages/commit/008f1c3b981135025c4c6b859ef3e05c3be21f7e a script to build the RPM packages for IBM AIX and the RPM specs. 

Best regards.
