### ISSUE TITLE
Installation with deployment variables should modify enrollment configuration

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-packages#633]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.0.4 | Agent | Install | Windows/Linux/macOS |

As of https://github.com/wazuh/wazuh/pull/5609 the Wazuh agent has an auto-enrollment functionality that allows it to automatically negotiate a key with a Wazuh manager if it doesn't already have one or if the manager rejects a message. 

If the manager is configured with `<use_password>` within its `<auth>` section this process depends on a file containing the password on the agent which by default is placed in `/var/ossec/etc/authd.pass` on Linux and `C:\Program Files(x86)\ossec-agent\authd.pass` on Windows. 

When installing using Deployment Variables the initial authentication works correctly but this file is not created thus breaking auto-enrollment. In consequence, if messages are rejected by the manager the agent will enter an infinite loop where it tries to negotiate a new key and fall into a 50 second loop of failing to connect to the manager, trying to get a new key and getting rejected due to lack of password:

```
2021/02/09 19:45:37 ossec-agentd: ERROR: (1137): Lost connection with manager. Setting lock.
2021/02/09 19:45:37 ossec-agentd: INFO: Closing connection to server (manager.address:1514/tcp).
2021/02/09 19:45:37 ossec-agentd: INFO: Trying to connect to server (manager.address:1514/tcp).
2021/02/09 19:45:37 ossec-agentd: WARNING: Process locked due to agent is offline. Waiting for connection...
2021/02/09 19:45:38 ossec-syscheckd: WARNING: Process locked due to agent is offline. Waiting for connection...
2021/02/09 19:45:47 ossec-agentd: INFO: Closing connection to server (manager.address:1514/tcp).
2021/02/09 19:45:47 ossec-agentd: INFO: Trying to connect to server (manager.address:1514/tcp).
2021/02/09 19:45:57 ossec-agentd: INFO: Closing connection to server (manager.address:1514/tcp).
2021/02/09 19:45:57 ossec-agentd: INFO: Trying to connect to server (manager.address:1514/tcp).
2021/02/09 19:46:07 ossec-agentd: INFO: Closing connection to server (manager.address:1514/tcp).
2021/02/09 19:46:07 ossec-agentd: INFO: Trying to connect to server (manager.address:1514/tcp).
2021/02/09 19:46:17 ossec-agentd: INFO: Closing connection to server (manager.address:1514/tcp).
2021/02/09 19:46:17 ossec-agentd: INFO: Trying to connect to server (manager.address:1514/tcp).
2021/02/09 19:46:17 ossec-agentd: INFO: Requesting a key from server: manager.address
2021/02/09 19:46:17 ossec-agentd: INFO: No authentication password provided
2021/02/09 19:46:17 ossec-agentd: INFO: Using agent name as: agent.hostname
2021/02/09 19:46:17 ossec-agentd: INFO: Waiting for server reply
2021/02/09 19:46:17 ossec-agentd: ERROR: Invalid password (from manager)
2021/02/09 19:46:17 ossec-agentd: ERROR: Unable to add agent (from manager)
2021/02/09 19:46:27 ossec-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: 'manager.address'.
2021/02/09 19:46:27 ossec-agentd: WARNING: Unable to connect to any server.
2021/02/09 19:46:27 ossec-agentd: INFO: Closing connection to server (manager.address:1514/tcp).
2021/02/09 19:46:27 ossec-agentd: INFO: Trying to connect to server (manager.address:1514/tcp).
2021/02/09 19:46:37 ossec-agentd: INFO: Closing connection to server (manager.address:1514/tcp).
2021/02/09 19:46:37 ossec-agentd: INFO: Trying to connect to server (manager.address:1514/tcp).
2021/02/09 19:46:47 ossec-agentd: INFO: Closing connection to server (manager.address:1514/tcp).
2021/02/09 19:46:47 ossec-agentd: INFO: Trying to connect to server (manager.address:1514/tcp).
2021/02/09 19:46:57 ossec-agentd: INFO: Closing connection to server (manager.address:1514/tcp).
2021/02/09 19:46:57 ossec-agentd: INFO: Trying to connect to server (manager.address:1514/tcp).
2021/02/09 19:47:07 ossec-agentd: INFO: Closing connection to server (manager.address:1514/tcp).
2021/02/09 19:47:07 ossec-agentd: INFO: Trying to connect to server (manager.address:1514/tcp).
2021/02/09 19:47:07 ossec-agentd: INFO: Requesting a key from server: manager.address
2021/02/09 19:47:07 ossec-agentd: INFO: No authentication password provided
2021/02/09 19:47:07 ossec-agentd: INFO: Using agent name as: agent.hostname
2021/02/09 19:47:07 ossec-agentd: INFO: Waiting for server reply
2021/02/09 19:47:07 ossec-agentd: ERROR: Invalid password (from manager)
2021/02/09 19:47:07 ossec-agentd: ERROR: Unable to add agent (from manager)
2021/02/09 19:47:17 ossec-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: 'manager.address'.
2021/02/09 19:47:17 ossec-agentd: WARNING: Unable to connect to any server.                                           
2021/02/09 19:47:17 ossec-agentd: INFO: Closing connection to server (manager.address:1514/tcp).                        
2021/02/09 19:47:17 ossec-agentd: INFO: Trying to connect to server (manager.address:1514/tcp).
```
This behavior can be achieved by using `agent-auth` to register an agent without then restarting the service, but it may occur naturally due to an interrupted availability of the manager.

**Comment by jctello** [comment]
I've modified the title of this issue to also account for other use cases. For example if a agent_name or agent groups are specified then these values should be added into the agent's `ossec.conf` [\<enrollment\>](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#enrollment) section.
This has been seen to affect an user here: https://github.com/wazuh/wazuh/issues/7899

**Comment by DFolchA** [comment]
## Update

Tested the development done in this branch from [wazuh/wazuh](https://github.com/wazuh/wazuh):

https://github.com/wazuh/wazuh/tree/wj1578-wazuhctl

We can substitute the current [register_configure_agent.sh](https://github.com/wazuh/wazuh/blob/master/src/init/register_configure_agent.sh) with the [wazuhctl](https://github.com/wazuh/wazuh/blob/wj1578-wazuhctl/src/init/wazuhctl) script for Linux and MacOS packages. This will allow us to modify the enrollment configuration when the deployment variables are used.

For Windows packages, we may use the PowerShell script [wazuhctl.ps1](https://github.com/wazuh/wazuh/blob/wj1578-wazuhctl/src/win32/wazuhctl.ps1), but think it would be better to write a new VBS script that is more native to the MSI package.

Also as we are modifying the enrollment configuration we probably do not need to use agent-auth in the auto-deployment process anymore, because the agent will be automatically registered once it is started by the user.

**Comment by DFolchA** [comment]
## Update

- Test new register_configure_agent.sh in centos 7 and ubuntu 18
- Work on VBS script for MSI

**Comment by DFolchA** [comment]
## Update

- Continue working on `register_configure_agent.vbs` 
- Add functionality to `register_configure_agent.vbs` so we can use it to register the agent using `agent-auth.exe`, this way we can remove all these lines from the wxs file:
https://github.com/wazuh/wazuh/blob/c4ba40903868ee050efdea6ff03a660a623ef343/src/win32/wazuh-installer.wxs#L107-L249

**Comment by DFolchA** [comment]
## Update 
**Working branch:** https://github.com/wazuh/wazuh/tree/wp663-unattended-enrollment

- Modify [InstallerScripts.vbs](https://github.com/wazuh/wazuh/blob/613c13ae72b8baad8e89dfba802d154a35cbac1e/src/win32/InstallerScripts.vbs) so it adds enrolment configurations and register the agent.  https://github.com/wazuh/wazuh/commit/613c13ae72b8baad8e89dfba802d154a35cbac1e
- Modify WXS file and remove lines calling agent-auth.exe. https://github.com/wazuh/wazuh/commit/613c13ae72b8baad8e89dfba802d154a35cbac1e  https://github.com/wazuh/wazuh/commit/ea808a4adb145dd05b862277f83f5157096ac055

## To Do 
- Test all the options in Windows installer

**Comment by DFolchA** [comment]
## Update 
**Working branch:** https://github.com/wazuh/wazuh/tree/wp663-unattended-enrollment

- Tested RPM and Deb packages
- Build and test MSI found error when launching VBS script

**Comment by DFolchA** [comment]
## Update 
**Working branch:** https://github.com/wazuh/wazuh/tree/wp663-unattended-enrollment

Finish changes to windows packages and test:

https://user-images.githubusercontent.com/19505384/143283717-e80d79d7-58e3-4667-b484-3752c725a1d9.mp4

- Add support to deprecated variables.

**Comment by DFolchA** [comment]
## Tests

<details><summary>RPM</summary>

|        Parameter                                              |     Configuration    |     Registered        |
|-----------------------------------------------------------|-------------------------|-------------------------|
| WAZUH_MANAGER                                     |     [ossec_conf_WAZUH_MANAGER.txt](https://github.com/wazuh/wazuh-packages/files/7620044/ossec_conf_WAZUH_MANAGER.txt)| :heavy_check_mark:  |                           
| WAZUH_MANAGER_PORT                         | [ossec_conf_WAZUH_MANAGER_PORT.txt](https://github.com/wazuh/wazuh-packages/files/7620048/ossec_conf_WAZUH_MANAGER_PORT.txt) | :heavy_check_mark:  |
| WAZUH_PROTOCOL                                   | [ossec_conf_WAZUH_PROTOCOL.txt](https://github.com/wazuh/wazuh-packages/files/7620067/ossec_conf_WAZUH_PROTOCOL.txt)                           | :heavy_check_mark:  |
| WAZUH_REGISTRATION_SERVER            | [ossec_conf_WAZUH_REGISTRATION_SERVER.txt](https://github.com/wazuh/wazuh-packages/files/7620072/ossec_conf_WAZUH_REGISTRATION_SERVER.txt)                          | :heavy_check_mark:  |
| WAZUH_REGISTRATION_PORT                 | [ossec_conf_WAZUH_REGISTRATION_PORT.txt](https://github.com/wazuh/wazuh-packages/files/7620071/ossec_conf_WAZUH_REGISTRATION_PORT.txt)                          | :heavy_check_mark:  |
| WAZUH_REGISTRATION_PASSWORD      | [ossec_conf_WAZUH_REGISTRATION_PASSWORD.txt](https://github.com/wazuh/wazuh-packages/files/7620070/ossec_conf_WAZUH_REGISTRATION_PASSWORD.txt)  <br> [authd.pass.txt](https://github.com/wazuh/wazuh-packages/files/7620062/authd.pass.txt)                        | :heavy_check_mark:  |
| WAZUH_KEEP_ALIVE_INTERVAL              | [ossec_conf_WAZUH_KEEP_ALIVE_INTERVAL.txt](https://github.com/wazuh/wazuh-packages/files/7620063/ossec_conf_WAZUH_KEEP_ALIVE_INTERVAL.txt)                          | :heavy_check_mark:  |
| WAZUH_TIME_RECONNECT                      | [ossec_conf_WAZUH_TIME_RECONNECT.txt](https://github.com/wazuh/wazuh-packages/files/7620073/ossec_conf_WAZUH_TIME_RECONNECT.txt)                          | :heavy_check_mark:  |
| WAZUH_REGISTRATION_CA                      | [ossec_conf_WAZUH_REGISTRATION_CA.txt](https://github.com/wazuh/wazuh-packages/files/7620068/ossec_conf_WAZUH_REGISTRATION_CA.txt)                          | :heavy_check_mark:  |
| WAZUH_REGISTRATION_CERTIFICATE    | [ossec_conf_WAZUH_REGISTRATION_CERTIFICATE_KEY.txt](https://github.com/wazuh/wazuh-packages/files/7620069/ossec_conf_WAZUH_REGISTRATION_CERTIFICATE_KEY.txt)                          | :heavy_check_mark:  |
| WAZUH_REGISTRATION_KEY                    | [ossec_conf_WAZUH_REGISTRATION_CERTIFICATE_KEY.txt](https://github.com/wazuh/wazuh-packages/files/7620069/ossec_conf_WAZUH_REGISTRATION_CERTIFICATE_KEY.txt)                          | :heavy_check_mark:  |
| WAZUH_AGENT_NAME                               | [ossec_conf_WAZUH_AGENT_NAME_GROUP.txt](https://github.com/wazuh/wazuh-packages/files/7620124/ossec_conf_WAZUH_AGENT_NAME_GROUP.txt)                          | :heavy_check_mark:  |
| WAZUH_AGENT_GROUP                            | [ossec_conf_WAZUH_AGENT_NAME_GROUP.txt](https://github.com/wazuh/wazuh-packages/files/7620124/ossec_conf_WAZUH_AGENT_NAME_GROUP.txt)                          | :heavy_check_mark:  |


### ERRORS

Enrollment cannot read CA file in CentOS 7.

```
2021/11/29 17:18:46 wazuh-agentd: ERROR: Unable to read CA certificate file "/home/vagrant/reg_certs/rootCA.pem"
2021/11/29 17:18:46 wazuh-agentd: ERROR: Could not set up SSL connection! Check ceritification configuration.
2021/11/29 17:19:01 wazuh-agentd: INFO: Requesting a key from server: 172.16.1.64
2021/11/29 17:19:01 wazuh-agentd: ERROR: Unable to read CA certificate file "/home/vagrant/reg_certs/rootCA.pem"
2021/11/29 17:19:01 wazuh-agentd: ERROR: Could not set up SSL connection! Check ceritification configuration.

[root@centos7 vagrant]# ls -l /home/vagrant/reg_certs/rootCA.pem
-rw-r--r--.  1 vagrant vagrant 1870 Nov 29 16:53 /home/vagrant/reg_certs/rootCA.pem

```

Enrollment cannot read certificate file in CentOS 7
```
2021/11/29 17:30:17 wazuh-agentd: INFO: Requesting a key from server: 172.16.1.64
2021/11/29 17:30:17 wazuh-agentd: ERROR: Unable to read certificate file (not found): /home/vagrant/reg_certs/sslagent.cert
2021/11/29 17:30:17 wazuh-agentd: ERROR: Could not set up SSL connection! Check ceritification configuration.
2021/11/29 17:30:27 wazuh-agentd: INFO: Requesting a key from server: 172.16.1.64
2021/11/29 17:30:27 wazuh-agentd: ERROR: Unable to read certificate file (not found): /home/vagrant/reg_certs/sslagent.cert
2021/11/29 17:30:27 wazuh-agentd: ERROR: Could not set up SSL connection! Check ceritification configuration.
2021/11/29 17:30:42 wazuh-agentd: INFO: Requesting a key from server: 172.16.1.64
2021/11/29 17:30:42 wazuh-agentd: ERROR: Unable to read certificate file (not found): /home/vagrant/reg_certs/sslagent.cert
2021/11/29 17:30:42 wazuh-agentd: ERROR: Could not set up SSL connection! Check ceritification configuration.


[root@centos7 vagrant]# ls -l /home/vagrant/reg_certs/sslagent.cert
-rw-r--r--. 1 vagrant vagrant 1785 Nov 29 16:53 /home/vagrant/reg_certs/sslagent.cert

```
</details>

<details><summary>DEB</summary>

|        Parameter                                              |     Configuration    |     Registered        |
|-----------------------------------------------------------|-------------------------|-------------------------|
| WAZUH_MANAGER                                     | [ossec_conf_WAZUH_MANAGER.txt](https://github.com/wazuh/wazuh-packages/files/7620159/ossec_conf_WAZUH_MANAGER.txt)                          | :heavy_check_mark:  |                           
| WAZUH_MANAGER_PORT                         | [ossec_conf_WAZUH_MANAGER_PORT.txt](https://github.com/wazuh/wazuh-packages/files/7620160/ossec_conf_WAZUH_MANAGER_PORT.txt)                          | :heavy_check_mark:  |
| WAZUH_PROTOCOL                                   | [ossec_conf_WAZUH_PROTOCOL.txt](https://github.com/wazuh/wazuh-packages/files/7620161/ossec_conf_WAZUH_PROTOCOL.txt)                          | :heavy_check_mark:  |
| WAZUH_REGISTRATION_SERVER            | [ossec_conf_WAZUH_REGISTRATION_SERVER.txt](https://github.com/wazuh/wazuh-packages/files/7620166/ossec_conf_WAZUH_REGISTRATION_SERVER.txt)                          | :heavy_check_mark:  |
| WAZUH_REGISTRATION_PORT                 | [ossec_conf_WAZUH_REGISTRATION_PORT.txt](https://github.com/wazuh/wazuh-packages/files/7620165/ossec_conf_WAZUH_REGISTRATION_PORT.txt)                          | :heavy_check_mark:  |
| WAZUH_REGISTRATION_PASSWORD      | [ossec_conf_WAZUH_REGISTRATION_PASSWORD.txt](https://github.com/wazuh/wazuh-packages/files/7620164/ossec_conf_WAZUH_REGISTRATION_PASSWORD.txt)<br>[authd.pass,txt](https://github.com/wazuh/wazuh-packages/files/7620156/authd.pass.txt)                         | :heavy_check_mark:  |
| WAZUH_KEEP_ALIVE_INTERVAL              | [ossec_conf_WAZUH_KEEP_ALIVE_INTERVAL.txt](https://github.com/wazuh/wazuh-packages/files/7620158/ossec_conf_WAZUH_KEEP_ALIVE_INTERVAL.txt)                          | :heavy_check_mark:  |
| WAZUH_TIME_RECONNECT                      | [ossec_conf_WAZUH_TIME_RECONNECT.txt](https://github.com/wazuh/wazuh-packages/files/7620167/ossec_conf_WAZUH_TIME_RECONNECT.txt)                          | :heavy_check_mark:  |
| WAZUH_REGISTRATION_CA                      | [ossec_conf_WAZUH_REGISTRATION_CA.txt](https://github.com/wazuh/wazuh-packages/files/7620162/ossec_conf_WAZUH_REGISTRATION_CA.txt)                          | :heavy_check_mark:  |
| WAZUH_REGISTRATION_CERTIFICATE    | [ossec_conf_WAZUH_REGISTRATION_CERTIFICATE_KEY.txt](https://github.com/wazuh/wazuh-packages/files/7620163/ossec_conf_WAZUH_REGISTRATION_CERTIFICATE_KEY.txt)                           | :heavy_check_mark:  |
| WAZUH_REGISTRATION_KEY                    | [ossec_conf_WAZUH_REGISTRATION_CERTIFICATE_KEY.txt](https://github.com/wazuh/wazuh-packages/files/7620163/ossec_conf_WAZUH_REGISTRATION_CERTIFICATE_KEY.txt)                          | :heavy_check_mark:  |
| WAZUH_AGENT_NAME                               | [ossec_conf_WAZUH_AGENT_NAME_GROUP.txt](https://github.com/wazuh/wazuh-packages/files/7620157/ossec_conf_WAZUH_AGENT_NAME_GROUP.txt)                          | :heavy_check_mark:  |
| WAZUH_AGENT_GROUP                            | [ossec_conf_WAZUH_AGENT_NAME_GROUP.txt](https://github.com/wazuh/wazuh-packages/files/7620157/ossec_conf_WAZUH_AGENT_NAME_GROUP.txt)                          | :heavy_check_mark:  |
</details>

<details><summary>MacOS</summary>

|        Parameter                                              |     Configuration    |     Registered        |
|-----------------------------------------------------------|-------------------------|-------------------------|
| WAZUH_MANAGER                                     | ---                          | :heavy_check_mark: |                           
| WAZUH_MANAGER_PORT                         | ---                          | ---                          |
| WAZUH_PROTOCOL                                   | ---                          | ---                          |
| WAZUH_REGISTRATION_SERVER            | ---                          | ---                          |
| WAZUH_REGISTRATION_PORT                 | ---                          | ---                          |
| WAZUH_REGISTRATION_PASSWORD      | ---                          | ---                          |
| WAZUH_KEEP_ALIVE_INTERVAL              | ---                          | ---                          |
| WAZUH_TIME_RECONNECT                      | ---                          | ---                          |
| WAZUH_REGISTRATION_CA                      | ---                          | ---                          |
| WAZUH_REGISTRATION_CERTIFICATE    | ---                          | ---                          |
| WAZUH_REGISTRATION_KEY                    | ---                          | ---                          |
| WAZUH_AGENT_NAME                               | ---                          | ---                          |
| WAZUH_AGENT_GROUP                            | ---                          | ---                          |
</details>

<details><summary>Windows</summary>

|        Parameter                                              |     Configuration    |     Registered        |
|-----------------------------------------------------------|-------------------------|-------------------------|
| WAZUH_MANAGER                                     | ---                          | :heavy_check_mark: |                           
| WAZUH_MANAGER_PORT                         | ---                          | ---                          |
| WAZUH_PROTOCOL                                   | ---                          | ---                          |
| WAZUH_REGISTRATION_SERVER            | ---                          | ---                          |
| WAZUH_REGISTRATION_PORT                 | ---                          | ---                          |
| WAZUH_REGISTRATION_PASSWORD      | ---                          | ---                          |
| WAZUH_KEEP_ALIVE_INTERVAL              | ---                          | ---                          |
| WAZUH_TIME_RECONNECT                      | ---                          | ---                          |
| WAZUH_REGISTRATION_CA                      | ---                          | ---                          |
| WAZUH_REGISTRATION_CERTIFICATE    | ---                          | ---                          |
| WAZUH_REGISTRATION_KEY                    | ---                          | ---                          |
| WAZUH_AGENT_NAME                               | ---                          | ---                          |
| WAZUH_AGENT_GROUP                            | ---                          | ---                          |
</details>

**Comment by DFolchA** [comment]
## Update

- Remove call to ossec-authd
- Add new variable for `delay_after_enrollment` 

## To Do
- Test changes
