### ISSUE TITLE
Rename wazuh-packages users and groups according to the new Wazuh standard

### ISSUE THREAD

**Issue by alromeros** [wazuh/wazuh-packages#651]
### Description

Hi team,

The goal of this issue is to rename all the references to the legacy users and groups in the **wazuh-packages** repository, according to the new Wazuh naming standard.

**Users to modify**
- `ossec`→ `wazuh`
- `ossecm` → `wazuh`
- `ossecr` → `wazuh`

**Group to modify**
- `ossec` → `wazuh`

### Relevant files

After a quick research, some files that appear to be relevant to this issue are:
- **`ossecr` main occurrences:**
    - `./rpms/SPECS/*/wazuh-manager-*.spec`
    - `./debs/SPECS/*/wazuh-manager/debian/post*`

- **`ossecm` main occurrences:**
     - `./rpms/SPECS/*/wazuh-manager-*.spec`
     - `./debs/SPECS/*/wazuh-manager/debian/post*`
- **`ossec` main occurrences:**

    - `./solaris/solaris11/SPECS/template_agent_*.json`
    - `./rpms/SPECS/*/wazuh-manager-*.spec`
    - `./debs/SPECS/*/wazuh-manager/debian/post*`
    - `./solaris/solaris*/generate_wazuh_packages.sh`
    - `./solaris/solaris10/preinstall.sh`

You can check issue wazuh/wazuh#7646 for more information.

**Comment by DFolchA** [comment]
### STATUS REPORT
**Working branch:** https://github.com/wazuh/wazuh-packages/tree/651-rename-user

Changes done in commits https://github.com/wazuh/wazuh-packages/commit/77eb00b4eb6760e71b8d7a0c1473af1e470e7ea7 and https://github.com/wazuh/wazuh-packages/commit/898105eefd7da82c63e6b7fba31d51aa03bb6961 .

Packages tested:
- [x] RPM 
- [x] DEB
- [ ] Solaris
- [ ] AIX
- [ ] MacOS

**Comment by DFolchA** [comment]
### Status Report

Solved issues when upgrading from older versions, these problems were caused by files not included in the package keeping the old user and group.

Tested upgrade and clean install in the different platforms.
