### ISSUE TITLE
Rename ossec.conf to manager.conf and agent.conf in Packages

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-packages#658]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 5.0.0 | Manager/API/Agent | Install/Upgrade/Remove | All |

The purpose of this issue is to rename `ossec.conf` in Wazuh Packages according to https://github.com/wazuh/wazuh/issues/7787:

- **Agent configuration**: All settings related to Wazuh Agent will be located at `agent.conf`. Blocks:
  - `<active-response>` (client side)
  - `<agent-upgrade>` (client side)
  - `<client>`
  - `<client_buffer>`
  - `<fluent-forward>`
  - `<gcp-pubsub>`
  - `<labels>` (same as manager)
  - `<localfile>`
  - `<logging>` (same as manager)
  - `<rootcheck>`
  - `<sca>`
  - `<socket>`
  - `<syscheck>`
  - `<wodle>`
    - `<wodle name="agent-key-polling">`
    - `<wodle name="aws-s3">`
    - `<wodle name="azure-logs">`
    - `<wodle name="cis-cat">`
    - `<wodle name="command">`
    - `<wodle name="docker-listener">`
    - `<wodle name="open-scap">`
    - `<wodle name="osquery">`
    - `<wodle name="syscollector">`

- **Manager configuration**: All settings related to Wazuh Manager will be located at `manager.conf`. Blocks:
  - `<active-response>` (manager side)
  - `<agentless>`
  - `<agent-upgrade>` (manager side)
  - `<alerts>`
  - `<auth>`
  - `<cluster>`
  - `<command>`
  - `<database_output>`
  - `<email_alerts>`
  - `<global>`
  - `<integration>`
  - `<labels>` (same as agent)
  - `<logging>` (same as agent)
  - `<remote>`
  - `<reports>`
  - `<rule_test>`
  - `<ruleset>`
  - `<syslog_output>`
  - `<task-manager>`
  - `<vulnerability-detector>`

Also, to avoid confusion, `agent.conf` shared configuration file should be renamed to `shared.conf` and `agent-template.conf` file to `shared-template.conf`.

In addition, `gen_ossec.sh` script file has to be renamed to `gen_wazuh.sh`. This is the new list of install types that this script can receive:

- `manager`: Build `manager.conf` file for manager installation.
- `local`: Build `manager.conf` file for local installation.
- `agent-server`: Build `agent.conf` file for manager/local installation.
- `agent`: Build `agent.conf` file for agent installation.

Agent upgrades using packages (DEB, RPM, ...) should have this behavior:

- If the agent version is lower than 5.0, upgrade should not continue because it is a breaking change (not supported).

**Comment by DFolchA** [comment]
## Update report

### Manager
Changed `ossec.conf` to `manager.conf` and `agent.conf` to `shared.conf`, When upgrading these files will be maintained as legacy but not used by Wazuh.

Use `gen_wazuh.sh `instead of `gen_ossec.sh` to generate ossec.conf

### Agent upgrade

Changed `ossec.conf` to `agent.conf`

Agent upgrade is not allowed from versions lower than 5.0.0.

## TO DO
- Build and test 5.0.0 packages from [dev-separate-conf](https://github.com/wazuh/wazuh/tree/dev-separate-conf)
    -  [ ] Installation
    -  [ ] Upgrade from 4.x
    -  [ ] Upgrade to 5.x

**Comment by DFolchA** [comment]
## Update report

Build and test packages:

### Agent
- [x] Build DEB
- [x] Build RPM
- [x] Installation
- [x] Upgrade
- [x] manager connection

### Manager
- [x] Build DEB
- [x] Build RPM
- [x] Installation
- [x] Upgrade
- [x] Agent connection

**Comment by alberpilot** [comment]
Reverted PR.
