### ISSUE TITLE
[AIX] Error in linking when installing dependencies

### ISSUE THREAD

**Issue by MethylHaine** [wazuh/wazuh-packages#687]
Wazuh version | Install type | Action performed | Platform
-- | -- | -- | --
v4.1.4 | Agent | Install Dependencies | AIX 7.2

Hi everyone,
We are trying to generate an AIX Wazuh package, following the [official documentation](https://documentation.wazuh.com/current/development/packaging/generate-aix-package.html).

When trying to install dependencies :
`./generate_wazuh_packages.sh -e`

We encounter the following issues:

1. Compiler **cc** is not found, while our **gcc** installation seems correct :
```
# rpm -qa | grep gcc
libgcc-8-1.ppc
gcc8-8.3.0-4.ppc
gcc-8-1.ppc
gcc-c++-8-1.ppc
libgcc8-8.3.0-4.ppc
gcc8-cpp-8.3.0-4.ppc
gcc-cpp-8-1.ppc
gcc8-c++-8.3.0-4.ppc
```
So we've established the following workaround, by creating a symbolic link between **cc** and **gcc** :
```
# ls /usr/bin/cc
lrwxrwxrwx    1 root     system           12 Mar 25 12:05 /usr/bin/cc -> /usr/bin/gcc
```
2. TOC Overflow when linking during gmake :
```
Scanning dependencies of target cmake
[ 91%] Building CXX object Source/CMakeFiles/cmake.dir/cmakemain.cxx.o
[ 92%] Building CXX object Source/CMakeFiles/cmake.dir/cmcmd.cxx.o
[ 92%] Linking CXX executable ../bin/cmake
ld: 0711-781 ERROR: TOC overflow. TOC size: 67288       Maximum size: 65536
collect2: error: ld returned 12 exit status
gmake[2]: *** [Source/CMakeFiles/cmake.dir/build.make:113: bin/cmake] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2263: Source/CMakeFiles/cmake.dir/all] Error 2
gmake: *** [Makefile:163: all] Error 2
```

According to [IBM in this ticket](https://www.ibm.com/support/pages/ld-0711-781-error-toc-overflow), we can solve this issue by adding the **'-bbigtoc'** options in the compilation flags (either on gmake or when linking).
Unfortunately this is not working. 
Either we still get the TOC overflow Error, a file not found exception, or the following :
```
[ 91%] Linking CXX executable ../bin/cmake
ld: 0711-738 ERROR: Input file /lib/crt0_r.o:
        XCOFF32 object files are not allowed in 64-bit mode.
collect2: error: ld returned 8 exit status
gmake[2]: *** [Source/CMakeFiles/cmake.dir/build.make:113: bin/cmake] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2263: Source/CMakeFiles/cmake.dir/all] Error 2
gmake: *** [Makefile:163: all] Error 2
```

There seems to be an issue with the flags or with our ENV vars, but we didn't manage to find which it was..
Would you have an idea ?

Best regards,

**Comment by alberpilot** [comment]
Hello @MethylHaine 

  Sorry for the inconvenience. We did an important change using CMake but it will be used on 4.2 and later. The `master` branch uses CMake as is the branch more advanced in development and it's ready to build 4.2 and later. 
  
  In your case, please use the wazuh-packages branch `4.1`, and run again the building tool. 
  
Please let me know if you have any questions.

**Comment by MethylHaine** [comment]
Hi @alberpilot 

Thanks for your quick answer.
When testing with [branch 4.1](https://github.com/wazuh/wazuh-packages/tarball/4.1), dependency resolving is indeed working flawlessly.

However when running 
```
./generate_wazuh_packages.sh -b v4.1.4 -p /OPT/ossec
```
 We encounter the following issue :
```
[root@wazaix /OPT/wazuh-wazuh-packages-5c2bc81/aix]# ./generate_wazuh_packages.sh -b v4.1.4  -p /OPT/ossec
--2021-03-30 16:44:49--  https://api.github.com/repos/wazuh/wazuh/tarball/v4.1.4
[...]
WARNING: cannot verify codeload.github.com's certificate, issued by 'CN=DigiCert High Assurance TLS Hybrid ECC SHA256 2020 CA1,O=DigiCert\\, Inc.,C=US':
  Unable to locally verify the issuer's authority.
Proxy request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: 'wazuh.tar.gz'

wazuh.tar.gz                                           [                   <=>                                                                                          ]  17.53M  4.39MB/s    in 3.9s

2021-03-30 16:44:53 (4.55 MB/s) - 'wazuh.tar.gz' saved [18381567]

rpm: -bb: unknown option
mv_64: cannot stat '/opt/freeware/src/packages/RPMS/ppc/wazuh-agent-4.1.4-1.aix7.2.ppc.rpm': No such file or directory
Error: RPM package could not be created
```
Obviously due to the fact we are using rpm v4.X, so changing `generate_wazuh_packages.sh` like this allows us to build the rpm :
```
 rpm --define '_tmppath /tmp' --define "_topdir ${rpm_build_dir}" --define "_localstatedir ${install_path}" \
  --define "_init_scripts ${init_scripts}" --define "_sysconfdir ${sysconfdir}"
  # -bb ${rpm_build_dir}/SPECS/${package_name}-aix.spec

  rpmbuild -ba ${rpm_build_dir}/SPECS/${package_name}-aix.spec
```
Once deleted our previous symbolic link for Cmake, and modified the script as above,
 the compilation runs fine until the following Error :
```
./generate_wazuh_packages.sh -b v4.1.4 -p /OPT/ossec
[...]
gmake ossec-agentd agent-auth ossec-logcollector ossec-syscheckd ossec-execd manage_agents wazuh-modulesd
gmake[1]: Entering directory '/opt/freeware/src/packages/BUILD/wazuh-agent-4.1.4/src'
grep_64: /etc/os-release: No such file or directory
    CC client-agent/notify.o
In file included from /usr/include/sys/cred.h:46,
                 from /usr/include/sys/thread.h:42,
                 from /usr/include/sys/ptrace.h:28,
                 from /usr/include/sys/proc.h:43,
                 from /usr/include/sys/pri.h:43,
                 from /usr/include/sys/sched.h:38,
                 from /usr/include/sched.h:51,
                 from /usr/include/pthread.h:63,
                 from ./headers/shared.h:74,
                 from client-agent/notify.c:11:
./config/config.h:43:5: error: expected identifier before numeric constant
     LOGALL,
     ^~~~~~
gmake[1]: *** [Makefile:1401: client-agent/notify.o] Error 1
gmake[1]: Leaving directory '/opt/freeware/src/packages/BUILD/wazuh-agent-4.1.4/src'
gmake: *** [Makefile:608: agent] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.AmHaea (%prep)


RPM build errors:
    bogus date in %changelog: Thu Feb 24 2020 support <info@wazuh.com> - 3.11.4
    [...]
    Bad exit status from /var/tmp/rpm-tmp.AmHaea (%prep)
mv_64: cannot stat '/opt/freeware/src/packages/RPMS/ppc/wazuh-agent-4.1.4-1.aix7.2.ppc.rpm': No such file or directory
Error: RPM package could not be created
```

**Comment by MethylHaine** [comment]
There seems to be a clash between pre-processors instructions and the values defined in the `typedef enum` section.
Changing the following section in `/config/config.h` :
```
typedef enum needed_tags {
    JSONOUT_OUTPUT = 0,
    ALERTS_LOG,
    LOGALL,
    LOGALL_JSON
} NeededTags;
```
To
```
typedef enum needed_tags {
    Jsonout_Output = 0,
    Alerts_Log,
    Logall,
    Logall_Json
} NeededTags;
```
Allows to run `gmake ossec-agentd agent-auth ossec-logcollector ossec-syscheckd ossec-execd manage_agents wazuh-modulesd`
Until the following Error ? :
```
gmake[1]: Leaving directory '/opt/freeware/src/packages/BUILD/wazuh-agent-4.1.4/src/external/bzip2'
    CC libwazuhext.so
gcc: error: external/libffi/failtarget/.libs/libffi.a: No such file or directory
gmake: *** [Makefile:1305: libwazuhext.so] Error 1
```

**Comment by Dwordcito** [comment]
Hi, @MethylHaine 

I think the problem you have when compiling is because you are incorrectly defining the gmake arguments. you can rely on the spec that I detail below.

`gmake TARGET=agent USE_SELINUX=no PREFIX=%{_localstatedir} DISABLE_SHARED=yes DISABLE_SYSC=yes`

https://github.com/wazuh/wazuh-packages/blob/5c2bc8196985424629ee6677287d855e8d7a2ba8/aix/SPECS/4.1.4/wazuh-agent-4.1.4-aix.spec#L27

Anyway, the inconvenience for not generating the package correctly exists, that typedef is causing problems when compiling in 7.2, (note that we do the packages with version 6 of AIX, in which this does not happen )


As for LOGALL, just by changing it to "LOGALL_EX" the problem is solved and we keep the code style constant, please create an issue in wazuh/wazuh or move it, and we will solve it shortly for future versions.
