### ISSUE TITLE
Rename ossec.log to wazuh.log and ossec.json to wazuh.json in Packages

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-packages#697]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 5.0 | Manager/API/Agent | Install/Upgrade/Remove | All |

The purpose of this issue is to rename `ossec.log` to `wazuh.log` and `ossec.json` to `wazuh.json` in Wazuh Packages according to https://github.com/wazuh/wazuh/issues/8086.

**Comment by DFolchA** [comment]
## Update report

### Common
Changed `ossec.log/json` to `wazuh.log/json` in 5.0.0 SPECS when necessary and references to these files have been changed in the installation scripts.

### Manager upgrade

Old logs are being removed if upgrading from versions lower than 5.0.0 and new logs will be created by the manager on start.

Starting from version 5.0.0 the longs will be maintained after an upgrade.

These changes do not affect `alerts` and archives logs.

### Agent upgrade

Agent upgrade is not allowed from versions lower than 5.0.0, from then onward logs with the new name will be maintained when upgrading.

**Comment by DFolchA** [comment]
## Update report

Build and test packages installation and upgrade, we found no problem and the files had the correct naming.

Working branch:
https://github.com/wazuh/wazuh-packages/tree/697-rename-logs

**Comment by DFolchA** [comment]
## Update report

Build and test packages:

### Agent
- [x] Build DEB
- [x] Build RPM
- [x] Installation
- [x] Upgrade
- [x] manager connection

### Manager
- [x] Build DEB
- [x] Build RPM
- [x] Installation
- [x] Upgrade
- [x] Agent connection
