### ISSUE TITLE
Wazuh manager SPECs modification including filebeat

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#698]
As part of the [Installer architecture simplification](https://github.com/wazuh/wazuh-packages/issues/665), and [once verified the technical viability](https://github.com/wazuh/wazuh-packages/issues/664), the Debian and RPM packages SPECs needs to be modified including all filebeat and custom configuration files. The package scripts must be modified accordingly.

**Comment by VictorMorenoJimenez** [comment]
### Update
RPM version of package is ready. A sample is uploaded to S3: https://packages-dev.wazuh.com/deps/filebeat-test/wazuh-manager-4.2.0-1.x86_64.rpm

`Wazuh-packages` and `wazuh` branch used to generate the package: `4.2.0-filebeat`:
- https://github.com/wazuh/wazuh-packages/tree/4.2.0-filebeat
- https://github.com/wazuh/wazuh/tree/4.2.0-filebeat

**Comment by VictorMorenoJimenez** [comment]
### Update
Moved development from `4.2.0` branch to `4.3.0`. 
Created branch in `wazuh/wazuh` and `wazuh/wazuh-packages` `4.3.0-filebeat`. 

- RPM package is ready.
- Working in Debian package. Working in SPEC.

**Comment by VictorMorenoJimenez** [comment]
## Update 07/04/2021
- Finished Debian SPECS. 
- Created 5.0.0 Debian and RPM packages.
- Test them with @alberpilot and found some issues:
  - `filebeat.yml` must be taken from `wazuh/wazuh` repo.
  - Wazuh filebeat module must be taken from `wazuh/wazuh/` repo.
  - Found error in Wazuh filebeat module, `alerts.json` path must be changed.
  - Must investigate how filebeat rotate logs, seems like it is rotating too fast, when starting filebeat a `filebeat`, `filebeat.1` and `filebeat.2` log files already in place.

**Comment by VictorMorenoJimenez** [comment]
### Update
- Finished first approach. Debian and RPM packages are ready:
  - https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/deps/filebeat-test/wazuh-manager_5.0.0-1_amd64.deb
  - https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/deps/filebeat-test/wazuh-manager-5.0.0-1.x86_64.rpm
  
- Steps followed: (RPM)
  -  Created new branch `5.0-dev-filebeat` in `wazuh/wazuh`. https://github.com/wazuh/wazuh/compare/5.0-dev...5.0-dev-filebeat
      - Modified `wazuh-control` to start/stop/restart `filebeat` daemon.
      - Modified `filebeat.yml`. Update with new paths.
      - Modified Wazuh filebeat module (new alerts.json location)
  - Created new branch `5.0-dev-filebeat` in `wazuh/wazuh-packages`. https://github.com/wazuh/wazuh-packages/compare/5.0-dev...5.0-dev-filebeat
    - Updated `5.0.0` SPECS to include filebeat.
    
### Test
- Installed package `wazuh-manager-5.0.0-1.x86_64.rpm` in a fresh centos7.
- Started service: `systemctl start wazuh-manager`

```
   [root@centos7 user]# ps -aux | grep wazuh-manager
  ossec     5838  0.4  2.1 297392 84736 ?        Sl   09:05   0:07 /usr/share/wazuh-manager/framework/python/bin/python3 /usr/share/wazuh-manager/api/scripts/wazuh-apid.py
  root      5880  0.0  0.0 116700  3356 ?        Sl   09:05   0:00 /usr/share/wazuh-manager/bin/wazuh-authd
  ossec     5897  0.2  0.6 640304 25188 ?        Sl   09:05   0:03 /usr/share/wazuh-manager/bin/wazuh-db
  root      5927  0.0  0.0  34624  1376 ?        Sl   09:05   0:00 /usr/share/wazuh-manager/bin/wazuh-execd
  ossec     5953  0.0  0.4 822240 18336 ?        Sl   09:05   0:01 /usr/share/wazuh-manager/bin/wazuh-analysisd
  root      6005  0.3  0.2 266248  9516 ?        SNl  09:05   0:06 /usr/share/wazuh-manager/bin/wazuh-syscheckd
  ossecr    6021  0.1  0.1 519392  4224 ?        Sl   09:05   0:03 /usr/share/wazuh-manager/bin/wazuh-remoted
  root      6069  0.0  0.1 480360  5420 ?        Sl   09:05   0:00 /usr/share/wazuh-manager/bin/wazuh-logcollector
  ossec     6125  0.0  0.0  34760  1528 ?        Sl   09:05   0:00 /usr/share/wazuh-manager/bin/wazuh-monitord
  root      6176  0.0  0.5 1057084 19516 ?       Sl   09:05   0:00 /usr/share/wazuh-manager/bin/wazuh-modulesd
  root      6365  0.0  0.8 964092 34908 ?        Sl   09:05   0:00 /usr/share/wazuh-manager/filebeat/bin/filebeat -c /usr/share/wazuh-manager/filebeat/etc/filebeat.yml --path.home /usr/share/wazuh-manager/filebeat --path.config /usr/share/wazuh-manager/filebeat/etc --path.data /var/lib/wazuh-filebeat --path.logs /var/log/wazuh-filebeat
```


- Stop service: `systemctl stop wazuh-manager`
  
```

  [root@centos7 user]# ps -aux | grep wazuh-manager
  root      8485  0.0  0.0  12500   684 pts/0    S+   09:32   0:00 grep --color=auto wazuh-manager
```




- Filebeat folder:

```
[root@centos7 certs]# tree /usr/share/wazuh-manager/filebeat/
/usr/share/wazuh-manager/filebeat/
├── bin
│   └── filebeat
├── etc
│   ├── certs
│   │   ├── filebeat.key
│   │   ├── filebeat.pem
│   │   └── root-ca.pem
│   ├── filebeat.yml
│   └── wazuh-template.json
├── LICENSE.txt
├── module
│   └── wazuh
│       ├── alerts
│       │   ├── config
│       │   │   └── alerts.yml
│       │   ├── ingest
│       │   │   └── pipeline.json
│       │   └── manifest.yml
│       ├── archives
│       │   ├── config
│       │   │   └── archives.yml
│       │   ├── ingest
│       │   │   └── pipeline.json
│       │   └── manifest.yml
│       ├── _meta
│       │   ├── config.yml
│       │   ├── docs.asciidoc
│       │   └── fields.yml
│       └── module.yml
├── NOTICE.txt
└── README.md

```

- Installed Elasticsearch to test filebeat output
```
[root@centos7 certs]# /usr/share/wazuh-manager/filebeat/bin/filebeat -c /usr/share/wazuh-manager/filebeat/etc/filebeat.yml test outputelasticsearch: https://127.0.0.1:9200...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: 127.0.0.1
    dial up... OK
  TLS...
    security: server's certificate chain verification is enabled
    handshake... OK
    TLS version: TLSv1.3
    dial up... OK
  talk to server... OK
  version: 7.10.0
```



- Check that filebeat is reading `alerts.json`
```
[root@centos7 certs]# lsof /usr/share/wazuh-manager/logs/alerts/alerts.json
COMMAND    PID  USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
wazuh-ana 6194 ossec   11w   REG    8,1   326348 68443707 /usr/share/wazuh-manager/logs/alerts/alerts.json
filebeat  6950  root    9r   REG    8,1   326348 68443707 /usr/share/wazuh-manager/logs/alerts/alerts.json
```

- Installed second filebeat daemon and configured it o read aswell `alerts.json`. Both filebeats working.

```
[root@centos7 filebeat]# lsof /usr/share/wazuh-manager/logs/alerts/alerts.json
COMMAND     PID  USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
wazuh-ana  6194 ossec   11w   REG    8,1   332186 68443707 /usr/share/wazuh-manager/logs/alerts/alerts.json
filebeat   6950  root    9r   REG    8,1   332186 68443707 /usr/share/wazuh-manager/logs/alerts/alerts.json
filebeat  15702  root    8r   REG    8,1   332186 68443707 /usr/share/wazuh-manager/logs/alerts/alerts.json

```

**Comment by VictorMorenoJimenez** [comment]
### Pending
- Filebeat data path, provisional: `/var/lib/wazuh-filebeat/`
- Filebeat log path, provisional: `/var/log/wazuh-filebeat/`

Are those locations going to be configurable using the `wazuh-packages` package generation script?

**Comment by santiago-bassett** [comment]
Lets use these paths:

- /var/lib/wazuh-manager/filebeat
- /var/log/wazuh-manager/filebeat

Everything related to wazuh-manager should be in directories for this package:
