### ISSUE TITLE
Add SPECS for SCA CIS policies for Amazon Linux 1 and 2, and Ubuntu 14, 16, 18 and 20

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-packages#758]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3 | SPECS | Install | -  |

Team. we need SPECS for those CIS Policies Files

-  ruleset/sca/amazon/cis_amazon_linux_1.yml
-  ruleset/sca/amazon/cis_amazon_linux_2.yml
-  ruleset/sca/ubuntu/cis_ubuntu14-04.yml
-  ruleset/sca/ubuntu/cis_ubuntu16-04.yml
-  ruleset/sca/ubuntu/cis_ubuntu18-04.yml
-  ruleset/sca/ubuntu/cis_ubuntu20-04.yml

Brach created on wazuh-packages -> https://github.com/wazuh/wazuh-packages/tree/sca-ubuntu-amazon-linux

**Comment by DFolchA** [comment]
## Status update

- Remove unused SCA files from SPECS
- Generate and test packages
