### ISSUE TITLE
Add SPECS for SCA CIS policies for SLES, IIS, MongoDB, OracleDB, Nginx

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-packages#759]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3 | SPECS | Install | -  |

- CIS SUSE Linux Enterprise 15 Benchmark v1.0.0
- CIS SUSE Linux Enterprise 11 Benchmark v2.1.0
- CIS SUSE Linux Enterprise 12 Benchmark v2.1.0
- CIS Microsoft IIS 10 Benchmark v1.1.1
- CIS MongoDB 3.6 Benchmark v1.0.0
- CIS Oracle Database 19c Benchmark v1.0.0
- CIS NGINX Benchmark v1.0.0

Brach created on wazuh-packages -> https://github.com/wazuh/wazuh-packages/tree/add_sca_policies

**Comment by DFolchA** [comment]
## Status update

- Remove unused SCA files from SPECS
- Generate and test packages

**Comment by okynos** [comment]
Done in https://github.com/wazuh/wazuh-packages/pull/797
