### ISSUE TITLE
Add SPECS for SCA CIS policies for MS IIS, Oracle Database 19c, MongoDB 3.6, Nginx, SQL Server and SLES

### ISSUE THREAD

**Issue by jcruzlp** [wazuh/wazuh-packages#783]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3 | SPECS | Install | - |

Hello team, we need SPECS for those CIS Policies Files:

- `ruleset/sca/applications/cis_iis_10.yml ` which uses this PR https://github.com/wazuh/wazuh/pull/8818 and [this branch](https://github.com/wazuh/wazuh/tree/8075-add-sca-for-ms) 
- ` ruleset/sca/oracledb/cis_oracle_database_19c.yml` uses this PR https://github.com/wazuh/wazuh/pull/8816 and [this branch](https://github.com/wazuh/wazuh/tree/8093-Add-OracleDB-19c-SCA) 
- `ruleset/sca/mongodb/cis_mongodb_36.yml` uses this PR https://github.com/wazuh/wazuh/pull/8815 and [this branch ](https://github.com/wazuh/wazuh/tree/8073-Add-Mongodb-SCA)
- `ruleset/sca/nginx/cis_nginx_1.yml` which uses this PR https://github.com/wazuh/wazuh/pull/8814 and this  [branch](https://github.com/wazuh/wazuh/tree/8126-add-nginx-sca)
- `ruleset/sca/aplications/cis_sqlserver_2016.yml` which uses this PR https://github.com/wazuh/wazuh/pull/8845 and [this branch](https://github.com/wazuh/wazuh/tree/693_SCA_policies_for_SQL_Server_2016)
- `ruleset/sca/sles/15/cis_sles15_linux.yml` which uses this PR https://github.com/wazuh/wazuh/pull/8911, [this branch](https://github.com/wazuh/wazuh/tree/8910-add-sles-sca) and has [this Issue](https://github.com/wazuh/wazuh/issues/8910)

**Comment by jcruzlp** [comment]
The branch with all the SCA changes is this one: https://github.com/wazuh/wazuh/tree/783-add-new-sca

**Comment by DFolchA** [comment]
##Update Report

- Modify SPECS to include new SCA files 
- Remove unnecessary SCA files from agent installation

## To Do
- Test Package
