### ISSUE TITLE
Python permissions are not corrected for Debian

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-packages#789]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.1.5 | Manager | Install | Debian  |
| 4.2.0-40205 | Manager | Install | Debian |

A fresh install of either  [wazuh-manager_4.1.5-1_amd64.deb](https://https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-manager/wazuh-manager_4.1.5-1_amd64.deb) or [wazuh-manager_4.2.0-1_amd64.deb](https://packages-dev.wazuh.com/pre-release/apt/pool/main/w/wazuh-manager/wazuh-manager_4.2.0-1_amd64.deb) will result on certain files having 777 permissions:

```
ls -l /var/ossec/framework/python/bin/2to3-3.9 /var/ossec/framework/python/bin/pydoc3.9 /var/ossec/framework/python/bin/idle3.9 /var/ossec/framework/python/bin/python3.9 /var/ossec/framework/python/share/man/man1/python3.9.1 /var/ossec/framework/python/lib/pkgconfig/python-3.9-embed.pc /var/ossec/framework/python/lib/libpython3.9.so.1.0
-rwxrwxrwx 1 root ossec      118 May 31 06:23 /var/ossec/framework/python/bin/2to3-3.9
-rwxrwxrwx 1 root ossec      116 May 31 06:23 /var/ossec/framework/python/bin/idle3.9
-rwxrwxrwx 1 root ossec      101 May 31 06:23 /var/ossec/framework/python/bin/pydoc3.9
-rwxrwxrwx 1 root ossec    15575 May 31 06:23 /var/ossec/framework/python/bin/python3.9
-rwxrwxrwx 1 root ossec 19661846 May 31 06:23 /var/ossec/framework/python/lib/libpython3.9.so.1.0
-rwxrwxrwx 1 root ossec      325 May 31 06:23 /var/ossec/framework/python/lib/pkgconfig/python-3.9-embed.pc
-rwxrwxrwx 1 root ossec    18232 May 31 06:23 /var/ossec/framework/python/share/man/man1/python3.9.1
```
There is a specific rule to fix these permission issues [here](https://github.com/wazuh/wazuh-packages/blob/v4.1.5/debs/SPECS/4.1.5/wazuh-manager/debian/rules#L189-L194) and in 3.13.2 and prior this would be [enforced here](https://github.com/wazuh/wazuh-packages/blob/7127e2a5a0f4255bfcabe3fb748b93d0436776b3/debs/SPECS/3.13.2/wazuh-manager/debian/postinst#L391-L397) which is not present in the current version.

**Comment by DFolchA** [comment]
## Update Report

**Working branch:** https://github.com/wazuh/wazuh-packages/tree/fix-override-dh-fixperms

We found that the the `override_dh_fixperms` section of the rules file was not being run, we added it to the .PHONY section in this commit to solve the problem 5aa6ed7.
