### ISSUE TITLE
Add SPECS for SCA CIS policy PostgreSQL-13

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh-packages#807]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3 | SPECS | Install | - |

- CIS PostgreSQL-13 Benchmark v1 

### Related
- [Issue](https://github.com/wazuh/wazuh/issues/8071)
- [PR](https://github.com/wazuh/wazuh/pull/9085)

**Comment by DFolchA** [comment]
## Update Report

- [x] Add changes to SPECS 

## To do 
- [ ] Test packages

**Comment by DFolchA** [comment]
The SCA files included in this issue are installed in the applications directory, so there is no need to change anything in the SPECS.
