### ISSUE TITLE
Add SPECS for SCA CIS policies to Fedora agents use Rhel 8 SCA

### ISSUE THREAD

**Issue by jcruzlp** [wazuh/wazuh-packages#808]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3 | Agent | Install | Fedora |

Hello team, we need SPECS for these CIS Policies Files:
https://github.com/wazuh/wazuh/pull/9095

**Comment by DFolchA** [comment]
## Update Report

- [x] Add changes to SPECS 

## To do 
- [ ] Test packages
