### ISSUE TITLE
Fix RPM SPECS for 4.3.0

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-packages#812]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| master (4.3)| ManageI/Agent | Packaging | RPM |

Hi team!

Currently we are not able to create RPM packages because some errors/not updated on SPECS:
```
error: Installed (but unpackaged) file(s) found:
   /var/ossec/lib/libwazuhshared.so
   /var/ossec/tmp/sca-4.3.0-0.commit136d0d6-tmp/sles/15/cis_sles15_linux.yml
```
Regards,
Nico

**Comment by alberpilot** [comment]
Done.
