### ISSUE TITLE
4.1/4.2 - Unattended-installation.sh aws is broken in debug mode

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#839]
As part of the migration issue https://github.com/wazuh/wazuh-packages/issues/835 from wazuh-documentation to wazuh-packages, the installer is being tested to detect possible problems, specifically, the production installer in aws in 4.1 is broken:

https://packages.wazuh.com/resources/4.1/open-distro/unattended-installation/unattended-installation.sh

Log:  [wazuh-unattended-installation.log](https://github.com/wazuh/wazuh-packages/files/7093399/wazuh-unattended-installation.log)

Documentation: https://documentation.wazuh.com/4.1/installation-guide/open-distro/all-in-one-deployment/unattended-installation.html

Errors:

![4 1_1](https://user-images.githubusercontent.com/14913942/131722512-bcb8d5b6-65fe-41c6-8538-28be5f1575bd.png)

![4 1_2](https://user-images.githubusercontent.com/14913942/131722519-dc0a3af6-7fe7-4e6d-830c-a85814b7ebdf.png)

![4 1_3](https://user-images.githubusercontent.com/14913942/131722522-62d0bebb-7ce0-45ce-b4b4-202e1c9b0bf0.png)

![4 1_4](https://user-images.githubusercontent.com/14913942/131722524-b9e08ca1-7732-4eaf-a6a2-ad1e05424318.png)

Tested on Vagrant - Centos8, 4GB ram, 2 cpus

**Comment by rauldpm** [comment]
When running the command `curl -so ~/unattended-installation.sh https://packages.wazuh.com/resources/4.1/open-distro/unattended-installation/unattended-installation.sh && bash ~/unattended-installation.sh` without verbose (-v), the following output is obtained:

![image](https://user-images.githubusercontent.com/14913942/131726349-b64fbaf6-8dda-4ca1-8583-b2916f5474ff.png)

Apparently there is a difference between running with verbose and without verbose, this error about `wazuh-password-tools.sh` has not been detected when running with verbose, since this stage has not been reached

**Comment by rauldpm** [comment]
Subsequent executions without debugging have successfully completed the installation. This may be due to a temporary failure to get the aws file or some other cause. Needs verification.

After a successful installation, when executing the same command on a new machine in debug mode, it shows the same fault identified at the beginning of the issue.

**Comment by rauldpm** [comment]
Note: The debug mode applied by ova (remove the $ {debug} from the script and use set, does not cause installation failure in 4.2. 4.1 doesnt use unnatented script

**Comment by DFolchA** [comment]
## Update

- Test and reproduce the issue
- Look for the causes of the problem and fix them

### TO DO
- [ ] Test fixed script

**Comment by verdx** [comment]
Tested on 4.2 (CentOS 8, 4 GB, 2 CPUs), and the same errors can be seen:
```
Elasticsearch started
Initializing Elasticsearch...
/root/unattended-installation.sh: line 327: ./securityadmin.sh: No such file or directory
Done
Installing Filebeat...
```
```
.opendistro_security index does not exists, attempt to create it ... done (0-all replicas)
Will retrieve '_doc/config' into /usr/share/elasticsearch/backup/config.yml 
   FAIL: Configuration for 'config' failed because of empty source
Will retrieve '_doc/roles' into /usr/share/elasticsearch/backup/roles.yml 
   FAIL: Configuration for 'roles' failed because of empty source
Will retrieve '_doc/rolesmapping' into /usr/share/elasticsearch/backup/roles_mapping.yml 
   FAIL: Configuration for 'rolesmapping' failed because of empty source
Will retrieve '_doc/internalusers' into /usr/share/elasticsearch/backup/internal_users.yml 
   FAIL: Configuration for 'internalusers' failed because of empty source
Will retrieve '_doc/actiongroups' into /usr/share/elasticsearch/backup/action_groups.yml 
   FAIL: Configuration for 'actiongroups' failed because of empty source
Will retrieve '_doc/tenants' into /usr/share/elasticsearch/backup/tenants.yml 
   FAIL: Configuration for 'tenants' failed because of empty source
Will retrieve '_doc/nodesdn' into /usr/share/elasticsearch/backup/nodes_dn.yml 
   SUCC: Configuration for 'nodesdn' stored in /usr/share/elasticsearch/backup/nodes_dn.yml
Will retrieve '_doc/whitelist' into /usr/share/elasticsearch/backup/whitelist.yml 
   SUCC: Configuration for 'whitelist' stored in /usr/share/elasticsearch/backup/whitelist.yml
Will retrieve '_doc/audit' into /usr/share/elasticsearch/backup/audit.yml 
   FAIL: Configuration for 'audit' failed because of empty source
Error: The backup could not be created
The passwords could not be changed
Cleaning the installation
```
```
Installation cleaned. Check the /var/log/wazuh-unattended-installation.log file to learn more about the issue.
```

**Comment by verdx** [comment]
The three previous PRs fix all of the problems in this issue
