### ISSUE TITLE
Improve the unattended installation scripts progress bars

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-packages#865]
| Version      | Documents affected
| -------------  | -------------  |
| 4.1             | unattended-installation.sh |

The unattended installation scripts may lead to confusion when installing since some steps may take a lot of time. 

The scripts should show more dynamic and graphical progress bars to clarify to the users that the script is still running.

Regards,

David

**Comment by verdx** [comment]
I'm having some problems with erasing the screen to write again with tput. The goal is to make a progress bar that stays in the last line as the rest of the output is written above it using a buffer.

**Comment by verdx** [comment]
Today I managed to get the progress bars working correctly. I'm going to solve issue #984, as it will make it a lot easier to implement the progress bars.

**Comment by verdx** [comment]
I added the progressBar to all installers, but I run into a problem. When calling to wazuh-cert-tool and wazuh-passwords-tool the progress bar is compromised, as they have their own unbuffered outputs, I must find a way to put their outputs into the buffer.

**Comment by alberpilot** [comment]
Merged into unified branch

**Comment by alberpilot** [comment]
We decided to cancel the progress bar and replace it with a spinner. 
In addition to this, we want to catch any user control - c during the installer execution and ask the user if it's really necessary to stop the installer.

**Comment by verdx** [comment]
Closed with https://github.com/wazuh/wazuh-packages/pull/1113
