### ISSUE TITLE
Unify unattended scripts

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-packages#867]
| Version      | Documents affected
| -------------  | -------------  |
| 4.x             | unattended-installation.sh |

Hello team! 

The aim of this issue is to unify all the unattended installation scripts.

We should use a single script for the following installations:

- Unattended all-in-one installation ODFE (first iteration)
- Unattended distributed installation ODFE (first iteration)
- Unattended all-in-one installation basic license (second iteration)
- Unattended distributed installation basic license (second iteration)

We should use the same options as we are using now for the single components installation:
- e: Elasticsearch
- k: Kibana

And we must add the following options:
-w: Wazuh + Filebeat
- b: install the basic license components. This must be used along with one of the options above.

Regards,

David

**Comment by DFolchA** [comment]
After discussing with the team we decided that this unification process will consist of a design change for the unattended script.

The main script will receive a series of parameters:
```
-A    All-in-one installation
-w    Wazuh + filebeat installation
-e    Elasticsearch installation
-k    Kibana installation
-b    Use Elasticsearch basic instead of Opendistro
```

Then depending on these parameters, the script will download a series of bash files containing the necessary functions to perform the installation and import them.

This will help to make the unattended script easier to maintain and upgrade.

Finally, the directory structure containing the unattended scripts will change:

```
unattended_scripts/
├── config
│   ├── elasticsearch_basic
│   │   ├── elasticsearch
│   │   │   └── 7.x
│   │   │       ├── elasticsearch_all_in_one.yml
│   │   │       ├── elasticsearch_cluster_initial_node.yml
│   │   │       ├── elasticsearch_cluster_subsequent_nodes.yml
│   │   │       ├── elasticsearch_cluster.yml
│   │   │       └── elasticsearch.yml
│   │   ├── filebeat
│   │   │   └── 7.x
│   │   │       ├── filebeat_all_in_one.yml
│   │   │       ├── filebeat_elastic_cluster.yml
│   │   │       └── filebeat.yml
│   │   ├── instances_aio.yml
│   │   └── kibana
│   │       └── 7.x
│   │           ├── kibana_all_in_one.yml
│   │           └── kibana.yml
│   └── opendistro
│       ├── elasticsearch
│       │   ├── 7.x
│       │   │   ├── elasticsearch_all_in_one.yml
│       │   │   ├── elasticsearch_cluster_initial_node.yml
│       │   │   ├── elasticsearch_cluster_subsequent_nodes.yml
│       │   │   ├── elasticsearch_unattended.yml
│       │   │   ├── elasticsearch.yml
│       │   │   └── wazuh-template.json
│       │   └── roles
│       │       ├── internal_users.yml
│       │       ├── roles_mapping.yml
│       │       └── roles.yml
│       ├── filebeat
│       │   └── 7.x
│       │       ├── filebeat_all_in_one.yml
│       │       ├── filebeat_elastic_cluster.yml
│       │       ├── filebeat_unattended.yml
│       │       ├── filebeat.yml
│       │       └── wazuh-module
│       │           ├── alerts
│       │           │   ├── config
│       │           │   │   └── alerts.yml
│       │           │   ├── ingest
│       │           │   │   └── pipeline.json
│       │           │   └── manifest.yml
│       │           ├── archives
│       │           │   ├── config
│       │           │   │   └── archives.yml
│       │           │   ├── ingest
│       │           │   │   └── pipeline.json
│       │           │   └── manifest.yml
│       │           ├── _meta
│       │           │   ├── config.yml
│       │           │   ├── docs.asciidoc
│       │           │   └── fields.yml
│       │           └── module.yml
│       ├── kibana
│       │   └── 7.x
│       │       ├── kibana_all_in_one.yml
│       │       ├── kibana_unattended.yml
│       │       └── kibana.yml
│       ├── searchguard
│       │   ├── multi-node
│       │   │   ├── search-guard-multi-node.yml
│       │   │   └── search-guard.yml
│       │   ├── search-guard-aio.yml
│       │   └── single-node
│       │       ├── search-guard-multi-node.yml
│       │       └── search-guard.yml
│       └── tools
│           ├── certificate-utility
│           │   ├── instances_aio.yml
│           │   ├── instances.yml
│           │   └── wazuh-cert-tool.sh
│           └── wazuh-passwords-tool.sh
├── install_functions
│   ├── elasticsearch_basic
│   │   ├── elasticsearch.sh
│   │   ├── kibana.sh
│   │   └── wazuh.sh
│   └── opendistro
│       ├── elasticsearch.sh
│       ├── kibana.sh
│       └── wazuh.sh
└── unattended_installation.sh
```

**Comment by DFolchA** [comment]
## Update

**Working branch:** https://github.com/wazuh/wazuh-packages/tree/unify-unattended

- Restructure unattended scripts directory.
- Start main script `unattended_installation.sh`
- Finish Wazuh + Filebeat installation functions.

**Comment by DFolchA** [comment]
## Update

**Working branch:** https://github.com/wazuh/wazuh-packages/tree/unify-unattended

- Work on Elasticsearch installation script and OD configuration
- Add Elasticsearch to main script

**Comment by DFolchA** [comment]
## Update

**Working branch:** https://github.com/wazuh/wazuh-packages/tree/unify-unattended

- Finish setting for AIO installation

## To Do 
- Test AIO installation 
- Configure distributed installation

**Comment by DFolchA** [comment]
## Update
**Working branch:** https://github.com/wazuh/wazuh-packages/tree/unify-unattended

Work in unattended AIO installation and fix some errors. Currently, all packages are installed correctly but there is a problem with the certificates:
```
Nov 10 17:11:23 centos7 kibana[1908]: {"type":"log","@timestamp":"2021-11-10T17:11:23Z","tags":["info","savedobjects-service"],"pid":1908,"message":"Waiting until all Elasticsearch nodes are compatible with Kibana before starting saved objects migrations..."}
Nov 10 17:11:23 centos7 kibana[1908]: {"type":"log","@timestamp":"2021-11-10T17:11:23Z","tags":["error","elasticsearch","data"],"pid":1908,"message":"[ConnectionError]: unable to verify the first certificate"}
Nov 10 17:11:23 centos7 kibana[1908]: {"type":"log","@timestamp":"2021-11-10T17:11:23Z","tags":["error","savedobjects-service"],"pid":1908,"message":"Unable to retrieve version information from Elasticsearch nodes."}
Nov 10 17:11:26 centos7 kibana[1908]: {"type":"log","@timestamp":"2021-11-10T17:11:26Z","tags":["error","elasticsearch","data"],"pid":1908,"message":"[ConnectionError]: unable to verify the first certificate"}
Nov 10 17:11:28 centos7 kibana[1908]: {"type":"log","@timestamp":"2021-11-10T17:11:28Z","tags":["error","elasticsearch","data"],"pid":1908,"message":"[ConnectionError]: unable to verify the first certificate"}

```

**Comment by DFolchA** [comment]
## Update

**Working branch:** https://github.com/wazuh/wazuh-packages/tree/unify-unattended

- AIO installation finished and testing
- Work on distributed installation

**Comment by DFolchA** [comment]
## Update

**Working branch:** https://github.com/wazuh/wazuh-packages/tree/unify-unattended

- Added certificate and password tools to unattended as functions.
- Finish distributed installation and test.
