### ISSUE TITLE
Escaping character $ in unattended script yum repo setting

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#869]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.2.0 | Manager | Install| Unattended |

We found that there is a bug related to the usage of `$` character when setting yum repositories, check this for further detail:
https://bugzilla.redhat.com/show_bug.cgi?id=1913008

We need to escape the character using `\` so the variables can be substituted correctly.

https://github.com/wazuh/wazuh-packages/blob/4334eddd7c0a74b6c6f23b9028314da766747796/resources/open-distro/unattended-installation/all-in-one-installation.sh#L176

**Comment by verdx** [comment]
We have made the changes proposed. Adding the escape character before `$` makes the variable recognizable and is so substituted correctly upon usage of the repository. 
![repolist](https://user-images.githubusercontent.com/61122643/137096797-13f2ffdd-fd75-47e8-bb73-1946a8fda385.png)
