### ISSUE TITLE
Allow upgrades with unattended script

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#877]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.2.0 | Managert | Install/Upgrade | unattended script |

We need to add the necessary tools to the unattended scripts so it is possible to use it to upgrade an already existing installation.

The unattended script will need to check if the versions of every component (wazuh-manager, elasticsearch, etc) are correspond with the latest version and upgrade the ones that are outdated.

**Comment by alberpilot** [comment]
Duplicated: https://github.com/wazuh/wazuh-packages/issues/862
