### ISSUE TITLE
Error in macOS agent upgrade from 4.1.5 to 4.3.0 via pkg

### ISSUE THREAD

**Issue by Nicogp** [wazuh/wazuh-packages#880]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.0 | Agent | Upgrade | macOS |

Hello team,

There are some issues in the macOS agent upgrade process via .pkg.

Steps to reproduce it:
Install and run macOS agent version 4.1.5:
`launchctl setenv WAZUH_MANAGER "manager_address" && installer -pkg wazuh-agent-4.1.5-2.pkg -target /`

If I upgrade an macOS to 4.3.0 agent I get the following error:
```
#installer -pkg wazuh-agent-4.3.0-x.pkg -target /
installer: Package name is Wazuh Agent
installer: Upgrading at base path /
installer: The upgrade failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package "wazuh-agent-4.3.0-x.pkg".)
```

And in the ossec.log I see this error:
```
# cat /Library/Ossec/logs/ossec.log 
2021/09/14 11:31:22 wazuh-execd: CRITICAL: (1203): Invalid user '' or group 'wazuh' given: Undefined error: 0 (0)
```
There seems to be a problem with changing the `user `from `ossec` to `wazuh`, so it probably affects other versions that want to upgrade to 4.3.0.

**Comment by DFolchA** [comment]
## Update

Working branch: https://github.com/wazuh/wazuh-packages/tree/880-macos-user

Fixed problem with postinstall deletion of old groups.
