### ISSUE TITLE
Unattended installation improvements

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-packages#882]
The unattended installation scripts must be improved:

- [x] Add a network test before the installation
- [x] Let the script be run more than twice. Check if the components are already installed and update them if possible. Besides we should make a backup of the configuration files.
- [ ] Improve the progress bars making them more graphical and dynamic. Sometimes the script seems to be frozen depending on the host specs.
- [x] Improve the error handling. We must provide more detailed information about the possible error that may occur during the installation.
- [x] If the installation fails, the script must do a rollback.
- [x] Improve the configuration file reading process. In order to avoid issues when adding/removing blank lines to the script configuration files, the new script should read all the information into an array trimming spaces and blank lines.
- [x] Include the certificate tool wazuh/wazuh-documentation#3128 
- [x] The script should randomize the passwords for the default users

Regards,
David

**Edit by** @alberpilot 
The script must accomplish the following points:
- [ ] The script unification. Same script for all installation types or deployment. 
- [x] Memory, disk space, CPU, architecture, and operating system must be validated by health check. If something doesn't match with the expected requirements, it will show an error explaining the minimum requirements. 
- [ ] If the host where the script is run has not an internet connection, a message about how to install offline must be done (with the package list). 
- [x] Check previous installations: it doesn't exist the installation goes normal. If exist a previous installation of any Filebeat, Wazuh manager, Elasticsearch, or Kibana, the script will exit with a warning message: if the user wants to overwrite the existent components must run the script with the --overwrite flag (or similar flag).
- [ ] The script must auto-detect if Elastic basic or opendistro is installed. Then, if all components are working properly but are outdated, then a warning message is showed about the upgrade possibility of running the script with --upgrade flag (I.e). If a not latest version is installed but not working, an overwrite must be proposed indicating the upgrade. 
- [x] In a fresh install, if something goes wrong, the script must indicate what step went wrong and clean the installation, removing all installed components and files. 
- [x] In a overwrite because indicated with an option, if something goes wrong, there is no possibility of rollback. It requires manual analysis. All errors must be reported. 
- [ ] The progress bar must be improved, all people must know if the script is running properly every 2/4 seconds. 
- [ ] Only download packages option. Download packages in tar.gz.

**Comment by alberpilot** [comment]
All tasks are included here: #834
