### ISSUE TITLE
Source 0 doesn't exist

### ISSUE THREAD

**Issue by scottrp21** [wazuh/wazuh-packages#9]
When trying to build an RPM using the provided spec file it is unable to pull the tar.gz file

Name:        wazuh-manager
Version:     2.1.1
Release:     1%{?dist}
License:     GPL
Group:       System Environment/Daemons
Source0:     https://github.com/wazuh/ossec-wazuh/archive/%{name}-%{version}.tar.gz

Source0 would be filled in as (https://github.com/wazuh/ossec-wazuh/archive/wazuh-manager-2.1.1.tar.gz)

When the above link is entered it redirects to (https://codeload.github.com/wazuh/wazuh/tar.gz/wazuh-manager-2.1.1) and returns a 404: Not Found.

Is the intended file supposed to be https://github.com/wazuh/wazuh/archive/v2.1.1.tar.gz ?

Please let me know if the file has been moved or is located else where? I run into the same issue with agent and API.

**Comment by erseco** [comment]
Hi @scottrp21,

It was a mistake, now the source0 link point to the correct URL

Thank you for your advice!

**Comment by scottrp21** [comment]
my only question i have then is previously it was going to a different tar.gz for each build (wazuh-manager & wazuh-agent) is this no longer the case?

**Comment by erseco** [comment]
No, is the same code. In the build process of the SPEC we set the compilation flag to build agent or manager, but the codebase is the same.

Bes regards!
