### ISSUE TITLE
Grant Wazuh administrator permissions to the wazuh user (OVA and unattended installation)

### ISSUE THREAD

**Issue by s-ocando** [wazuh/wazuh-packages#901]
The WUI's `wazuh` user, used as the default user in the OVA and the unattended installation, does not have administrator permissions granted by default. Only `admin` and `elastic` users are mapped as administrators by [default.](https://documentation.wazuh.com/current/user-manual/api/rbac/reference.html#default-rules) 

When `run_as` is enabled, the `wazuh` user is left without administrative privileges which can be inconvenient.  I suggest adding a mapping as administrator for the `wazuh` user in the OVA as well as in the unattended installation script. 
![image](https://user-images.githubusercontent.com/61882981/134642433-9b901ca6-400f-4bb4-8842-2179a1fea622.png)

**Comment by rauldpm** [comment]
Issue closed due to merged PR.
