### ISSUE TITLE
Remove cmd pop up windows during installation on Windows

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-packages#906]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.2.2 | Agent | Install | Windows |

During the installation of a Windows agent a few cmd windows quickly flash. 

![output](https://user-images.githubusercontent.com/36071202/135337809-80f06a3d-a3f7-4320-92b6-dccde0297210.gif)

The installation process would provide a cleaner experience if these are not shown.  It may be possible to use [WixQuietExecCA as explained here](https://stackoverflow.com/questions/13535061/wix-hide-cmd-line-window).

**Comment by DFolchA** [comment]
## Update 

Found calls to [icacls](https://github.com/wazuh/wazuh/blob/46f640b8684136047e8e6b0af3e0ca034b863f5f/src/win32/InstallerScripts.vbs#L203) in `InstallerScripts.vbs ` that caused popup windows to appear. We have silenced them in this commit:
https://github.com/wazuh/wazuh/commit/21c72419a4942471eadc8fc25aeb01d72737c5f8

### Before fix

https://user-images.githubusercontent.com/19505384/139837159-d276600d-5351-49f0-995f-2b49d80ae576.mp4

### After fix

https://user-images.githubusercontent.com/19505384/139837193-74d41d21-f140-4e46-a332-e709e22c9d22.mp4

**Comment by DFolchA** [comment]
## Update
Hide agent-auth.exe prompt when using deployment vars.

**Comment by DFolchA** [comment]
## Update 

Hide all the popups that appear when using deployment variables.

### MSI 4.2.4

https://user-images.githubusercontent.com/19505384/140085687-e7d2c4a6-cdcd-4390-ab9b-52413f0ea866.mp4

### MSI 4.3.0 after fix

https://user-images.githubusercontent.com/19505384/140085797-952e09bf-3d35-4f75-80c1-97d3384ef2a7.mp4

**Comment by jctello** [comment]
It would be great to see one with `/q` to really compare the behavior to the originally reported issue.

**Comment by DFolchA** [comment]
## Update

## Quiet installation

https://user-images.githubusercontent.com/19505384/140292590-57090a13-5308-4ba4-9d48-12dca9133006.mp4
