### ISSUE TITLE
Fix wazuh-passwords-tool.sh in opensuse tumbleweed

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#916]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.1/4.2 | Bash | Change passwords script | OpenSUSE Tumbleweed |

Hello team,

An user has reported to us that in OpenSUSE Tumbleweed the script that changes the passwords does not correctly detect that Open Distro is installed, this causes users to have to fix the bug themselves or keep the default passwords.

![image](https://user-images.githubusercontent.com/14913942/135898594-db666628-3690-4110-9cb8-60cf6b8b5a10.png)
![image](https://user-images.githubusercontent.com/14913942/135898693-4f33d9ab-0f1e-4889-ace9-5b43b4a7f8c1.png)

**Comment by verdx** [comment]
I have fixed one of the problems, --installed was used instead of --installed-only when trying to see if packages are installed. The other problem is it looks for noarch packages and zypper installs x86_64, but I still need to know why it looks for noarch

**Comment by verdx** [comment]
I have it done, but I'm waiting for the PRs for issue #984 to be closed, as I'm modifying the same files and to avoid conflicts.
