### ISSUE TITLE
Fix kibana.yml password when modifying a specific user password with wazuh-passwords-tool.sh script

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#920]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.1/4.2 | Bash | Change passwords script | * |

Hello team,

Testing the Wazuh AMI, an error derived from changing the passwords of the opendistro users was found, specifically, in the AMI it is necessary to change all the passwords for the instance_id of the instance. This functionality is not implemented and it is only allowed to change the password to all users (randomized) or one by one indicating the password that you want, this brings the problem that every time the password is changed to an user, the services stop and start.

In addition, an error has been found and it is the following: When changing the password of a user (for example the wazuh user, which has its password specified in filebeat.yml) the password of the kibanaserver user specified in the kibana.yml file is removed. This should not be the case and should only affect the user whose password is changed.

Error given: 

`kibana[4375]: FATAL Error: [config validation of [elasticsearch].password]: expected value of type [string] but got [null]`

![image](https://user-images.githubusercontent.com/14913942/136428512-19cae3f0-9667-4934-9a99-326e948a9d28.png)

This issue aims to:

- [ ] Add the functionality to specify the same password given to all users
- [ ] Fix the problem with the password of the kibanaserver user

**Comment by verdx** [comment]
When fixing the bug stated in the issue, I encountered another one. The password of the kibanaserver couldn't be changed alone, as the code to change it was inside an if statement only accessed when the password changed was the one from wazuh or all the passwords were being changed. I have fixed this in PR's https://github.com/wazuh/wazuh-packages/pull/929, https://github.com/wazuh/wazuh-packages/pull/930 and https://github.com/wazuh/wazuh-packages/pull/931

**Comment by DFolchA** [comment]
Allowing to set all the passwords to the same value is not a good security practice and may lead to security issues, to try to minimize this instead of using:

```
bash wazuh-passwords-tool.sh -a -p SecretPassword
```

We have decided to add an option to get the passwords from a formatted file:

```
bash wazuh-passwords-tool.sh -f /path/to/pass.yml
```

The fille will have a format similar to this:

```
User: 
    name: Wazuh
    password: SecretPassword2

User: 
    name: elasticsearch
    password: SecretPassword2

....
```

If the `-a` option is used in conjunction with `-f` the passwords of the users not included in the file will be randomized.
