### ISSUE TITLE
Add custom login page in unattended script instead in the OVA/AMI build process

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#943]
Hello team,

Both the OVA and AWS AMI are built using the unattended script, in each of them, a configuration is made to have a personalized Kibana login page that changes the background, the title of the window and the title that It is displayed above the username and password forms.

It would be convenient to study and implements those procedures in the unattended script instead of performing them during the installation of the OVA/AMI.

Current:
![image](https://user-images.githubusercontent.com/14913942/138516240-513cbe2d-128e-4a9b-8d67-a8c0eaaf5fe8.png)

Desired:
![image](https://user-images.githubusercontent.com/14913942/138516308-59f4752c-7df7-443b-a99c-028723e72891.png)

Regards, Raúl.

**Comment by verdx** [comment]
I've got it figured as to add this block of code in the kibana installation:
```
        # Edit window title
        eval "sed -i 's/null, \"Elastic\"/null, \"Wazuh\"/g' /usr/share/kibana/src/core/server/rendering/views/template.js ${debug}"
        eval "curl -so ~/custom_welcome.tar.gz https://wazuh-demo.s3-us-west-1.amazonaws.com/custom_welcome_opendistro_docker.tar.gz ${debug}"
        eval "tar -xf ~/custom_welcome.tar.gz -C ~ ${debug}"
        eval "cp ~/custom_welcome/wazuh_logo_circle.svg /usr/share/kibana/src/core/server/core_app/assets/ ${debug}"
        eval "cp ~/custom_welcome/wazuh_wazuh_bg.svg /usr/share/kibana/src/core/server/core_app/assets/ ${debug}"
        eval "cp -f ~/custom_welcome/template.js.hbs /usr/share/kibana/src/legacy/ui/ui_render/bootstrap/template.js.hbs ${debug}"
        eval "curl -so ~/customWelcomeKibana.css ${resources}/open-distro/kibana/customWelcomeKibana.css ${debug}"
        eval "less ~/customWelcomeKibana.css >> /usr/share/kibana/src/core/server/core_app/assets/legacy_light_theme.css ${debug}"
```
It has given some problems not detecting correctly `customWelcomeKibana.css` in local, but I seem to have solved it. Right now the branches still don't complete an unattended installation. More testing is needed for every type of kibana installation possible in the unattended. The rest of branches and their PRs also need to be done the next day.

**Comment by verdx** [comment]
The all-in-one unattended installation currently works on all pulls except on the unified branch. I haven't been able to find the problem there yet. The login screen after the unified all-in-one  installation is the same as when in the others this command is not run correctly:
```
eval "cat ~/customWelcomeKibana.css | tee -a /usr/share/kibana/src/core/server/core_app/assets/legacy_light_theme.css ${debug}"
```
The problem is, the command is run correctly, the contents of `customWelcomeKibana.css` are appended to `/usr/share/kibana/src/core/server/core_app/assets/legacy_light_theme.css`
In the case of the distributed installation, it gets stuck on here:
```
11/29/2021 12:49:20 INFO: Initializing Kibana (this may take a while)
.........................................................
```

**Comment by verdx** [comment]
Tried the unified option and it seems to install properly, but kiibana can't be accessed from the browser. `journalctl -u kibana` returns:
```
Dec 01 09:53:02 centos7 kibana[4291]: {"type":"log","@timestamp":"2021-12-01T09:53:02Z","tags":["fatal","
Dec 01 09:53:02 centos7 kibana[4291]: FATAL  Error: Plugin with id "wazuh" is already registered!
```
