### ISSUE TITLE
Fix template wazuh-alerts-* in distributed unattended installer 

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#967]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.2/4.3 | Unattended distributed | Install | - |

Hello team,

When testing the unattended I have realized that there is a failure in the unattended installation in a distributed way, the failure is that when performing the health check it does not find the template index pattern title wazuh-alerts-*

![image](https://user-images.githubusercontent.com/14913942/139909088-78b25eed-14e8-41a0-8eec-d53f2742e4f1.png)

Regards Raúl.

**Comment by alberpilot** [comment]
Solved
