### ISSUE TITLE
securityadmin.sh failing on Unattended install

### ISSUE THREAD

**Issue by fhielpos** [wazuh/wazuh-packages#974]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.2 | Manager | Install | OS version |

Hello team,

We have seen that on some Operating Systems, the `securityadmin.sh` execution fails:

```
Initializing Elasticsearch...
./unattended-installation.sh: line 328: ./securityadmin.sh: No such file or directory
```

Which makes the installation to hang up on the final step:

```
Initializing Kibana (this may take a while)
........................
```

We can also see that the `filebeat test output` fails because of the same:

```
Kibana started
Done
Checking the installation...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    37  100    37    0     0    344      0 --:--:-- --:--:-- --:--:--   345
Open Distro Security not initialized.Elasticsearch installation succeeded.
elasticsearch: https://127.0.0.1:9200...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: 127.0.0.1
    dial up... OK
  TLS...
    security: server's certificate chain verification is enabled
    handshake... OK
    TLS version: TLSv1.3
    dial up... OK
  talk to server... ERROR 503 Service Unavailable: Open Distro Security not initialized.
Filebeat installation succeeded.
```

This has been replicated on `Centos/7` and `aspyatkin/ubuntu-20.04-server` Vagrant boxes.

## Possible solution

It seems that the issue comes from these lines:

```bash
        eval "cd /usr/share/elasticsearch/plugins/opendistro_security/tools/ ${debug}"
        eval "./securityadmin.sh -cd ../securityconfig/ -icl -nhnv -cacert /etc/elasticsearch/certs/root-ca.pem -cert /etc/elasticsearch/certs/admin.pem -key /etc/elasticsearch/certs/admin-key.pem ${debug}"
```

If we change these for a one-liner:

```bash
        eval "/usr/share/elasticsearch/plugins/opendistro_security/tools/securityadmin.sh -cd /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/ -icl -nhnv -cacert /etc/elasticsearch/certs/root-ca.pem -cert /etc/elasticsearch/certs/admin.pem -key /etc/elasticsearch/certs/admin-key.pem ${debug}"
```

The installation finishes properly.

Also, even though the `wazuh-passwords-tool.sh` uses the same approach, it runs properly.

**Comment by rauldpm** [comment]
Related to https://github.com/wazuh/wazuh-packages/issues/839

**Comment by verdx** [comment]
There are other two occasions on the installer where `cd` is used and fails when using debug, but they don`t create further problems so they haven't been detected:
```
 eval "cd /etc/elasticsearch/certs ${debug}"
```
```
eval "cd /usr/share/kibana ${debug}"

```
Everytime`cd` is used in a command pipelined into another, it doesn't work. The solution seems to be, as said before, to remove `cd` and use full paths wherever possible.
