### ISSUE TITLE
Add libfimdb.so to SPECS, new fim library

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh-packages#989]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| [9103-replace-fim-db-dbsync](https://github.com/wazuh/wazuh/tree/9103-replace-fim-db-dbsync) | Manager/API/Agent | Install/Upgrade/Remove | all |

## Description
Hello team, 
we are working with this epic:
https://github.com/wazuh/wazuh/issues/9103

And we have needed to make some changes in the FIM compilation, among them, we have created new dynamic libraries to compile the new fimdb with dbsync, in c++.
It is necessary to modify the SPECS of the packages so that the new library files are generated correctly.

The name and path of the library in Linux is:
`/var/ossec/lib/libfimdb.so`

**Comment by antoniomanuelfr** [comment]
Working branch: https://github.com/wazuh/wazuh-packages/tree/989-add-libfimdb-specs

**Comment by antoniomanuelfr** [comment]
## Tests performed

# Ubuntu Manager
- [X] Package generation
- [X] Package Install
# Centos Manager
- [X] Package generation
- [ ] Package Install
# Ubuntu agent
- [ ] Package generation
- [ ] Package install
# CentOS agent
- [ ] Package generation
- [ ] Package install

**Comment by antoniomanuelfr** [comment]
Closed https://github.com/wazuh/wazuh-packages/pull/1134
