### ISSUE TITLE
SPECS request for HPUX SCA

### ISSUE THREAD

**Issue by jcruzlp** [wazuh/wazuh-packages#997]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3/4.4 | Agent | Install | HP UX 11i |

Hello team, we just created a new SCA policy for HPUX and need SPECS for it, this is the PR we're working with https://github.com/wazuh/wazuh/pull/10862
Also added the SCA path in the templates files.

**Comment by alberpilot** [comment]
Closing issue due to no packages available for HP-UX (we build a tar file).
